function TSynWebEngine.HtmlAttrUndef: TSynWebTokenKind;
begin
  Result:=stkHtmlTagKeyUndef;
end;

function TSynWebEngine.HtmlAttrFunc13: TSynWebTokenKind;
begin
  if  HtmlAttrKeyComp(55) then
    Result := stkHtmlTagKey
  else
    Result := stkHtmlTagKeyUndef;
end;

function TSynWebEngine.HtmlAttrFunc15: TSynWebTokenKind;
begin
  if  HtmlAttrKeyComp(45) then
    Result := stkHtmlTagKey
  else
    Result := stkHtmlTagKeyUndef;
end;

function TSynWebEngine.HtmlAttrFunc23: TSynWebTokenKind;
begin
  if  HtmlAttrKeyComp(0) then
    Result := stkHtmlTagKey
  else
    Result := stkHtmlTagKeyUndef;
end;

function TSynWebEngine.HtmlAttrFunc26: TSynWebTokenKind;
begin
  if  HtmlAttrKeyComp(32) then
    Result := stkHtmlTagKey
  else
    Result := stkHtmlTagKeyUndef;
end;

function TSynWebEngine.HtmlAttrFunc27: TSynWebTokenKind;
begin
  if  HtmlAttrKeyComp(23) then
    Result := stkHtmlTagKey
  else
    Result := stkHtmlTagKeyUndef;
end;

function TSynWebEngine.HtmlAttrFunc30: TSynWebTokenKind;
begin
  if  HtmlAttrKeyComp(15) then
    Result := stkHtmlTagKey
  else
    Result := stkHtmlTagKeyUndef;
end;

function TSynWebEngine.HtmlAttrFunc31: TSynWebTokenKind;
begin
  if  HtmlAttrKeyComp(40) then
    Result := stkHtmlTagKey
  else
    Result := stkHtmlTagKeyUndef;
end;

function TSynWebEngine.HtmlAttrFunc32: TSynWebTokenKind;
begin
  if  HtmlAttrKeyComp(57) or
      HtmlAttrKeyComp(65) then
    Result := stkHtmlTagKey
  else
    Result := stkHtmlTagKeyUndef;
end;

function TSynWebEngine.HtmlAttrFunc33: TSynWebTokenKind;
begin
  if  HtmlAttrKeyComp(7) or
      HtmlAttrKeyComp(68) then
    Result := stkHtmlTagKey
  else
    Result := stkHtmlTagKeyUndef;
end;

function TSynWebEngine.HtmlAttrFunc34: TSynWebTokenKind;
begin
  if  HtmlAttrKeyComp(58) then
    Result := stkHtmlTagKey
  else
    Result := stkHtmlTagKeyUndef;
end;

function TSynWebEngine.HtmlAttrFunc35: TSynWebTokenKind;
begin
  if  HtmlAttrKeyComp(95) then
    Result := stkHtmlTagKey
  else
    Result := stkHtmlTagKeyUndef;
end;

function TSynWebEngine.HtmlAttrFunc37: TSynWebTokenKind;
begin
  if  HtmlAttrKeyComp(19) or
      HtmlAttrKeyComp(51) then
    Result := stkHtmlTagKey
  else
    Result := stkHtmlTagKeyUndef;
end;

function TSynWebEngine.HtmlAttrFunc38: TSynWebTokenKind;
begin
  if  HtmlAttrKeyComp(39) then
    Result := stkHtmlTagKey
  else
    Result := stkHtmlTagKeyUndef;
end;

function TSynWebEngine.HtmlAttrFunc39: TSynWebTokenKind;
begin
  if  HtmlAttrKeyComp(18) or
      HtmlAttrKeyComp(22) or
      HtmlAttrKeyComp(46) then
    Result := stkHtmlTagKey
  else
    Result := stkHtmlTagKeyUndef;
end;

function TSynWebEngine.HtmlAttrFunc40: TSynWebTokenKind;
begin
  if  HtmlAttrKeyComp(107) then
    Result := stkHtmlTagKey
  else
    Result := stkHtmlTagKeyUndef;
end;

function TSynWebEngine.HtmlAttrFunc43: TSynWebTokenKind;
begin
  if  HtmlAttrKeyComp(5) or
      HtmlAttrKeyComp(47) then
    Result := stkHtmlTagKey
  else
    Result := stkHtmlTagKeyUndef;
end;

function TSynWebEngine.HtmlAttrFunc45: TSynWebTokenKind;
begin
  if  HtmlAttrKeyComp(96) then
    Result := stkHtmlTagKey
  else
    Result := stkHtmlTagKeyUndef;
end;

function TSynWebEngine.HtmlAttrFunc46: TSynWebTokenKind;
begin
  if  HtmlAttrKeyComp(60) then
    Result := stkHtmlTagKey
  else
    Result := stkHtmlTagKeyUndef;
end;

function TSynWebEngine.HtmlAttrFunc47: TSynWebTokenKind;
begin
  if  HtmlAttrKeyComp(6) then
    Result := stkHtmlTagKey
  else
    Result := stkHtmlTagKeyUndef;
end;

function TSynWebEngine.HtmlAttrFunc48: TSynWebTokenKind;
begin
  if  HtmlAttrKeyComp(1) or
      HtmlAttrKeyComp(33) or
      HtmlAttrKeyComp(38) then
    Result := stkHtmlTagKey
  else
    Result := stkHtmlTagKeyUndef;
end;

function TSynWebEngine.HtmlAttrFunc49: TSynWebTokenKind;
begin
  if  HtmlAttrKeyComp(27) or
      HtmlAttrKeyComp(104) then
    Result := stkHtmlTagKey
  else
    Result := stkHtmlTagKeyUndef;
end;

function TSynWebEngine.HtmlAttrFunc50: TSynWebTokenKind;
begin
  if  HtmlAttrKeyComp(106) then
    Result := stkHtmlTagKey
  else
    Result := stkHtmlTagKeyUndef;
end;

function TSynWebEngine.HtmlAttrFunc52: TSynWebTokenKind;
begin
  if  HtmlAttrKeyComp(53) then
    Result := stkHtmlTagKey
  else
    Result := stkHtmlTagKeyUndef;
end;

function TSynWebEngine.HtmlAttrFunc53: TSynWebTokenKind;
begin
  if  HtmlAttrKeyComp(9) or
      HtmlAttrKeyComp(100) then
    Result := stkHtmlTagKey
  else
    Result := stkHtmlTagKeyUndef;
end;

function TSynWebEngine.HtmlAttrFunc54: TSynWebTokenKind;
begin
  if  HtmlAttrKeyComp(20) or
      HtmlAttrKeyComp(24) then
    Result := stkHtmlTagKey
  else
    Result := stkHtmlTagKeyUndef;
end;

function TSynWebEngine.HtmlAttrFunc55: TSynWebTokenKind;
begin
  if  HtmlAttrKeyComp(73) then
    Result := stkHtmlTagKey
  else
    Result := stkHtmlTagKeyUndef;
end;

function TSynWebEngine.HtmlAttrFunc56: TSynWebTokenKind;
begin
  if  HtmlAttrKeyComp(41) then
    Result := stkHtmlTagKey
  else
    Result := stkHtmlTagKeyUndef;
end;

function TSynWebEngine.HtmlAttrFunc57: TSynWebTokenKind;
begin
  if  HtmlAttrKeyComp(16) or
      HtmlAttrKeyComp(50) then
    Result := stkHtmlTagKey
  else
    Result := stkHtmlTagKeyUndef;
end;

function TSynWebEngine.HtmlAttrFunc58: TSynWebTokenKind;
begin
  if  HtmlAttrKeyComp(56) or
      HtmlAttrKeyComp(101) then
    Result := stkHtmlTagKey
  else
    Result := stkHtmlTagKeyUndef;
end;

function TSynWebEngine.HtmlAttrFunc59: TSynWebTokenKind;
begin
  if  HtmlAttrKeyComp(105) then
    Result := stkHtmlTagKey
  else
    Result := stkHtmlTagKeyUndef;
end;

function TSynWebEngine.HtmlAttrFunc60: TSynWebTokenKind;
begin
  if  HtmlAttrKeyComp(49) then
    Result := stkHtmlTagKey
  else
    Result := stkHtmlTagKeyUndef;
end;

function TSynWebEngine.HtmlAttrFunc61: TSynWebTokenKind;
begin
  if  HtmlAttrKeyComp(82) or
      HtmlAttrKeyComp(119) then
    Result := stkHtmlTagKey
  else
    Result := stkHtmlTagKeyUndef;
end;

function TSynWebEngine.HtmlAttrFunc62: TSynWebTokenKind;
begin
  if  HtmlAttrKeyComp(4) or
      HtmlAttrKeyComp(12) then
    Result := stkHtmlTagKey
  else
    Result := stkHtmlTagKeyUndef;
end;

function TSynWebEngine.HtmlAttrFunc63: TSynWebTokenKind;
begin
  if  HtmlAttrKeyComp(26) then
    Result := stkHtmlTagKey
  else
    Result := stkHtmlTagKeyUndef;
end;

function TSynWebEngine.HtmlAttrFunc64: TSynWebTokenKind;
begin
  if  HtmlAttrKeyComp(124) then
    Result := stkHtmlTagKey
  else
    Result := stkHtmlTagKeyUndef;
end;

function TSynWebEngine.HtmlAttrFunc65: TSynWebTokenKind;
begin
  if  HtmlAttrKeyComp(66) or
      HtmlAttrKeyComp(118) then
    Result := stkHtmlTagKey
  else
    Result := stkHtmlTagKeyUndef;
end;

function TSynWebEngine.HtmlAttrFunc66: TSynWebTokenKind;
begin
  if  HtmlAttrKeyComp(8) or
      HtmlAttrKeyComp(36) or
      HtmlAttrKeyComp(44) or
      HtmlAttrKeyComp(69) or
      HtmlAttrKeyComp(71) or
      HtmlAttrKeyComp(115) or
      HtmlAttrKeyComp(116) or
      HtmlAttrKeyComp(123) then
    Result := stkHtmlTagKey
  else
    Result := stkHtmlTagKeyUndef;
end;

function TSynWebEngine.HtmlAttrFunc67: TSynWebTokenKind;
begin
  if  HtmlAttrKeyComp(21) or
      HtmlAttrKeyComp(75) or
      HtmlAttrKeyComp(76) then
    Result := stkHtmlTagKey
  else
    Result := stkHtmlTagKeyUndef;
end;

function TSynWebEngine.HtmlAttrFunc68: TSynWebTokenKind;
begin
  if  HtmlAttrKeyComp(59) or
      HtmlAttrKeyComp(122) then
    Result := stkHtmlTagKey
  else
    Result := stkHtmlTagKeyUndef;
end;

function TSynWebEngine.HtmlAttrFunc69: TSynWebTokenKind;
begin
  if  HtmlAttrKeyComp(114) then
    Result := stkHtmlTagKey
  else
    Result := stkHtmlTagKeyUndef;
end;

function TSynWebEngine.HtmlAttrFunc71: TSynWebTokenKind;
begin
  if  HtmlAttrKeyComp(29) or
      HtmlAttrKeyComp(42) or
      HtmlAttrKeyComp(52) or
      HtmlAttrKeyComp(113) then
    Result := stkHtmlTagKey
  else
    Result := stkHtmlTagKeyUndef;
end;

function TSynWebEngine.HtmlAttrFunc72: TSynWebTokenKind;
begin
  if  HtmlAttrKeyComp(11) then
    Result := stkHtmlTagKey
  else
    Result := stkHtmlTagKeyUndef;
end;

function TSynWebEngine.HtmlAttrFunc73: TSynWebTokenKind;
begin
  if  HtmlAttrKeyComp(103) then
    Result := stkHtmlTagKey
  else
    Result := stkHtmlTagKeyUndef;
end;

function TSynWebEngine.HtmlAttrFunc74: TSynWebTokenKind;
begin
  if  HtmlAttrKeyComp(17) or
      HtmlAttrKeyComp(31) then
    Result := stkHtmlTagKey
  else
    Result := stkHtmlTagKeyUndef;
end;

function TSynWebEngine.HtmlAttrFunc75: TSynWebTokenKind;
begin
  if  HtmlAttrKeyComp(97) or
      HtmlAttrKeyComp(99) or
      HtmlAttrKeyComp(117) then
    Result := stkHtmlTagKey
  else
    Result := stkHtmlTagKeyUndef;
end;

function TSynWebEngine.HtmlAttrFunc77: TSynWebTokenKind;
begin
  if  HtmlAttrKeyComp(37) or
      HtmlAttrKeyComp(125) then
    Result := stkHtmlTagKey
  else
    Result := stkHtmlTagKeyUndef;
end;

function TSynWebEngine.HtmlAttrFunc78: TSynWebTokenKind;
begin
  if  HtmlAttrKeyComp(109) then
    Result := stkHtmlTagKey
  else
    Result := stkHtmlTagKeyUndef;
end;

function TSynWebEngine.HtmlAttrFunc79: TSynWebTokenKind;
begin
  if  HtmlAttrKeyComp(61) or
      HtmlAttrKeyComp(112) then
    Result := stkHtmlTagKey
  else
    Result := stkHtmlTagKeyUndef;
end;

function TSynWebEngine.HtmlAttrFunc80: TSynWebTokenKind;
begin
  if  HtmlAttrKeyComp(28) then
    Result := stkHtmlTagKey
  else
    Result := stkHtmlTagKeyUndef;
end;

function TSynWebEngine.HtmlAttrFunc81: TSynWebTokenKind;
begin
  if  HtmlAttrKeyComp(92) or
      HtmlAttrKeyComp(110) then
    Result := stkHtmlTagKey
  else
    Result := stkHtmlTagKeyUndef;
end;

function TSynWebEngine.HtmlAttrFunc82: TSynWebTokenKind;
begin
  if  HtmlAttrKeyComp(74) or
      HtmlAttrKeyComp(127) then
    Result := stkHtmlTagKey
  else
    Result := stkHtmlTagKeyUndef;
end;

function TSynWebEngine.HtmlAttrFunc85: TSynWebTokenKind;
begin
  if  HtmlAttrKeyComp(77) or
      HtmlAttrKeyComp(108) then
    Result := stkHtmlTagKey
  else
    Result := stkHtmlTagKeyUndef;
end;

function TSynWebEngine.HtmlAttrFunc87: TSynWebTokenKind;
begin
  if  HtmlAttrKeyComp(13) or
      HtmlAttrKeyComp(72) or
      HtmlAttrKeyComp(126) then
    Result := stkHtmlTagKey
  else
    Result := stkHtmlTagKeyUndef;
end;

function TSynWebEngine.HtmlAttrFunc88: TSynWebTokenKind;
begin
  if  HtmlAttrKeyComp(43) then
    Result := stkHtmlTagKey
  else
    Result := stkHtmlTagKeyUndef;
end;

function TSynWebEngine.HtmlAttrFunc91: TSynWebTokenKind;
begin
  if  HtmlAttrKeyComp(3) or
      HtmlAttrKeyComp(30) then
    Result := stkHtmlTagKey
  else
    Result := stkHtmlTagKeyUndef;
end;

function TSynWebEngine.HtmlAttrFunc93: TSynWebTokenKind;
begin
  if  HtmlAttrKeyComp(25) or
      HtmlAttrKeyComp(78) or
      HtmlAttrKeyComp(89) then
    Result := stkHtmlTagKey
  else
    Result := stkHtmlTagKeyUndef;
end;

function TSynWebEngine.HtmlAttrFunc94: TSynWebTokenKind;
begin
  if  HtmlAttrKeyComp(94) then
    Result := stkHtmlTagKey
  else
    Result := stkHtmlTagKeyUndef;
end;

function TSynWebEngine.HtmlAttrFunc96: TSynWebTokenKind;
begin
  if  HtmlAttrKeyComp(10) or
      HtmlAttrKeyComp(88) or
      HtmlAttrKeyComp(91) then
    Result := stkHtmlTagKey
  else
    Result := stkHtmlTagKeyUndef;
end;

function TSynWebEngine.HtmlAttrFunc98: TSynWebTokenKind;
begin
  if  HtmlAttrKeyComp(93) then
    Result := stkHtmlTagKey
  else
    Result := stkHtmlTagKeyUndef;
end;

function TSynWebEngine.HtmlAttrFunc101: TSynWebTokenKind;
begin
  if  HtmlAttrKeyComp(14) then
    Result := stkHtmlTagKey
  else
    Result := stkHtmlTagKeyUndef;
end;

function TSynWebEngine.HtmlAttrFunc102: TSynWebTokenKind;
begin
  if  HtmlAttrKeyComp(121) then
    Result := stkHtmlTagKey
  else
    Result := stkHtmlTagKeyUndef;
end;

function TSynWebEngine.HtmlAttrFunc103: TSynWebTokenKind;
begin
  if  HtmlAttrKeyComp(2) then
    Result := stkHtmlTagKey
  else
    Result := stkHtmlTagKeyUndef;
end;

function TSynWebEngine.HtmlAttrFunc104: TSynWebTokenKind;
begin
  if  HtmlAttrKeyComp(64) then
    Result := stkHtmlTagKey
  else
    Result := stkHtmlTagKeyUndef;
end;

function TSynWebEngine.HtmlAttrFunc105: TSynWebTokenKind;
begin
  if  HtmlAttrKeyComp(48) then
    Result := stkHtmlTagKey
  else
    Result := stkHtmlTagKeyUndef;
end;

function TSynWebEngine.HtmlAttrFunc106: TSynWebTokenKind;
begin
  if  HtmlAttrKeyComp(98) then
    Result := stkHtmlTagKey
  else
    Result := stkHtmlTagKeyUndef;
end;

function TSynWebEngine.HtmlAttrFunc107: TSynWebTokenKind;
begin
  if  HtmlAttrKeyComp(81) then
    Result := stkHtmlTagKey
  else
    Result := stkHtmlTagKeyUndef;
end;

function TSynWebEngine.HtmlAttrFunc108: TSynWebTokenKind;
begin
  if  HtmlAttrKeyComp(67) then
    Result := stkHtmlTagKey
  else
    Result := stkHtmlTagKeyUndef;
end;

function TSynWebEngine.HtmlAttrFunc109: TSynWebTokenKind;
begin
  if  HtmlAttrKeyComp(102) then
    Result := stkHtmlTagKey
  else
    Result := stkHtmlTagKeyUndef;
end;

function TSynWebEngine.HtmlAttrFunc110: TSynWebTokenKind;
begin
  if  HtmlAttrKeyComp(111) then
    Result := stkHtmlTagKey
  else
    Result := stkHtmlTagKeyUndef;
end;

function TSynWebEngine.HtmlAttrFunc111: TSynWebTokenKind;
begin
  if  HtmlAttrKeyComp(70) then
    Result := stkHtmlTagKey
  else
    Result := stkHtmlTagKeyUndef;
end;

function TSynWebEngine.HtmlAttrFunc113: TSynWebTokenKind;
begin
  if  HtmlAttrKeyComp(90) then
    Result := stkHtmlTagKey
  else
    Result := stkHtmlTagKeyUndef;
end;

function TSynWebEngine.HtmlAttrFunc114: TSynWebTokenKind;
begin
  if  HtmlAttrKeyComp(35) then
    Result := stkHtmlTagKey
  else
    Result := stkHtmlTagKeyUndef;
end;

function TSynWebEngine.HtmlAttrFunc119: TSynWebTokenKind;
begin
  if  HtmlAttrKeyComp(34) or
      HtmlAttrKeyComp(54) or
      HtmlAttrKeyComp(62) then
    Result := stkHtmlTagKey
  else
    Result := stkHtmlTagKeyUndef;
end;

function TSynWebEngine.HtmlAttrFunc126: TSynWebTokenKind;
begin
  if  HtmlAttrKeyComp(63) or
      HtmlAttrKeyComp(79) then
    Result := stkHtmlTagKey
  else
    Result := stkHtmlTagKeyUndef;
end;

function TSynWebEngine.HtmlAttrFunc127: TSynWebTokenKind;
begin
  if  HtmlAttrKeyComp(120) then
    Result := stkHtmlTagKey
  else
    Result := stkHtmlTagKeyUndef;
end;

function TSynWebEngine.HtmlAttrFunc139: TSynWebTokenKind;
begin
  if  HtmlAttrKeyComp(87) then
    Result := stkHtmlTagKey
  else
    Result := stkHtmlTagKeyUndef;
end;

function TSynWebEngine.HtmlAttrFunc147: TSynWebTokenKind;
begin
  if  HtmlAttrKeyComp(80) then
    Result := stkHtmlTagKey
  else
    Result := stkHtmlTagKeyUndef;
end;

function TSynWebEngine.HtmlAttrFunc157: TSynWebTokenKind;
begin
  if  HtmlAttrKeyComp(84) then
    Result := stkHtmlTagKey
  else
    Result := stkHtmlTagKeyUndef;
end;

function TSynWebEngine.HtmlAttrFunc158: TSynWebTokenKind;
begin
  if  HtmlAttrKeyComp(83) or
      HtmlAttrKeyComp(85) then
    Result := stkHtmlTagKey
  else
    Result := stkHtmlTagKeyUndef;
end;

function TSynWebEngine.HtmlAttrFunc162: TSynWebTokenKind;
begin
  if  HtmlAttrKeyComp(86) then
    Result := stkHtmlTagKey
  else
    Result := stkHtmlTagKeyUndef;
end;
