function TSynWebEngine.CssValUndef: TSynWebTokenKind;
begin
  Result:=stkCssValUndef;
end;

function TSynWebEngine.CssValFunc17: TSynWebTokenKind;
begin
  if  CssValKeyComp(36) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc21: TSynWebTokenKind;
begin
  if  CssValKeyComp(41) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc22: TSynWebTokenKind;
begin
  if  CssValKeyComp(80) or
      CssValKeyComp(683) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc23: TSynWebTokenKind;
begin
  if  CssValKeyComp(199) or
      CssValKeyComp(670) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc25: TSynWebTokenKind;
begin
  if  CssValKeyComp(11) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc26: TSynWebTokenKind;
begin
  if  CssValKeyComp(6) or
      CssValKeyComp(278) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc27: TSynWebTokenKind;
begin
  if  CssValKeyComp(111) or
      CssValKeyComp(483) or
      CssValKeyComp(558) or
      CssValKeyComp(566) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc28: TSynWebTokenKind;
begin
  if  CssValKeyComp(46) or
      CssValKeyComp(339) or
      CssValKeyComp(567) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc29: TSynWebTokenKind;
begin
  if  CssValKeyComp(52) or
      CssValKeyComp(198) or
      CssValKeyComp(490) or
      CssValKeyComp(515) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc30: TSynWebTokenKind;
begin
  if  CssValKeyComp(96) or
      CssValKeyComp(164) or
      CssValKeyComp(194) or
      CssValKeyComp(397) or
      CssValKeyComp(572) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc31: TSynWebTokenKind;
begin
  if  CssValKeyComp(0) or
      CssValKeyComp(401) or
      CssValKeyComp(484) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc32: TSynWebTokenKind;
begin
  if  CssValKeyComp(1) or
      CssValKeyComp(88) or
      CssValKeyComp(279) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc33: TSynWebTokenKind;
begin
  if  CssValKeyComp(2) or
      CssValKeyComp(34) or
      CssValKeyComp(60) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc34: TSynWebTokenKind;
begin
  if  CssValKeyComp(35) or
      CssValKeyComp(304) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc35: TSynWebTokenKind;
begin
  if  CssValKeyComp(178) or
      CssValKeyComp(682) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc36: TSynWebTokenKind;
begin
  if  CssValKeyComp(99) or
      CssValKeyComp(231) or
      CssValKeyComp(243) or
      CssValKeyComp(276) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc37: TSynWebTokenKind;
begin
  if  CssValKeyComp(352) or
      CssValKeyComp(491) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc38: TSynWebTokenKind;
begin
  if  CssValKeyComp(40) or
      CssValKeyComp(259) or
      CssValKeyComp(265) or
      CssValKeyComp(597) or
      CssValKeyComp(684) or
      CssValKeyComp(694) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc39: TSynWebTokenKind;
begin
  if  CssValKeyComp(187) or
      CssValKeyComp(232) or
      CssValKeyComp(238) or
      CssValKeyComp(373) or
      CssValKeyComp(540) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc40: TSynWebTokenKind;
begin
  if  CssValKeyComp(23) or
      CssValKeyComp(58) or
      CssValKeyComp(336) or
      CssValKeyComp(600) or
      CssValKeyComp(671) or
      CssValKeyComp(748) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc41: TSynWebTokenKind;
begin
  if  CssValKeyComp(76) or
      CssValKeyComp(163) or
      CssValKeyComp(201) or
      CssValKeyComp(275) or
      CssValKeyComp(292) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc42: TSynWebTokenKind;
begin
  if  CssValKeyComp(9) or
      CssValKeyComp(45) or
      CssValKeyComp(230) or
      CssValKeyComp(455) or
      CssValKeyComp(663) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc43: TSynWebTokenKind;
begin
  if  CssValKeyComp(55) or
      CssValKeyComp(143) or
      CssValKeyComp(340) or
      CssValKeyComp(349) or
      CssValKeyComp(384) or
      CssValKeyComp(429) or
      CssValKeyComp(568) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc44: TSynWebTokenKind;
begin
  if  CssValKeyComp(277) or
      CssValKeyComp(645) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc45: TSynWebTokenKind;
begin
  if  CssValKeyComp(3) or
      CssValKeyComp(74) or
      CssValKeyComp(444) or
      CssValKeyComp(556) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc46: TSynWebTokenKind;
begin
  if  CssValKeyComp(228) or
      CssValKeyComp(329) or
      CssValKeyComp(442) or
      CssValKeyComp(557) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc47: TSynWebTokenKind;
begin
  if  CssValKeyComp(165) or
      CssValKeyComp(434) or
      CssValKeyComp(617) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc48: TSynWebTokenKind;
begin
  if  CssValKeyComp(54) or
      CssValKeyComp(173) or
      CssValKeyComp(233) or
      CssValKeyComp(237) or
      CssValKeyComp(469) or
      CssValKeyComp(633) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc49: TSynWebTokenKind;
begin
  if  CssValKeyComp(108) or
      CssValKeyComp(130) or
      CssValKeyComp(262) or
      CssValKeyComp(634) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc50: TSynWebTokenKind;
begin
  if  CssValKeyComp(7) or
      CssValKeyComp(48) or
      CssValKeyComp(101) or
      CssValKeyComp(387) or
      CssValKeyComp(398) or
      CssValKeyComp(493) or
      CssValKeyComp(533) or
      CssValKeyComp(587) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc51: TSynWebTokenKind;
begin
  if  CssValKeyComp(30) or
      CssValKeyComp(43) or
      CssValKeyComp(261) or
      CssValKeyComp(348) or
      CssValKeyComp(482) or
      CssValKeyComp(695) or
      CssValKeyComp(696) or
      CssValKeyComp(707) or
      CssValKeyComp(735) or
      CssValKeyComp(747) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc52: TSynWebTokenKind;
begin
  if  CssValKeyComp(137) or
      CssValKeyComp(343) or
      CssValKeyComp(386) or
      CssValKeyComp(485) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc53: TSynWebTokenKind;
begin
  if  CssValKeyComp(19) or
      CssValKeyComp(330) or
      CssValKeyComp(430) or
      CssValKeyComp(746) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc54: TSynWebTokenKind;
begin
  if  CssValKeyComp(320) or
      CssValKeyComp(378) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc55: TSynWebTokenKind;
begin
  if  CssValKeyComp(264) or
      CssValKeyComp(280) or
      CssValKeyComp(337) or
      CssValKeyComp(448) or
      CssValKeyComp(681) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc56: TSynWebTokenKind;
begin
  if  CssValKeyComp(61) or
      CssValKeyComp(356) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc57: TSynWebTokenKind;
begin
  if  CssValKeyComp(29) or
      CssValKeyComp(47) or
      CssValKeyComp(274) or
      CssValKeyComp(498) or
      CssValKeyComp(614) or
      CssValKeyComp(637) or
      CssValKeyComp(750) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc58: TSynWebTokenKind;
begin
  if  CssValKeyComp(109) or
      CssValKeyComp(179) or
      CssValKeyComp(299) or
      CssValKeyComp(625) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc59: TSynWebTokenKind;
begin
  if  CssValKeyComp(28) or
      CssValKeyComp(129) or
      CssValKeyComp(190) or
      CssValKeyComp(281) or
      CssValKeyComp(375) or
      CssValKeyComp(643) or
      CssValKeyComp(699) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc60: TSynWebTokenKind;
begin
  if  CssValKeyComp(174) or
      CssValKeyComp(270) or
      CssValKeyComp(314) or
      CssValKeyComp(331) or
      CssValKeyComp(496) or
      CssValKeyComp(531) or
      CssValKeyComp(559) or
      CssValKeyComp(642) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc61: TSynWebTokenKind;
begin
  if  CssValKeyComp(155) or
      CssValKeyComp(273) or
      CssValKeyComp(342) or
      CssValKeyComp(347) or
      CssValKeyComp(399) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc62: TSynWebTokenKind;
begin
  if  CssValKeyComp(84) or
      CssValKeyComp(402) or
      CssValKeyComp(451) or
      CssValKeyComp(535) or
      CssValKeyComp(569) or
      CssValKeyComp(615) or
      CssValKeyComp(618) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc63: TSynWebTokenKind;
begin
  if  CssValKeyComp(113) or
      CssValKeyComp(135) or
      CssValKeyComp(271) or
      CssValKeyComp(305) or
      CssValKeyComp(456) or
      CssValKeyComp(487) or
      CssValKeyComp(646) or
      CssValKeyComp(648) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc64: TSynWebTokenKind;
begin
  if  CssValKeyComp(602) or
      CssValKeyComp(734) or
      CssValKeyComp(753) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc65: TSynWebTokenKind;
begin
  if  CssValKeyComp(89) or
      CssValKeyComp(419) or
      CssValKeyComp(561) or
      CssValKeyComp(603) or
      CssValKeyComp(616) or
      CssValKeyComp(751) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc66: TSynWebTokenKind;
begin
  if  CssValKeyComp(385) or
      CssValKeyComp(526) or
      CssValKeyComp(588) or
      CssValKeyComp(604) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc67: TSynWebTokenKind;
begin
  if  CssValKeyComp(42) or
      CssValKeyComp(253) or
      CssValKeyComp(312) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc68: TSynWebTokenKind;
begin
  if  CssValKeyComp(175) or
      CssValKeyComp(188) or
      CssValKeyComp(500) or
      CssValKeyComp(520) or
      CssValKeyComp(573) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc69: TSynWebTokenKind;
begin
  if  CssValKeyComp(50) or
      CssValKeyComp(169) or
      CssValKeyComp(229) or
      CssValKeyComp(528) or
      CssValKeyComp(635) or
      CssValKeyComp(644) or
      CssValKeyComp(686) or
      CssValKeyComp(774) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc70: TSynWebTokenKind;
begin
  if  CssValKeyComp(10) or
      CssValKeyComp(667) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc71: TSynWebTokenKind;
begin
  if  CssValKeyComp(33) or
      CssValKeyComp(97) or
      CssValKeyComp(119) or
      CssValKeyComp(302) or
      CssValKeyComp(641) or
      CssValKeyComp(698) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc72: TSynWebTokenKind;
begin
  if  CssValKeyComp(79) or
      CssValKeyComp(236) or
      CssValKeyComp(583) or
      CssValKeyComp(654) or
      CssValKeyComp(723) or
      CssValKeyComp(749) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc73: TSynWebTokenKind;
begin
  if  CssValKeyComp(51) or
      CssValKeyComp(83) or
      CssValKeyComp(92) or
      CssValKeyComp(222) or
      CssValKeyComp(249) or
      CssValKeyComp(252) or
      CssValKeyComp(388) or
      CssValKeyComp(473) or
      CssValKeyComp(499) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc74: TSynWebTokenKind;
begin
  if  CssValKeyComp(138) or
      CssValKeyComp(144) or
      CssValKeyComp(150) or
      CssValKeyComp(303) or
      CssValKeyComp(431) or
      CssValKeyComp(438) or
      CssValKeyComp(457) or
      CssValKeyComp(480) or
      CssValKeyComp(522) or
      CssValKeyComp(596) or
      CssValKeyComp(601) or
      CssValKeyComp(607) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc75: TSynWebTokenKind;
begin
  if  CssValKeyComp(26) or
      CssValKeyComp(338) or
      CssValKeyComp(585) or
      CssValKeyComp(669) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc76: TSynWebTokenKind;
begin
  if  CssValKeyComp(122) or
      CssValKeyComp(257) or
      CssValKeyComp(291) or
      CssValKeyComp(407) or
      CssValKeyComp(502) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc77: TSynWebTokenKind;
begin
  if  CssValKeyComp(16) or
      CssValKeyComp(145) or
      CssValKeyComp(176) or
      CssValKeyComp(200) or
      CssValKeyComp(443) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc78: TSynWebTokenKind;
begin
  if  CssValKeyComp(87) or
      CssValKeyComp(115) or
      CssValKeyComp(298) or
      CssValKeyComp(653) or
      CssValKeyComp(745) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc79: TSynWebTokenKind;
begin
  if  CssValKeyComp(360) or
      CssValKeyComp(400) or
      CssValKeyComp(575) or
      CssValKeyComp(605) or
      CssValKeyComp(620) or
      CssValKeyComp(665) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc80: TSynWebTokenKind;
begin
  if  CssValKeyComp(167) or
      CssValKeyComp(354) or
      CssValKeyComp(408) or
      CssValKeyComp(640) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc81: TSynWebTokenKind;
begin
  if  CssValKeyComp(18) or
      CssValKeyComp(177) or
      CssValKeyComp(235) or
      CssValKeyComp(319) or
      CssValKeyComp(344) or
      CssValKeyComp(445) or
      CssValKeyComp(481) or
      CssValKeyComp(608) or
      CssValKeyComp(650) or
      CssValKeyComp(660) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc82: TSynWebTokenKind;
begin
  if  CssValKeyComp(100) or
      CssValKeyComp(171) or
      CssValKeyComp(267) or
      CssValKeyComp(527) or
      CssValKeyComp(529) or
      CssValKeyComp(626) or
      CssValKeyComp(772) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc83: TSynWebTokenKind;
begin
  if  CssValKeyComp(112) or
      CssValKeyComp(120) or
      CssValKeyComp(148) or
      CssValKeyComp(301) or
      CssValKeyComp(517) or
      CssValKeyComp(627) or
      CssValKeyComp(743) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc84: TSynWebTokenKind;
begin
  if  CssValKeyComp(705) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc85: TSynWebTokenKind;
begin
  if  CssValKeyComp(75) or
      CssValKeyComp(147) or
      CssValKeyComp(203) or
      CssValKeyComp(250) or
      CssValKeyComp(413) or
      CssValKeyComp(449) or
      CssValKeyComp(612) or
      CssValKeyComp(621) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc86: TSynWebTokenKind;
begin
  if  CssValKeyComp(225) or
      CssValKeyComp(300) or
      CssValKeyComp(685) or
      CssValKeyComp(717) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc87: TSynWebTokenKind;
begin
  if  CssValKeyComp(268) or
      CssValKeyComp(475) or
      CssValKeyComp(497) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc88: TSynWebTokenKind;
begin
  if  CssValKeyComp(239) or
      CssValKeyComp(318) or
      CssValKeyComp(374) or
      CssValKeyComp(488) or
      CssValKeyComp(551) or
      CssValKeyComp(754) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc89: TSynWebTokenKind;
begin
  if  CssValKeyComp(149) or
      CssValKeyComp(321) or
      CssValKeyComp(492) or
      CssValKeyComp(658) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc90: TSynWebTokenKind;
begin
  if  CssValKeyComp(170) or
      CssValKeyComp(737) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc91: TSynWebTokenKind;
begin
  if  CssValKeyComp(123) or
      CssValKeyComp(136) or
      CssValKeyComp(154) or
      CssValKeyComp(195) or
      CssValKeyComp(454) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc92: TSynWebTokenKind;
begin
  if  CssValKeyComp(82) or
      CssValKeyComp(560) or
      CssValKeyComp(565) or
      CssValKeyComp(636) or
      CssValKeyComp(770) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc93: TSynWebTokenKind;
begin
  if  CssValKeyComp(186) or
      CssValKeyComp(289) or
      CssValKeyComp(508) or
      CssValKeyComp(657) or
      CssValKeyComp(659) or
      CssValKeyComp(697) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc94: TSynWebTokenKind;
begin
  if  CssValKeyComp(153) or
      CssValKeyComp(260) or
      CssValKeyComp(759) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc95: TSynWebTokenKind;
begin
  if  CssValKeyComp(4) or
      CssValKeyComp(151) or
      CssValKeyComp(184) or
      CssValKeyComp(193) or
      CssValKeyComp(294) or
      CssValKeyComp(628) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc96: TSynWebTokenKind;
begin
  if  CssValKeyComp(17) or
      CssValKeyComp(133) or
      CssValKeyComp(324) or
      CssValKeyComp(357) or
      CssValKeyComp(439) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc97: TSynWebTokenKind;
begin
  if  CssValKeyComp(116) or
      CssValKeyComp(142) or
      CssValKeyComp(536) or
      CssValKeyComp(594) or
      CssValKeyComp(630) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc98: TSynWebTokenKind;
begin
  if  CssValKeyComp(334) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc99: TSynWebTokenKind;
begin
  if  CssValKeyComp(141) or
      CssValKeyComp(286) or
      CssValKeyComp(346) or
      CssValKeyComp(359) or
      CssValKeyComp(376) or
      CssValKeyComp(733) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc100: TSynWebTokenKind;
begin
  if  CssValKeyComp(24) or
      CssValKeyComp(77) or
      CssValKeyComp(256) or
      CssValKeyComp(333) or
      CssValKeyComp(446) or
      CssValKeyComp(501) or
      CssValKeyComp(507) or
      CssValKeyComp(509) or
      CssValKeyComp(606) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc101: TSynWebTokenKind;
begin
  if  CssValKeyComp(132) or
      CssValKeyComp(297) or
      CssValKeyComp(327) or
      CssValKeyComp(391) or
      CssValKeyComp(447) or
      CssValKeyComp(656) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc102: TSynWebTokenKind;
begin
  if  CssValKeyComp(85) or
      CssValKeyComp(624) or
      CssValKeyComp(722) or
      CssValKeyComp(767) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc103: TSynWebTokenKind;
begin
  if  CssValKeyComp(326) or
      CssValKeyComp(580) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc104: TSynWebTokenKind;
begin
  if  CssValKeyComp(581) or
      CssValKeyComp(727) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc105: TSynWebTokenKind;
begin
  if  CssValKeyComp(358) or
      CssValKeyComp(363) or
      CssValKeyComp(421) or
      CssValKeyComp(459) or
      CssValKeyComp(582) or
      CssValKeyComp(760) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc106: TSynWebTokenKind;
begin
  if  CssValKeyComp(226) or
      CssValKeyComp(365) or
      CssValKeyComp(412) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc107: TSynWebTokenKind;
begin
  if  CssValKeyComp(325) or
      CssValKeyComp(362) or
      CssValKeyComp(706) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc108: TSynWebTokenKind;
begin
  if  CssValKeyComp(53) or
      CssValKeyComp(156) or
      CssValKeyComp(157) or
      CssValKeyComp(246) or
      CssValKeyComp(269) or
      CssValKeyComp(341) or
      CssValKeyComp(351) or
      CssValKeyComp(542) or
      CssValKeyComp(631) or
      CssValKeyComp(758) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc109: TSynWebTokenKind;
begin
  if  CssValKeyComp(8) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc110: TSynWebTokenKind;
begin
  if  CssValKeyComp(44) or
      CssValKeyComp(125) or
      CssValKeyComp(139) or
      CssValKeyComp(244) or
      CssValKeyComp(328) or
      CssValKeyComp(673) or
      CssValKeyComp(711) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc111: TSynWebTokenKind;
begin
  if  CssValKeyComp(25) or
      CssValKeyComp(364) or
      CssValKeyComp(586) or
      CssValKeyComp(756) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc112: TSynWebTokenKind;
begin
  if  CssValKeyComp(632) or
      CssValKeyComp(762) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc113: TSynWebTokenKind;
begin
  if  CssValKeyComp(576) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc114: TSynWebTokenKind;
begin
  if  CssValKeyComp(593) or
      CssValKeyComp(619) or
      CssValKeyComp(761) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc115: TSynWebTokenKind;
begin
  if  CssValKeyComp(134) or
      CssValKeyComp(254) or
      CssValKeyComp(525) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc116: TSynWebTokenKind;
begin
  if  CssValKeyComp(521) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc117: TSynWebTokenKind;
begin
  if  CssValKeyComp(162) or
      CssValKeyComp(538) or
      CssValKeyComp(541) or
      CssValKeyComp(546) or
      CssValKeyComp(595) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc118: TSynWebTokenKind;
begin
  if  CssValKeyComp(32) or
      CssValKeyComp(95) or
      CssValKeyComp(290) or
      CssValKeyComp(350) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc119: TSynWebTokenKind;
begin
  if  CssValKeyComp(414) or
      CssValKeyComp(764) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc120: TSynWebTokenKind;
begin
  if  CssValKeyComp(20) or
      CssValKeyComp(353) or
      CssValKeyComp(465) or
      CssValKeyComp(773) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc121: TSynWebTokenKind;
begin
  if  CssValKeyComp(27) or
      CssValKeyComp(534) or
      CssValKeyComp(539) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc122: TSynWebTokenKind;
begin
  if  CssValKeyComp(422) or
      CssValKeyComp(765) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc123: TSynWebTokenKind;
begin
  if  CssValKeyComp(21) or
      CssValKeyComp(59) or
      CssValKeyComp(710) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc124: TSynWebTokenKind;
begin
  if  CssValKeyComp(12) or
      CssValKeyComp(197) or
      CssValKeyComp(435) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc125: TSynWebTokenKind;
begin
  if  CssValKeyComp(168) or
      CssValKeyComp(202) or
      CssValKeyComp(227) or
      CssValKeyComp(251) or
      CssValKeyComp(661) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc127: TSynWebTokenKind;
begin
  if  CssValKeyComp(117) or
      CssValKeyComp(181) or
      CssValKeyComp(562) or
      CssValKeyComp(571) or
      CssValKeyComp(664) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc128: TSynWebTokenKind;
begin
  if  CssValKeyComp(146) or
      CssValKeyComp(450) or
      CssValKeyComp(516) or
      CssValKeyComp(563) or
      CssValKeyComp(752) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc129: TSynWebTokenKind;
begin
  if  CssValKeyComp(240) or
      CssValKeyComp(245) or
      CssValKeyComp(768) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc130: TSynWebTokenKind;
begin
  if  CssValKeyComp(366) or
      CssValKeyComp(367) or
      CssValKeyComp(468) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc131: TSynWebTokenKind;
begin
  if  CssValKeyComp(158) or
      CssValKeyComp(285) or
      CssValKeyComp(437) or
      CssValKeyComp(589) or
      CssValKeyComp(763) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc132: TSynWebTokenKind;
begin
  if  CssValKeyComp(248) or
      CssValKeyComp(472) or
      CssValKeyComp(649) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc133: TSynWebTokenKind;
begin
  if  CssValKeyComp(266) or
      CssValKeyComp(416) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc134: TSynWebTokenKind;
begin
  if  CssValKeyComp(86) or
      CssValKeyComp(258) or
      CssValKeyComp(476) or
      CssValKeyComp(511) or
      CssValKeyComp(638) or
      CssValKeyComp(678) or
      CssValKeyComp(713) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc135: TSynWebTokenKind;
begin
  if  CssValKeyComp(78) or
      CssValKeyComp(81) or
      CssValKeyComp(127) or
      CssValKeyComp(377) or
      CssValKeyComp(417) or
      CssValKeyComp(545) or
      CssValKeyComp(598) or
      CssValKeyComp(714) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc136: TSynWebTokenKind;
begin
  if  CssValKeyComp(512) or
      CssValKeyComp(662) or
      CssValKeyComp(715) or
      CssValKeyComp(744) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc137: TSynWebTokenKind;
begin
  if  CssValKeyComp(570) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc138: TSynWebTokenKind;
begin
  if  CssValKeyComp(287) or
      CssValKeyComp(432) or
      CssValKeyComp(440) or
      CssValKeyComp(530) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc139: TSynWebTokenKind;
begin
  if  CssValKeyComp(102) or
      CssValKeyComp(308) or
      CssValKeyComp(424) or
      CssValKeyComp(452) or
      CssValKeyComp(651) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc140: TSynWebTokenKind;
begin
  if  CssValKeyComp(418) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc141: TSynWebTokenKind;
begin
  if  CssValKeyComp(64) or
      CssValKeyComp(140) or
      CssValKeyComp(263) or
      CssValKeyComp(311) or
      CssValKeyComp(771) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc142: TSynWebTokenKind;
begin
  if  CssValKeyComp(14) or
      CssValKeyComp(159) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc143: TSynWebTokenKind;
begin
  if  CssValKeyComp(345) or
      CssValKeyComp(404) or
      CssValKeyComp(441) or
      CssValKeyComp(757) or
      CssValKeyComp(769) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc144: TSynWebTokenKind;
begin
  if  CssValKeyComp(306) or
      CssValKeyComp(514) or
      CssValKeyComp(519) or
      CssValKeyComp(613) or
      CssValKeyComp(712) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc145: TSynWebTokenKind;
begin
  if  CssValKeyComp(381) or
      CssValKeyComp(719) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc146: TSynWebTokenKind;
begin
  if  CssValKeyComp(90) or
      CssValKeyComp(152) or
      CssValKeyComp(160) or
      CssValKeyComp(716) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc147: TSynWebTokenKind;
begin
  if  CssValKeyComp(191) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc148: TSynWebTokenKind;
begin
  if  CssValKeyComp(220) or
      CssValKeyComp(282) or
      CssValKeyComp(372) or
      CssValKeyComp(433) or
      CssValKeyComp(599) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc149: TSynWebTokenKind;
begin
  if  CssValKeyComp(332) or
      CssValKeyComp(389) or
      CssValKeyComp(574) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc150: TSynWebTokenKind;
begin
  if  CssValKeyComp(114) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc151: TSynWebTokenKind;
begin
  if  CssValKeyComp(128) or
      CssValKeyComp(313) or
      CssValKeyComp(368) or
      CssValKeyComp(382) or
      CssValKeyComp(406) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc152: TSynWebTokenKind;
begin
  if  CssValKeyComp(22) or
      CssValKeyComp(204) or
      CssValKeyComp(241) or
      CssValKeyComp(532) or
      CssValKeyComp(725) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc153: TSynWebTokenKind;
begin
  if  CssValKeyComp(189) or
      CssValKeyComp(255) or
      CssValKeyComp(423) or
      CssValKeyComp(464) or
      CssValKeyComp(477) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc154: TSynWebTokenKind;
begin
  if  CssValKeyComp(335) or
      CssValKeyComp(550) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc155: TSynWebTokenKind;
begin
  if  CssValKeyComp(513) or
      CssValKeyComp(766) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc156: TSynWebTokenKind;
begin
  if  CssValKeyComp(672) or
      CssValKeyComp(674) or
      CssValKeyComp(724) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc157: TSynWebTokenKind;
begin
  if  CssValKeyComp(107) or
      CssValKeyComp(371) or
      CssValKeyComp(392) or
      CssValKeyComp(411) or
      CssValKeyComp(478) or
      CssValKeyComp(611) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc158: TSynWebTokenKind;
begin
  if  CssValKeyComp(49) or
      CssValKeyComp(410) or
      CssValKeyComp(462) or
      CssValKeyComp(647) or
      CssValKeyComp(693) or
      CssValKeyComp(718) or
      CssValKeyComp(739) or
      CssValKeyComp(741) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc159: TSynWebTokenKind;
begin
  if  CssValKeyComp(293) or
      CssValKeyComp(474) or
      CssValKeyComp(655) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc160: TSynWebTokenKind;
begin
  if  CssValKeyComp(577) or
      CssValKeyComp(728) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc161: TSynWebTokenKind;
begin
  if  CssValKeyComp(409) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc162: TSynWebTokenKind;
begin
  if  CssValKeyComp(405) or
      CssValKeyComp(425) or
      CssValKeyComp(554) or
      CssValKeyComp(668) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc163: TSynWebTokenKind;
begin
  if  CssValKeyComp(65) or
      CssValKeyComp(247) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc164: TSynWebTokenKind;
begin
  if  CssValKeyComp(73) or
      CssValKeyComp(317) or
      CssValKeyComp(369) or
      CssValKeyComp(564) or
      CssValKeyComp(666) or
      CssValKeyComp(700) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc165: TSynWebTokenKind;
begin
  if  CssValKeyComp(91) or
      CssValKeyComp(242) or
      CssValKeyComp(420) or
      CssValKeyComp(436) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc166: TSynWebTokenKind;
begin
  if  CssValKeyComp(494) or
      CssValKeyComp(692) or
      CssValKeyComp(702) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc167: TSynWebTokenKind;
begin
  if  CssValKeyComp(31) or
      CssValKeyComp(394) or
      CssValKeyComp(415) or
      CssValKeyComp(610) or
      CssValKeyComp(755) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc168: TSynWebTokenKind;
begin
  if  CssValKeyComp(370) or
      CssValKeyComp(704) or
      CssValKeyComp(736) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc169: TSynWebTokenKind;
begin
  if  CssValKeyComp(38) or
      CssValKeyComp(70) or
      CssValKeyComp(131) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc170: TSynWebTokenKind;
begin
  if  CssValKeyComp(110) or
      CssValKeyComp(124) or
      CssValKeyComp(380) or
      CssValKeyComp(629) or
      CssValKeyComp(730) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc171: TSynWebTokenKind;
begin
  if  CssValKeyComp(738) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc172: TSynWebTokenKind;
begin
  if  CssValKeyComp(296) or
      CssValKeyComp(396) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc173: TSynWebTokenKind;
begin
  if  CssValKeyComp(57) or
      CssValKeyComp(591) or
      CssValKeyComp(639) or
      CssValKeyComp(690) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc174: TSynWebTokenKind;
begin
  if  CssValKeyComp(322) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc175: TSynWebTokenKind;
begin
  if  CssValKeyComp(379) or
      CssValKeyComp(428) or
      CssValKeyComp(732) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc176: TSynWebTokenKind;
begin
  if  CssValKeyComp(584) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc177: TSynWebTokenKind;
begin
  if  CssValKeyComp(467) or
      CssValKeyComp(553) or
      CssValKeyComp(609) or
      CssValKeyComp(691) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc178: TSynWebTokenKind;
begin
  if  CssValKeyComp(221) or
      CssValKeyComp(510) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc179: TSynWebTokenKind;
begin
  if  CssValKeyComp(161) or
      CssValKeyComp(224) or
      CssValKeyComp(518) or
      CssValKeyComp(579) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc180: TSynWebTokenKind;
begin
  if  CssValKeyComp(93) or
      CssValKeyComp(543) or
      CssValKeyComp(680) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc181: TSynWebTokenKind;
begin
  if  CssValKeyComp(453) or
      CssValKeyComp(479) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc182: TSynWebTokenKind;
begin
  if  CssValKeyComp(505) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc183: TSynWebTokenKind;
begin
  if  CssValKeyComp(721) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc184: TSynWebTokenKind;
begin
  if  CssValKeyComp(185) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc185: TSynWebTokenKind;
begin
  if  CssValKeyComp(196) or
      CssValKeyComp(403) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc186: TSynWebTokenKind;
begin
  if  CssValKeyComp(98) or
      CssValKeyComp(390) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc187: TSynWebTokenKind;
begin
  if  CssValKeyComp(316) or
      CssValKeyComp(355) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc189: TSynWebTokenKind;
begin
  if  CssValKeyComp(223) or
      CssValKeyComp(307) or
      CssValKeyComp(726) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc190: TSynWebTokenKind;
begin
  if  CssValKeyComp(578) or
      CssValKeyComp(740) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc192: TSynWebTokenKind;
begin
  if  CssValKeyComp(126) or
      CssValKeyComp(689) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc193: TSynWebTokenKind;
begin
  if  CssValKeyComp(310) or
      CssValKeyComp(720) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc194: TSynWebTokenKind;
begin
  if  CssValKeyComp(552) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc196: TSynWebTokenKind;
begin
  if  CssValKeyComp(393) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc197: TSynWebTokenKind;
begin
  if  CssValKeyComp(15) or
      CssValKeyComp(37) or
      CssValKeyComp(323) or
      CssValKeyComp(426) or
      CssValKeyComp(503) or
      CssValKeyComp(742) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc198: TSynWebTokenKind;
begin
  if  CssValKeyComp(288) or
      CssValKeyComp(506) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc199: TSynWebTokenKind;
begin
  if  CssValKeyComp(729) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc200: TSynWebTokenKind;
begin
  if  CssValKeyComp(94) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc202: TSynWebTokenKind;
begin
  if  CssValKeyComp(315) or
      CssValKeyComp(463) or
      CssValKeyComp(544) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc204: TSynWebTokenKind;
begin
  if  CssValKeyComp(180) or
      CssValKeyComp(295) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc205: TSynWebTokenKind;
begin
  if  CssValKeyComp(504) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc206: TSynWebTokenKind;
begin
  if  CssValKeyComp(121) or
      CssValKeyComp(172) or
      CssValKeyComp(219) or
      CssValKeyComp(652) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc209: TSynWebTokenKind;
begin
  if  CssValKeyComp(183) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc210: TSynWebTokenKind;
begin
  if  CssValKeyComp(427) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc213: TSynWebTokenKind;
begin
  if  CssValKeyComp(537) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc215: TSynWebTokenKind;
begin
  if  CssValKeyComp(13) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc216: TSynWebTokenKind;
begin
  if  CssValKeyComp(56) or
      CssValKeyComp(272) or
      CssValKeyComp(687) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc217: TSynWebTokenKind;
begin
  if  CssValKeyComp(395) or
      CssValKeyComp(486) or
      CssValKeyComp(688) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc220: TSynWebTokenKind;
begin
  if  CssValKeyComp(489) or
      CssValKeyComp(731) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc221: TSynWebTokenKind;
begin
  if  CssValKeyComp(471) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc223: TSynWebTokenKind;
begin
  if  CssValKeyComp(118) or
      CssValKeyComp(283) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc225: TSynWebTokenKind;
begin
  if  CssValKeyComp(234) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc228: TSynWebTokenKind;
begin
  if  CssValKeyComp(206) or
      CssValKeyComp(523) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc231: TSynWebTokenKind;
begin
  if  CssValKeyComp(701) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc233: TSynWebTokenKind;
begin
  if  CssValKeyComp(470) or
      CssValKeyComp(703) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc234: TSynWebTokenKind;
begin
  if  CssValKeyComp(677) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc235: TSynWebTokenKind;
begin
  if  CssValKeyComp(105) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc236: TSynWebTokenKind;
begin
  if  CssValKeyComp(192) or
      CssValKeyComp(309) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc237: TSynWebTokenKind;
begin
  if  CssValKeyComp(460) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc239: TSynWebTokenKind;
begin
  if  CssValKeyComp(5) or
      CssValKeyComp(166) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc242: TSynWebTokenKind;
begin
  if  CssValKeyComp(361) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc244: TSynWebTokenKind;
begin
  if  CssValKeyComp(66) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc245: TSynWebTokenKind;
begin
  if  CssValKeyComp(67) or
      CssValKeyComp(182) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc246: TSynWebTokenKind;
begin
  if  CssValKeyComp(549) or
      CssValKeyComp(590) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc247: TSynWebTokenKind;
begin
  if  CssValKeyComp(708) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc249: TSynWebTokenKind;
begin
  if  CssValKeyComp(106) or
      CssValKeyComp(679) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc250: TSynWebTokenKind;
begin
  if  CssValKeyComp(218) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc251: TSynWebTokenKind;
begin
  if  CssValKeyComp(39) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc252: TSynWebTokenKind;
begin
  if  CssValKeyComp(71) or
      CssValKeyComp(212) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc253: TSynWebTokenKind;
begin
  if  CssValKeyComp(72) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc259: TSynWebTokenKind;
begin
  if  CssValKeyComp(103) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc261: TSynWebTokenKind;
begin
  if  CssValKeyComp(495) or
      CssValKeyComp(622) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc262: TSynWebTokenKind;
begin
  if  CssValKeyComp(104) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc263: TSynWebTokenKind;
begin
  if  CssValKeyComp(68) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc264: TSynWebTokenKind;
begin
  if  CssValKeyComp(69) or
      CssValKeyComp(284) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc267: TSynWebTokenKind;
begin
  if  CssValKeyComp(205) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc269: TSynWebTokenKind;
begin
  if  CssValKeyComp(383) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc270: TSynWebTokenKind;
begin
  if  CssValKeyComp(709) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc271: TSynWebTokenKind;
begin
  if  CssValKeyComp(548) or
      CssValKeyComp(675) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc272: TSynWebTokenKind;
begin
  if  CssValKeyComp(676) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc274: TSynWebTokenKind;
begin
  if  CssValKeyComp(547) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc277: TSynWebTokenKind;
begin
  if  CssValKeyComp(209) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc279: TSynWebTokenKind;
begin
  if  CssValKeyComp(210) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc280: TSynWebTokenKind;
begin
  if  CssValKeyComp(207) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc282: TSynWebTokenKind;
begin
  if  CssValKeyComp(208) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc284: TSynWebTokenKind;
begin
  if  CssValKeyComp(623) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc286: TSynWebTokenKind;
begin
  if  CssValKeyComp(62) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc287: TSynWebTokenKind;
begin
  if  CssValKeyComp(63) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc288: TSynWebTokenKind;
begin
  if  CssValKeyComp(592) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc290: TSynWebTokenKind;
begin
  if  CssValKeyComp(461) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc291: TSynWebTokenKind;
begin
  if  CssValKeyComp(211) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc304: TSynWebTokenKind;
begin
  if  CssValKeyComp(216) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc305: TSynWebTokenKind;
begin
  if  CssValKeyComp(213) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc306: TSynWebTokenKind;
begin
  if  CssValKeyComp(217) or
      CssValKeyComp(458) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc309: TSynWebTokenKind;
begin
  if  CssValKeyComp(214) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc311: TSynWebTokenKind;
begin
  if  CssValKeyComp(215) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc324: TSynWebTokenKind;
begin
  if  CssValKeyComp(555) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc331: TSynWebTokenKind;
begin
  if  CssValKeyComp(466) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.CssValFunc348: TSynWebTokenKind;
begin
  if  CssValKeyComp(524) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;
