function TSynWebEngine.Css_PropUndef: TSynWebTokenKind;
begin
  Result:=stkCssPropUndef;
end;

function TSynWebEngine.Css_PropFunc29: TSynWebTokenKind;
begin
  if  Css_PropKeyComp(37) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.Css_PropFunc39: TSynWebTokenKind;
begin
  if  Css_PropKeyComp(31) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.Css_PropFunc40: TSynWebTokenKind;
begin
  if  Css_PropKeyComp(32) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.Css_PropFunc43: TSynWebTokenKind;
begin
  if  Css_PropKeyComp(53) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.Css_PropFunc51: TSynWebTokenKind;
begin
  if  Css_PropKeyComp(104) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.Css_PropFunc52: TSynWebTokenKind;
begin
  if  Css_PropKeyComp(93) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.Css_PropFunc54: TSynWebTokenKind;
begin
  if  Css_PropKeyComp(45) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.Css_PropFunc55: TSynWebTokenKind;
begin
  if  Css_PropKeyComp(46) or
      Css_PropKeyComp(75) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.Css_PropFunc56: TSynWebTokenKind;
begin
  if  Css_PropKeyComp(86) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.Css_PropFunc57: TSynWebTokenKind;
begin
  if  Css_PropKeyComp(52) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.Css_PropFunc60: TSynWebTokenKind;
begin
  if  Css_PropKeyComp(38) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.Css_PropFunc61: TSynWebTokenKind;
begin
  if  Css_PropKeyComp(39) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.Css_PropFunc62: TSynWebTokenKind;
begin
  if  Css_PropKeyComp(7) or
      Css_PropKeyComp(60) or
      Css_PropKeyComp(83) or
      Css_PropKeyComp(92) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.Css_PropFunc63: TSynWebTokenKind;
begin
  if  Css_PropKeyComp(33) or
      Css_PropKeyComp(114) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.Css_PropFunc64: TSynWebTokenKind;
begin
  if  Css_PropKeyComp(112) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.Css_PropFunc74: TSynWebTokenKind;
begin
  if  Css_PropKeyComp(67) or
      Css_PropKeyComp(94) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.Css_PropFunc76: TSynWebTokenKind;
begin
  if  Css_PropKeyComp(65) or
      Css_PropKeyComp(105) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.Css_PropFunc78: TSynWebTokenKind;
begin
  if  Css_PropKeyComp(55) or
      Css_PropKeyComp(80) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.Css_PropFunc79: TSynWebTokenKind;
begin
  if  Css_PropKeyComp(77) or
      Css_PropKeyComp(81) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.Css_PropFunc81: TSynWebTokenKind;
begin
  if  Css_PropKeyComp(68) or
      Css_PropKeyComp(97) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.Css_PropFunc82: TSynWebTokenKind;
begin
  if  Css_PropKeyComp(87) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.Css_PropFunc83: TSynWebTokenKind;
begin
  if  Css_PropKeyComp(66) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.Css_PropFunc85: TSynWebTokenKind;
begin
  if  Css_PropKeyComp(29) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.Css_PropFunc86: TSynWebTokenKind;
begin
  if  Css_PropKeyComp(14) or
      Css_PropKeyComp(42) or
      Css_PropKeyComp(62) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.Css_PropFunc87: TSynWebTokenKind;
begin
  if  Css_PropKeyComp(79) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.Css_PropFunc88: TSynWebTokenKind;
begin
  if  Css_PropKeyComp(82) or
      Css_PropKeyComp(109) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.Css_PropFunc90: TSynWebTokenKind;
begin
  if  Css_PropKeyComp(110) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.Css_PropFunc91: TSynWebTokenKind;
begin
  if  Css_PropKeyComp(34) or
      Css_PropKeyComp(69) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.Css_PropFunc93: TSynWebTokenKind;
begin
  if  Css_PropKeyComp(84) or
      Css_PropKeyComp(100) or
      Css_PropKeyComp(111) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.Css_PropFunc94: TSynWebTokenKind;
begin
  if  Css_PropKeyComp(24) or
      Css_PropKeyComp(40) or
      Css_PropKeyComp(64) or
      Css_PropKeyComp(85) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.Css_PropFunc95: TSynWebTokenKind;
begin
  if  Css_PropKeyComp(48) or
      Css_PropKeyComp(91) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.Css_PropFunc96: TSynWebTokenKind;
begin
  if  Css_PropKeyComp(1) or
      Css_PropKeyComp(30) or
      Css_PropKeyComp(70) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.Css_PropFunc97: TSynWebTokenKind;
begin
  if  Css_PropKeyComp(41) or
      Css_PropKeyComp(90) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.Css_PropFunc98: TSynWebTokenKind;
begin
  if  Css_PropKeyComp(0) or
      Css_PropKeyComp(78) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.Css_PropFunc100: TSynWebTokenKind;
begin
  if  Css_PropKeyComp(98) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.Css_PropFunc101: TSynWebTokenKind;
begin
  if  Css_PropKeyComp(108) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.Css_PropFunc102: TSynWebTokenKind;
begin
  if  Css_PropKeyComp(47) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.Css_PropFunc103: TSynWebTokenKind;
begin
  if  Css_PropKeyComp(43) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.Css_PropFunc105: TSynWebTokenKind;
begin
  if  Css_PropKeyComp(18) or
      Css_PropKeyComp(63) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.Css_PropFunc106: TSynWebTokenKind;
begin
  if  Css_PropKeyComp(13) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.Css_PropFunc107: TSynWebTokenKind;
begin
  if  Css_PropKeyComp(28) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.Css_PropFunc108: TSynWebTokenKind;
begin
  if  Css_PropKeyComp(51) or
      Css_PropKeyComp(88) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.Css_PropFunc110: TSynWebTokenKind;
begin
  if  Css_PropKeyComp(113) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.Css_PropFunc111: TSynWebTokenKind;
begin
  if  Css_PropKeyComp(44) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.Css_PropFunc112: TSynWebTokenKind;
begin
  if  Css_PropKeyComp(4) or
      Css_PropKeyComp(22) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.Css_PropFunc114: TSynWebTokenKind;
begin
  if  Css_PropKeyComp(106) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.Css_PropFunc115: TSynWebTokenKind;
begin
  if  Css_PropKeyComp(99) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.Css_PropFunc116: TSynWebTokenKind;
begin
  if  Css_PropKeyComp(74) or
      Css_PropKeyComp(102) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.Css_PropFunc117: TSynWebTokenKind;
begin
  if  Css_PropKeyComp(49) or
      Css_PropKeyComp(89) or
      Css_PropKeyComp(95) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.Css_PropFunc121: TSynWebTokenKind;
begin
  if  Css_PropKeyComp(50) or
      Css_PropKeyComp(76) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.Css_PropFunc122: TSynWebTokenKind;
begin
  if  Css_PropKeyComp(56) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.Css_PropFunc124: TSynWebTokenKind;
begin
  if  Css_PropKeyComp(23) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.Css_PropFunc126: TSynWebTokenKind;
begin
  if  Css_PropKeyComp(12) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.Css_PropFunc128: TSynWebTokenKind;
begin
  if  Css_PropKeyComp(8) or
      Css_PropKeyComp(61) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.Css_PropFunc130: TSynWebTokenKind;
begin
  if  Css_PropKeyComp(15) or
      Css_PropKeyComp(54) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.Css_PropFunc131: TSynWebTokenKind;
begin
  if  Css_PropKeyComp(17) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.Css_PropFunc136: TSynWebTokenKind;
begin
  if  Css_PropKeyComp(107) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.Css_PropFunc138: TSynWebTokenKind;
begin
  if  Css_PropKeyComp(25) or
      Css_PropKeyComp(57) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.Css_PropFunc139: TSynWebTokenKind;
begin
  if  Css_PropKeyComp(27) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.Css_PropFunc140: TSynWebTokenKind;
begin
  if  Css_PropKeyComp(3) or
      Css_PropKeyComp(71) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.Css_PropFunc141: TSynWebTokenKind;
begin
  if  Css_PropKeyComp(73) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.Css_PropFunc142: TSynWebTokenKind;
begin
  if  Css_PropKeyComp(6) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.Css_PropFunc144: TSynWebTokenKind;
begin
  if  Css_PropKeyComp(36) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.Css_PropFunc148: TSynWebTokenKind;
begin
  if  Css_PropKeyComp(16) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.Css_PropFunc149: TSynWebTokenKind;
begin
  if  Css_PropKeyComp(19) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.Css_PropFunc150: TSynWebTokenKind;
begin
  if  Css_PropKeyComp(21) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.Css_PropFunc154: TSynWebTokenKind;
begin
  if  Css_PropKeyComp(101) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.Css_PropFunc156: TSynWebTokenKind;
begin
  if  Css_PropKeyComp(26) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.Css_PropFunc158: TSynWebTokenKind;
begin
  if  Css_PropKeyComp(72) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.Css_PropFunc167: TSynWebTokenKind;
begin
  if  Css_PropKeyComp(20) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.Css_PropFunc169: TSynWebTokenKind;
begin
  if  Css_PropKeyComp(59) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.Css_PropFunc172: TSynWebTokenKind;
begin
  if  Css_PropKeyComp(9) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.Css_PropFunc173: TSynWebTokenKind;
begin
  if  Css_PropKeyComp(11) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.Css_PropFunc174: TSynWebTokenKind;
begin
  if  Css_PropKeyComp(103) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.Css_PropFunc178: TSynWebTokenKind;
begin
  if  Css_PropKeyComp(35) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.Css_PropFunc182: TSynWebTokenKind;
begin
  if  Css_PropKeyComp(2) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.Css_PropFunc187: TSynWebTokenKind;
begin
  if  Css_PropKeyComp(96) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.Css_PropFunc190: TSynWebTokenKind;
begin
  if  Css_PropKeyComp(10) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.Css_PropFunc194: TSynWebTokenKind;
begin
  if  Css_PropKeyComp(5) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.Css_PropFunc220: TSynWebTokenKind;
begin
  if  Css_PropKeyComp(58) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;
