function TSynWebEngine.Css_PropUndef: TSynWebTokenKind;
begin
  Result:=stkCssPropUndef;
end;

function TSynWebEngine.CSS_PropFunc29: TSynWebTokenKind;
begin
  if  CSS_PropKeyComp(37) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CSS_PropFunc39: TSynWebTokenKind;
begin
  if  CSS_PropKeyComp(31) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CSS_PropFunc40: TSynWebTokenKind;
begin
  if  CSS_PropKeyComp(32) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CSS_PropFunc43: TSynWebTokenKind;
begin
  if  CSS_PropKeyComp(53) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CSS_PropFunc51: TSynWebTokenKind;
begin
  if  CSS_PropKeyComp(104) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CSS_PropFunc52: TSynWebTokenKind;
begin
  if  CSS_PropKeyComp(93) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CSS_PropFunc54: TSynWebTokenKind;
begin
  if  CSS_PropKeyComp(45) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CSS_PropFunc55: TSynWebTokenKind;
begin
  if  CSS_PropKeyComp(46) or
      CSS_PropKeyComp(75) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CSS_PropFunc56: TSynWebTokenKind;
begin
  if  CSS_PropKeyComp(86) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CSS_PropFunc57: TSynWebTokenKind;
begin
  if  CSS_PropKeyComp(52) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CSS_PropFunc60: TSynWebTokenKind;
begin
  if  CSS_PropKeyComp(38) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CSS_PropFunc61: TSynWebTokenKind;
begin
  if  CSS_PropKeyComp(39) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CSS_PropFunc62: TSynWebTokenKind;
begin
  if  CSS_PropKeyComp(7) or
      CSS_PropKeyComp(60) or
      CSS_PropKeyComp(83) or
      CSS_PropKeyComp(92) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CSS_PropFunc63: TSynWebTokenKind;
begin
  if  CSS_PropKeyComp(33) or
      CSS_PropKeyComp(114) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CSS_PropFunc64: TSynWebTokenKind;
begin
  if  CSS_PropKeyComp(112) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CSS_PropFunc74: TSynWebTokenKind;
begin
  if  CSS_PropKeyComp(67) or
      CSS_PropKeyComp(94) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CSS_PropFunc76: TSynWebTokenKind;
begin
  if  CSS_PropKeyComp(65) or
      CSS_PropKeyComp(105) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CSS_PropFunc78: TSynWebTokenKind;
begin
  if  CSS_PropKeyComp(55) or
      CSS_PropKeyComp(80) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CSS_PropFunc79: TSynWebTokenKind;
begin
  if  CSS_PropKeyComp(77) or
      CSS_PropKeyComp(81) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CSS_PropFunc81: TSynWebTokenKind;
begin
  if  CSS_PropKeyComp(68) or
      CSS_PropKeyComp(97) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CSS_PropFunc82: TSynWebTokenKind;
begin
  if  CSS_PropKeyComp(87) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CSS_PropFunc83: TSynWebTokenKind;
begin
  if  CSS_PropKeyComp(66) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CSS_PropFunc85: TSynWebTokenKind;
begin
  if  CSS_PropKeyComp(29) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CSS_PropFunc86: TSynWebTokenKind;
begin
  if  CSS_PropKeyComp(14) or
      CSS_PropKeyComp(42) or
      CSS_PropKeyComp(62) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CSS_PropFunc87: TSynWebTokenKind;
begin
  if  CSS_PropKeyComp(79) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CSS_PropFunc88: TSynWebTokenKind;
begin
  if  CSS_PropKeyComp(82) or
      CSS_PropKeyComp(109) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CSS_PropFunc90: TSynWebTokenKind;
begin
  if  CSS_PropKeyComp(110) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CSS_PropFunc91: TSynWebTokenKind;
begin
  if  CSS_PropKeyComp(34) or
      CSS_PropKeyComp(69) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CSS_PropFunc93: TSynWebTokenKind;
begin
  if  CSS_PropKeyComp(84) or
      CSS_PropKeyComp(100) or
      CSS_PropKeyComp(111) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CSS_PropFunc94: TSynWebTokenKind;
begin
  if  CSS_PropKeyComp(24) or
      CSS_PropKeyComp(40) or
      CSS_PropKeyComp(64) or
      CSS_PropKeyComp(85) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CSS_PropFunc95: TSynWebTokenKind;
begin
  if  CSS_PropKeyComp(48) or
      CSS_PropKeyComp(91) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CSS_PropFunc96: TSynWebTokenKind;
begin
  if  CSS_PropKeyComp(1) or
      CSS_PropKeyComp(30) or
      CSS_PropKeyComp(70) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CSS_PropFunc97: TSynWebTokenKind;
begin
  if  CSS_PropKeyComp(41) or
      CSS_PropKeyComp(90) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CSS_PropFunc98: TSynWebTokenKind;
begin
  if  CSS_PropKeyComp(0) or
      CSS_PropKeyComp(78) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CSS_PropFunc100: TSynWebTokenKind;
begin
  if  CSS_PropKeyComp(98) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CSS_PropFunc101: TSynWebTokenKind;
begin
  if  CSS_PropKeyComp(108) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CSS_PropFunc102: TSynWebTokenKind;
begin
  if  CSS_PropKeyComp(47) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CSS_PropFunc103: TSynWebTokenKind;
begin
  if  CSS_PropKeyComp(43) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CSS_PropFunc105: TSynWebTokenKind;
begin
  if  CSS_PropKeyComp(18) or
      CSS_PropKeyComp(63) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CSS_PropFunc106: TSynWebTokenKind;
begin
  if  CSS_PropKeyComp(13) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CSS_PropFunc107: TSynWebTokenKind;
begin
  if  CSS_PropKeyComp(28) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CSS_PropFunc108: TSynWebTokenKind;
begin
  if  CSS_PropKeyComp(51) or
      CSS_PropKeyComp(88) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CSS_PropFunc110: TSynWebTokenKind;
begin
  if  CSS_PropKeyComp(113) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CSS_PropFunc111: TSynWebTokenKind;
begin
  if  CSS_PropKeyComp(44) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CSS_PropFunc112: TSynWebTokenKind;
begin
  if  CSS_PropKeyComp(4) or
      CSS_PropKeyComp(22) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CSS_PropFunc114: TSynWebTokenKind;
begin
  if  CSS_PropKeyComp(106) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CSS_PropFunc115: TSynWebTokenKind;
begin
  if  CSS_PropKeyComp(99) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CSS_PropFunc116: TSynWebTokenKind;
begin
  if  CSS_PropKeyComp(74) or
      CSS_PropKeyComp(102) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CSS_PropFunc117: TSynWebTokenKind;
begin
  if  CSS_PropKeyComp(49) or
      CSS_PropKeyComp(89) or
      CSS_PropKeyComp(95) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CSS_PropFunc121: TSynWebTokenKind;
begin
  if  CSS_PropKeyComp(50) or
      CSS_PropKeyComp(76) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CSS_PropFunc122: TSynWebTokenKind;
begin
  if  CSS_PropKeyComp(56) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CSS_PropFunc124: TSynWebTokenKind;
begin
  if  CSS_PropKeyComp(23) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CSS_PropFunc126: TSynWebTokenKind;
begin
  if  CSS_PropKeyComp(12) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CSS_PropFunc128: TSynWebTokenKind;
begin
  if  CSS_PropKeyComp(8) or
      CSS_PropKeyComp(61) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CSS_PropFunc130: TSynWebTokenKind;
begin
  if  CSS_PropKeyComp(15) or
      CSS_PropKeyComp(54) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CSS_PropFunc131: TSynWebTokenKind;
begin
  if  CSS_PropKeyComp(17) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CSS_PropFunc136: TSynWebTokenKind;
begin
  if  CSS_PropKeyComp(107) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CSS_PropFunc138: TSynWebTokenKind;
begin
  if  CSS_PropKeyComp(25) or
      CSS_PropKeyComp(57) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CSS_PropFunc139: TSynWebTokenKind;
begin
  if  CSS_PropKeyComp(27) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CSS_PropFunc140: TSynWebTokenKind;
begin
  if  CSS_PropKeyComp(3) or
      CSS_PropKeyComp(71) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CSS_PropFunc141: TSynWebTokenKind;
begin
  if  CSS_PropKeyComp(73) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CSS_PropFunc142: TSynWebTokenKind;
begin
  if  CSS_PropKeyComp(6) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CSS_PropFunc144: TSynWebTokenKind;
begin
  if  CSS_PropKeyComp(36) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CSS_PropFunc148: TSynWebTokenKind;
begin
  if  CSS_PropKeyComp(16) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CSS_PropFunc149: TSynWebTokenKind;
begin
  if  CSS_PropKeyComp(19) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CSS_PropFunc150: TSynWebTokenKind;
begin
  if  CSS_PropKeyComp(21) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CSS_PropFunc154: TSynWebTokenKind;
begin
  if  CSS_PropKeyComp(101) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CSS_PropFunc156: TSynWebTokenKind;
begin
  if  CSS_PropKeyComp(26) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CSS_PropFunc158: TSynWebTokenKind;
begin
  if  CSS_PropKeyComp(72) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CSS_PropFunc167: TSynWebTokenKind;
begin
  if  CSS_PropKeyComp(20) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CSS_PropFunc169: TSynWebTokenKind;
begin
  if  CSS_PropKeyComp(59) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CSS_PropFunc172: TSynWebTokenKind;
begin
  if  CSS_PropKeyComp(9) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CSS_PropFunc173: TSynWebTokenKind;
begin
  if  CSS_PropKeyComp(11) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CSS_PropFunc174: TSynWebTokenKind;
begin
  if  CSS_PropKeyComp(103) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CSS_PropFunc178: TSynWebTokenKind;
begin
  if  CSS_PropKeyComp(35) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CSS_PropFunc182: TSynWebTokenKind;
begin
  if  CSS_PropKeyComp(2) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CSS_PropFunc187: TSynWebTokenKind;
begin
  if  CSS_PropKeyComp(96) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CSS_PropFunc190: TSynWebTokenKind;
begin
  if  CSS_PropKeyComp(10) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CSS_PropFunc194: TSynWebTokenKind;
begin
  if  CSS_PropKeyComp(5) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CSS_PropFunc220: TSynWebTokenKind;
begin
  if  CSS_PropKeyComp(58) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;
