function TSynWebEngine.HTML_AttrUndef: TSynWebTokenKind;
begin
  Result:=stkHTMLTagKeyUndef;
end;

function TSynWebEngine.HTML_AttrFunc13: TSynWebTokenKind;
begin
  if  HTML_AttrKeyComp(55) then
    Result := stkHTMLTagKey
  else
    Result := stkHTMLTagKeyUndef;
end;

function TSynWebEngine.HTML_AttrFunc15: TSynWebTokenKind;
begin
  if  HTML_AttrKeyComp(45) then
    Result := stkHTMLTagKey
  else
    Result := stkHTMLTagKeyUndef;
end;

function TSynWebEngine.HTML_AttrFunc23: TSynWebTokenKind;
begin
  if  HTML_AttrKeyComp(0) then
    Result := stkHTMLTagKey
  else
    Result := stkHTMLTagKeyUndef;
end;

function TSynWebEngine.HTML_AttrFunc26: TSynWebTokenKind;
begin
  if  HTML_AttrKeyComp(32) then
    Result := stkHTMLTagKey
  else
    Result := stkHTMLTagKeyUndef;
end;

function TSynWebEngine.HTML_AttrFunc27: TSynWebTokenKind;
begin
  if  HTML_AttrKeyComp(23) then
    Result := stkHTMLTagKey
  else
    Result := stkHTMLTagKeyUndef;
end;

function TSynWebEngine.HTML_AttrFunc30: TSynWebTokenKind;
begin
  if  HTML_AttrKeyComp(15) then
    Result := stkHTMLTagKey
  else
    Result := stkHTMLTagKeyUndef;
end;

function TSynWebEngine.HTML_AttrFunc31: TSynWebTokenKind;
begin
  if  HTML_AttrKeyComp(40) then
    Result := stkHTMLTagKey
  else
    Result := stkHTMLTagKeyUndef;
end;

function TSynWebEngine.HTML_AttrFunc32: TSynWebTokenKind;
begin
  if  HTML_AttrKeyComp(57) or
      HTML_AttrKeyComp(65) then
    Result := stkHTMLTagKey
  else
    Result := stkHTMLTagKeyUndef;
end;

function TSynWebEngine.HTML_AttrFunc33: TSynWebTokenKind;
begin
  if  HTML_AttrKeyComp(7) or
      HTML_AttrKeyComp(68) then
    Result := stkHTMLTagKey
  else
    Result := stkHTMLTagKeyUndef;
end;

function TSynWebEngine.HTML_AttrFunc34: TSynWebTokenKind;
begin
  if  HTML_AttrKeyComp(58) then
    Result := stkHTMLTagKey
  else
    Result := stkHTMLTagKeyUndef;
end;

function TSynWebEngine.HTML_AttrFunc35: TSynWebTokenKind;
begin
  if  HTML_AttrKeyComp(95) then
    Result := stkHTMLTagKey
  else
    Result := stkHTMLTagKeyUndef;
end;

function TSynWebEngine.HTML_AttrFunc37: TSynWebTokenKind;
begin
  if  HTML_AttrKeyComp(19) or
      HTML_AttrKeyComp(51) then
    Result := stkHTMLTagKey
  else
    Result := stkHTMLTagKeyUndef;
end;

function TSynWebEngine.HTML_AttrFunc38: TSynWebTokenKind;
begin
  if  HTML_AttrKeyComp(39) then
    Result := stkHTMLTagKey
  else
    Result := stkHTMLTagKeyUndef;
end;

function TSynWebEngine.HTML_AttrFunc39: TSynWebTokenKind;
begin
  if  HTML_AttrKeyComp(18) or
      HTML_AttrKeyComp(22) or
      HTML_AttrKeyComp(46) then
    Result := stkHTMLTagKey
  else
    Result := stkHTMLTagKeyUndef;
end;

function TSynWebEngine.HTML_AttrFunc40: TSynWebTokenKind;
begin
  if  HTML_AttrKeyComp(107) then
    Result := stkHTMLTagKey
  else
    Result := stkHTMLTagKeyUndef;
end;

function TSynWebEngine.HTML_AttrFunc43: TSynWebTokenKind;
begin
  if  HTML_AttrKeyComp(5) or
      HTML_AttrKeyComp(47) then
    Result := stkHTMLTagKey
  else
    Result := stkHTMLTagKeyUndef;
end;

function TSynWebEngine.HTML_AttrFunc45: TSynWebTokenKind;
begin
  if  HTML_AttrKeyComp(96) then
    Result := stkHTMLTagKey
  else
    Result := stkHTMLTagKeyUndef;
end;

function TSynWebEngine.HTML_AttrFunc46: TSynWebTokenKind;
begin
  if  HTML_AttrKeyComp(60) then
    Result := stkHTMLTagKey
  else
    Result := stkHTMLTagKeyUndef;
end;

function TSynWebEngine.HTML_AttrFunc47: TSynWebTokenKind;
begin
  if  HTML_AttrKeyComp(6) then
    Result := stkHTMLTagKey
  else
    Result := stkHTMLTagKeyUndef;
end;

function TSynWebEngine.HTML_AttrFunc48: TSynWebTokenKind;
begin
  if  HTML_AttrKeyComp(1) or
      HTML_AttrKeyComp(33) or
      HTML_AttrKeyComp(38) then
    Result := stkHTMLTagKey
  else
    Result := stkHTMLTagKeyUndef;
end;

function TSynWebEngine.HTML_AttrFunc49: TSynWebTokenKind;
begin
  if  HTML_AttrKeyComp(27) or
      HTML_AttrKeyComp(104) then
    Result := stkHTMLTagKey
  else
    Result := stkHTMLTagKeyUndef;
end;

function TSynWebEngine.HTML_AttrFunc50: TSynWebTokenKind;
begin
  if  HTML_AttrKeyComp(106) then
    Result := stkHTMLTagKey
  else
    Result := stkHTMLTagKeyUndef;
end;

function TSynWebEngine.HTML_AttrFunc52: TSynWebTokenKind;
begin
  if  HTML_AttrKeyComp(53) then
    Result := stkHTMLTagKey
  else
    Result := stkHTMLTagKeyUndef;
end;

function TSynWebEngine.HTML_AttrFunc53: TSynWebTokenKind;
begin
  if  HTML_AttrKeyComp(9) or
      HTML_AttrKeyComp(100) then
    Result := stkHTMLTagKey
  else
    Result := stkHTMLTagKeyUndef;
end;

function TSynWebEngine.HTML_AttrFunc54: TSynWebTokenKind;
begin
  if  HTML_AttrKeyComp(20) or
      HTML_AttrKeyComp(24) then
    Result := stkHTMLTagKey
  else
    Result := stkHTMLTagKeyUndef;
end;

function TSynWebEngine.HTML_AttrFunc55: TSynWebTokenKind;
begin
  if  HTML_AttrKeyComp(73) then
    Result := stkHTMLTagKey
  else
    Result := stkHTMLTagKeyUndef;
end;

function TSynWebEngine.HTML_AttrFunc56: TSynWebTokenKind;
begin
  if  HTML_AttrKeyComp(41) then
    Result := stkHTMLTagKey
  else
    Result := stkHTMLTagKeyUndef;
end;

function TSynWebEngine.HTML_AttrFunc57: TSynWebTokenKind;
begin
  if  HTML_AttrKeyComp(16) or
      HTML_AttrKeyComp(50) then
    Result := stkHTMLTagKey
  else
    Result := stkHTMLTagKeyUndef;
end;

function TSynWebEngine.HTML_AttrFunc58: TSynWebTokenKind;
begin
  if  HTML_AttrKeyComp(56) or
      HTML_AttrKeyComp(101) then
    Result := stkHTMLTagKey
  else
    Result := stkHTMLTagKeyUndef;
end;

function TSynWebEngine.HTML_AttrFunc59: TSynWebTokenKind;
begin
  if  HTML_AttrKeyComp(105) then
    Result := stkHTMLTagKey
  else
    Result := stkHTMLTagKeyUndef;
end;

function TSynWebEngine.HTML_AttrFunc60: TSynWebTokenKind;
begin
  if  HTML_AttrKeyComp(49) then
    Result := stkHTMLTagKey
  else
    Result := stkHTMLTagKeyUndef;
end;

function TSynWebEngine.HTML_AttrFunc61: TSynWebTokenKind;
begin
  if  HTML_AttrKeyComp(82) or
      HTML_AttrKeyComp(119) then
    Result := stkHTMLTagKey
  else
    Result := stkHTMLTagKeyUndef;
end;

function TSynWebEngine.HTML_AttrFunc62: TSynWebTokenKind;
begin
  if  HTML_AttrKeyComp(4) or
      HTML_AttrKeyComp(12) then
    Result := stkHTMLTagKey
  else
    Result := stkHTMLTagKeyUndef;
end;

function TSynWebEngine.HTML_AttrFunc63: TSynWebTokenKind;
begin
  if  HTML_AttrKeyComp(26) then
    Result := stkHTMLTagKey
  else
    Result := stkHTMLTagKeyUndef;
end;

function TSynWebEngine.HTML_AttrFunc64: TSynWebTokenKind;
begin
  if  HTML_AttrKeyComp(124) then
    Result := stkHTMLTagKey
  else
    Result := stkHTMLTagKeyUndef;
end;

function TSynWebEngine.HTML_AttrFunc65: TSynWebTokenKind;
begin
  if  HTML_AttrKeyComp(66) or
      HTML_AttrKeyComp(118) then
    Result := stkHTMLTagKey
  else
    Result := stkHTMLTagKeyUndef;
end;

function TSynWebEngine.HTML_AttrFunc66: TSynWebTokenKind;
begin
  if  HTML_AttrKeyComp(8) or
      HTML_AttrKeyComp(36) or
      HTML_AttrKeyComp(44) or
      HTML_AttrKeyComp(69) or
      HTML_AttrKeyComp(71) or
      HTML_AttrKeyComp(115) or
      HTML_AttrKeyComp(116) or
      HTML_AttrKeyComp(123) then
    Result := stkHTMLTagKey
  else
    Result := stkHTMLTagKeyUndef;
end;

function TSynWebEngine.HTML_AttrFunc67: TSynWebTokenKind;
begin
  if  HTML_AttrKeyComp(21) or
      HTML_AttrKeyComp(75) or
      HTML_AttrKeyComp(76) then
    Result := stkHTMLTagKey
  else
    Result := stkHTMLTagKeyUndef;
end;

function TSynWebEngine.HTML_AttrFunc68: TSynWebTokenKind;
begin
  if  HTML_AttrKeyComp(59) or
      HTML_AttrKeyComp(122) then
    Result := stkHTMLTagKey
  else
    Result := stkHTMLTagKeyUndef;
end;

function TSynWebEngine.HTML_AttrFunc69: TSynWebTokenKind;
begin
  if  HTML_AttrKeyComp(114) then
    Result := stkHTMLTagKey
  else
    Result := stkHTMLTagKeyUndef;
end;

function TSynWebEngine.HTML_AttrFunc71: TSynWebTokenKind;
begin
  if  HTML_AttrKeyComp(29) or
      HTML_AttrKeyComp(42) or
      HTML_AttrKeyComp(52) or
      HTML_AttrKeyComp(113) then
    Result := stkHTMLTagKey
  else
    Result := stkHTMLTagKeyUndef;
end;

function TSynWebEngine.HTML_AttrFunc72: TSynWebTokenKind;
begin
  if  HTML_AttrKeyComp(11) then
    Result := stkHTMLTagKey
  else
    Result := stkHTMLTagKeyUndef;
end;

function TSynWebEngine.HTML_AttrFunc73: TSynWebTokenKind;
begin
  if  HTML_AttrKeyComp(103) then
    Result := stkHTMLTagKey
  else
    Result := stkHTMLTagKeyUndef;
end;

function TSynWebEngine.HTML_AttrFunc74: TSynWebTokenKind;
begin
  if  HTML_AttrKeyComp(17) or
      HTML_AttrKeyComp(31) then
    Result := stkHTMLTagKey
  else
    Result := stkHTMLTagKeyUndef;
end;

function TSynWebEngine.HTML_AttrFunc75: TSynWebTokenKind;
begin
  if  HTML_AttrKeyComp(97) or
      HTML_AttrKeyComp(99) or
      HTML_AttrKeyComp(117) then
    Result := stkHTMLTagKey
  else
    Result := stkHTMLTagKeyUndef;
end;

function TSynWebEngine.HTML_AttrFunc77: TSynWebTokenKind;
begin
  if  HTML_AttrKeyComp(37) or
      HTML_AttrKeyComp(125) then
    Result := stkHTMLTagKey
  else
    Result := stkHTMLTagKeyUndef;
end;

function TSynWebEngine.HTML_AttrFunc78: TSynWebTokenKind;
begin
  if  HTML_AttrKeyComp(109) then
    Result := stkHTMLTagKey
  else
    Result := stkHTMLTagKeyUndef;
end;

function TSynWebEngine.HTML_AttrFunc79: TSynWebTokenKind;
begin
  if  HTML_AttrKeyComp(61) or
      HTML_AttrKeyComp(112) then
    Result := stkHTMLTagKey
  else
    Result := stkHTMLTagKeyUndef;
end;

function TSynWebEngine.HTML_AttrFunc80: TSynWebTokenKind;
begin
  if  HTML_AttrKeyComp(28) then
    Result := stkHTMLTagKey
  else
    Result := stkHTMLTagKeyUndef;
end;

function TSynWebEngine.HTML_AttrFunc81: TSynWebTokenKind;
begin
  if  HTML_AttrKeyComp(92) or
      HTML_AttrKeyComp(110) then
    Result := stkHTMLTagKey
  else
    Result := stkHTMLTagKeyUndef;
end;

function TSynWebEngine.HTML_AttrFunc82: TSynWebTokenKind;
begin
  if  HTML_AttrKeyComp(74) or
      HTML_AttrKeyComp(127) then
    Result := stkHTMLTagKey
  else
    Result := stkHTMLTagKeyUndef;
end;

function TSynWebEngine.HTML_AttrFunc85: TSynWebTokenKind;
begin
  if  HTML_AttrKeyComp(77) or
      HTML_AttrKeyComp(108) then
    Result := stkHTMLTagKey
  else
    Result := stkHTMLTagKeyUndef;
end;

function TSynWebEngine.HTML_AttrFunc87: TSynWebTokenKind;
begin
  if  HTML_AttrKeyComp(13) or
      HTML_AttrKeyComp(72) or
      HTML_AttrKeyComp(126) then
    Result := stkHTMLTagKey
  else
    Result := stkHTMLTagKeyUndef;
end;

function TSynWebEngine.HTML_AttrFunc88: TSynWebTokenKind;
begin
  if  HTML_AttrKeyComp(43) then
    Result := stkHTMLTagKey
  else
    Result := stkHTMLTagKeyUndef;
end;

function TSynWebEngine.HTML_AttrFunc91: TSynWebTokenKind;
begin
  if  HTML_AttrKeyComp(3) or
      HTML_AttrKeyComp(30) then
    Result := stkHTMLTagKey
  else
    Result := stkHTMLTagKeyUndef;
end;

function TSynWebEngine.HTML_AttrFunc93: TSynWebTokenKind;
begin
  if  HTML_AttrKeyComp(25) or
      HTML_AttrKeyComp(78) or
      HTML_AttrKeyComp(89) then
    Result := stkHTMLTagKey
  else
    Result := stkHTMLTagKeyUndef;
end;

function TSynWebEngine.HTML_AttrFunc94: TSynWebTokenKind;
begin
  if  HTML_AttrKeyComp(94) then
    Result := stkHTMLTagKey
  else
    Result := stkHTMLTagKeyUndef;
end;

function TSynWebEngine.HTML_AttrFunc96: TSynWebTokenKind;
begin
  if  HTML_AttrKeyComp(10) or
      HTML_AttrKeyComp(88) or
      HTML_AttrKeyComp(91) then
    Result := stkHTMLTagKey
  else
    Result := stkHTMLTagKeyUndef;
end;

function TSynWebEngine.HTML_AttrFunc98: TSynWebTokenKind;
begin
  if  HTML_AttrKeyComp(93) then
    Result := stkHTMLTagKey
  else
    Result := stkHTMLTagKeyUndef;
end;

function TSynWebEngine.HTML_AttrFunc101: TSynWebTokenKind;
begin
  if  HTML_AttrKeyComp(14) then
    Result := stkHTMLTagKey
  else
    Result := stkHTMLTagKeyUndef;
end;

function TSynWebEngine.HTML_AttrFunc102: TSynWebTokenKind;
begin
  if  HTML_AttrKeyComp(121) then
    Result := stkHTMLTagKey
  else
    Result := stkHTMLTagKeyUndef;
end;

function TSynWebEngine.HTML_AttrFunc103: TSynWebTokenKind;
begin
  if  HTML_AttrKeyComp(2) then
    Result := stkHTMLTagKey
  else
    Result := stkHTMLTagKeyUndef;
end;

function TSynWebEngine.HTML_AttrFunc104: TSynWebTokenKind;
begin
  if  HTML_AttrKeyComp(64) then
    Result := stkHTMLTagKey
  else
    Result := stkHTMLTagKeyUndef;
end;

function TSynWebEngine.HTML_AttrFunc105: TSynWebTokenKind;
begin
  if  HTML_AttrKeyComp(48) then
    Result := stkHTMLTagKey
  else
    Result := stkHTMLTagKeyUndef;
end;

function TSynWebEngine.HTML_AttrFunc106: TSynWebTokenKind;
begin
  if  HTML_AttrKeyComp(98) then
    Result := stkHTMLTagKey
  else
    Result := stkHTMLTagKeyUndef;
end;

function TSynWebEngine.HTML_AttrFunc107: TSynWebTokenKind;
begin
  if  HTML_AttrKeyComp(81) then
    Result := stkHTMLTagKey
  else
    Result := stkHTMLTagKeyUndef;
end;

function TSynWebEngine.HTML_AttrFunc108: TSynWebTokenKind;
begin
  if  HTML_AttrKeyComp(67) then
    Result := stkHTMLTagKey
  else
    Result := stkHTMLTagKeyUndef;
end;

function TSynWebEngine.HTML_AttrFunc109: TSynWebTokenKind;
begin
  if  HTML_AttrKeyComp(102) then
    Result := stkHTMLTagKey
  else
    Result := stkHTMLTagKeyUndef;
end;

function TSynWebEngine.HTML_AttrFunc110: TSynWebTokenKind;
begin
  if  HTML_AttrKeyComp(111) then
    Result := stkHTMLTagKey
  else
    Result := stkHTMLTagKeyUndef;
end;

function TSynWebEngine.HTML_AttrFunc111: TSynWebTokenKind;
begin
  if  HTML_AttrKeyComp(70) then
    Result := stkHTMLTagKey
  else
    Result := stkHTMLTagKeyUndef;
end;

function TSynWebEngine.HTML_AttrFunc113: TSynWebTokenKind;
begin
  if  HTML_AttrKeyComp(90) then
    Result := stkHTMLTagKey
  else
    Result := stkHTMLTagKeyUndef;
end;

function TSynWebEngine.HTML_AttrFunc114: TSynWebTokenKind;
begin
  if  HTML_AttrKeyComp(35) then
    Result := stkHTMLTagKey
  else
    Result := stkHTMLTagKeyUndef;
end;

function TSynWebEngine.HTML_AttrFunc119: TSynWebTokenKind;
begin
  if  HTML_AttrKeyComp(34) or
      HTML_AttrKeyComp(54) or
      HTML_AttrKeyComp(62) then
    Result := stkHTMLTagKey
  else
    Result := stkHTMLTagKeyUndef;
end;

function TSynWebEngine.HTML_AttrFunc126: TSynWebTokenKind;
begin
  if  HTML_AttrKeyComp(63) or
      HTML_AttrKeyComp(79) then
    Result := stkHTMLTagKey
  else
    Result := stkHTMLTagKeyUndef;
end;

function TSynWebEngine.HTML_AttrFunc127: TSynWebTokenKind;
begin
  if  HTML_AttrKeyComp(120) then
    Result := stkHTMLTagKey
  else
    Result := stkHTMLTagKeyUndef;
end;

function TSynWebEngine.HTML_AttrFunc139: TSynWebTokenKind;
begin
  if  HTML_AttrKeyComp(87) then
    Result := stkHTMLTagKey
  else
    Result := stkHTMLTagKeyUndef;
end;

function TSynWebEngine.HTML_AttrFunc147: TSynWebTokenKind;
begin
  if  HTML_AttrKeyComp(80) then
    Result := stkHTMLTagKey
  else
    Result := stkHTMLTagKeyUndef;
end;

function TSynWebEngine.HTML_AttrFunc157: TSynWebTokenKind;
begin
  if  HTML_AttrKeyComp(84) then
    Result := stkHTMLTagKey
  else
    Result := stkHTMLTagKeyUndef;
end;

function TSynWebEngine.HTML_AttrFunc158: TSynWebTokenKind;
begin
  if  HTML_AttrKeyComp(83) or
      HTML_AttrKeyComp(85) then
    Result := stkHTMLTagKey
  else
    Result := stkHTMLTagKeyUndef;
end;

function TSynWebEngine.HTML_AttrFunc162: TSynWebTokenKind;
begin
  if  HTML_AttrKeyComp(86) then
    Result := stkHTMLTagKey
  else
    Result := stkHTMLTagKeyUndef;
end;
