function TSynWebEngine.Html_AttrUndef: TSynWebTokenKind;
begin
  Result:=stkHtmlTagKeyUndef;
end;

function TSynWebEngine.Html_AttrFunc13: TSynWebTokenKind;
begin
  if  Html_AttrKeyComp(55) then
    Result := stkHtmlTagKey
  else
    Result := stkHtmlTagKeyUndef;
end;

function TSynWebEngine.Html_AttrFunc15: TSynWebTokenKind;
begin
  if  Html_AttrKeyComp(45) then
    Result := stkHtmlTagKey
  else
    Result := stkHtmlTagKeyUndef;
end;

function TSynWebEngine.Html_AttrFunc23: TSynWebTokenKind;
begin
  if  Html_AttrKeyComp(0) then
    Result := stkHtmlTagKey
  else
    Result := stkHtmlTagKeyUndef;
end;

function TSynWebEngine.Html_AttrFunc26: TSynWebTokenKind;
begin
  if  Html_AttrKeyComp(32) then
    Result := stkHtmlTagKey
  else
    Result := stkHtmlTagKeyUndef;
end;

function TSynWebEngine.Html_AttrFunc27: TSynWebTokenKind;
begin
  if  Html_AttrKeyComp(23) then
    Result := stkHtmlTagKey
  else
    Result := stkHtmlTagKeyUndef;
end;

function TSynWebEngine.Html_AttrFunc30: TSynWebTokenKind;
begin
  if  Html_AttrKeyComp(15) then
    Result := stkHtmlTagKey
  else
    Result := stkHtmlTagKeyUndef;
end;

function TSynWebEngine.Html_AttrFunc31: TSynWebTokenKind;
begin
  if  Html_AttrKeyComp(40) then
    Result := stkHtmlTagKey
  else
    Result := stkHtmlTagKeyUndef;
end;

function TSynWebEngine.Html_AttrFunc32: TSynWebTokenKind;
begin
  if  Html_AttrKeyComp(57) or
      Html_AttrKeyComp(65) then
    Result := stkHtmlTagKey
  else
    Result := stkHtmlTagKeyUndef;
end;

function TSynWebEngine.Html_AttrFunc33: TSynWebTokenKind;
begin
  if  Html_AttrKeyComp(7) or
      Html_AttrKeyComp(68) then
    Result := stkHtmlTagKey
  else
    Result := stkHtmlTagKeyUndef;
end;

function TSynWebEngine.Html_AttrFunc34: TSynWebTokenKind;
begin
  if  Html_AttrKeyComp(58) then
    Result := stkHtmlTagKey
  else
    Result := stkHtmlTagKeyUndef;
end;

function TSynWebEngine.Html_AttrFunc35: TSynWebTokenKind;
begin
  if  Html_AttrKeyComp(95) then
    Result := stkHtmlTagKey
  else
    Result := stkHtmlTagKeyUndef;
end;

function TSynWebEngine.Html_AttrFunc37: TSynWebTokenKind;
begin
  if  Html_AttrKeyComp(19) or
      Html_AttrKeyComp(51) then
    Result := stkHtmlTagKey
  else
    Result := stkHtmlTagKeyUndef;
end;

function TSynWebEngine.Html_AttrFunc38: TSynWebTokenKind;
begin
  if  Html_AttrKeyComp(39) then
    Result := stkHtmlTagKey
  else
    Result := stkHtmlTagKeyUndef;
end;

function TSynWebEngine.Html_AttrFunc39: TSynWebTokenKind;
begin
  if  Html_AttrKeyComp(18) or
      Html_AttrKeyComp(22) or
      Html_AttrKeyComp(46) then
    Result := stkHtmlTagKey
  else
    Result := stkHtmlTagKeyUndef;
end;

function TSynWebEngine.Html_AttrFunc40: TSynWebTokenKind;
begin
  if  Html_AttrKeyComp(107) then
    Result := stkHtmlTagKey
  else
    Result := stkHtmlTagKeyUndef;
end;

function TSynWebEngine.Html_AttrFunc43: TSynWebTokenKind;
begin
  if  Html_AttrKeyComp(5) or
      Html_AttrKeyComp(47) then
    Result := stkHtmlTagKey
  else
    Result := stkHtmlTagKeyUndef;
end;

function TSynWebEngine.Html_AttrFunc45: TSynWebTokenKind;
begin
  if  Html_AttrKeyComp(96) then
    Result := stkHtmlTagKey
  else
    Result := stkHtmlTagKeyUndef;
end;

function TSynWebEngine.Html_AttrFunc46: TSynWebTokenKind;
begin
  if  Html_AttrKeyComp(60) then
    Result := stkHtmlTagKey
  else
    Result := stkHtmlTagKeyUndef;
end;

function TSynWebEngine.Html_AttrFunc47: TSynWebTokenKind;
begin
  if  Html_AttrKeyComp(6) then
    Result := stkHtmlTagKey
  else
    Result := stkHtmlTagKeyUndef;
end;

function TSynWebEngine.Html_AttrFunc48: TSynWebTokenKind;
begin
  if  Html_AttrKeyComp(1) or
      Html_AttrKeyComp(33) or
      Html_AttrKeyComp(38) then
    Result := stkHtmlTagKey
  else
    Result := stkHtmlTagKeyUndef;
end;

function TSynWebEngine.Html_AttrFunc49: TSynWebTokenKind;
begin
  if  Html_AttrKeyComp(27) or
      Html_AttrKeyComp(104) then
    Result := stkHtmlTagKey
  else
    Result := stkHtmlTagKeyUndef;
end;

function TSynWebEngine.Html_AttrFunc50: TSynWebTokenKind;
begin
  if  Html_AttrKeyComp(106) then
    Result := stkHtmlTagKey
  else
    Result := stkHtmlTagKeyUndef;
end;

function TSynWebEngine.Html_AttrFunc52: TSynWebTokenKind;
begin
  if  Html_AttrKeyComp(53) then
    Result := stkHtmlTagKey
  else
    Result := stkHtmlTagKeyUndef;
end;

function TSynWebEngine.Html_AttrFunc53: TSynWebTokenKind;
begin
  if  Html_AttrKeyComp(9) or
      Html_AttrKeyComp(100) then
    Result := stkHtmlTagKey
  else
    Result := stkHtmlTagKeyUndef;
end;

function TSynWebEngine.Html_AttrFunc54: TSynWebTokenKind;
begin
  if  Html_AttrKeyComp(20) or
      Html_AttrKeyComp(24) then
    Result := stkHtmlTagKey
  else
    Result := stkHtmlTagKeyUndef;
end;

function TSynWebEngine.Html_AttrFunc55: TSynWebTokenKind;
begin
  if  Html_AttrKeyComp(73) then
    Result := stkHtmlTagKey
  else
    Result := stkHtmlTagKeyUndef;
end;

function TSynWebEngine.Html_AttrFunc56: TSynWebTokenKind;
begin
  if  Html_AttrKeyComp(41) then
    Result := stkHtmlTagKey
  else
    Result := stkHtmlTagKeyUndef;
end;

function TSynWebEngine.Html_AttrFunc57: TSynWebTokenKind;
begin
  if  Html_AttrKeyComp(16) or
      Html_AttrKeyComp(50) then
    Result := stkHtmlTagKey
  else
    Result := stkHtmlTagKeyUndef;
end;

function TSynWebEngine.Html_AttrFunc58: TSynWebTokenKind;
begin
  if  Html_AttrKeyComp(56) or
      Html_AttrKeyComp(101) then
    Result := stkHtmlTagKey
  else
    Result := stkHtmlTagKeyUndef;
end;

function TSynWebEngine.Html_AttrFunc59: TSynWebTokenKind;
begin
  if  Html_AttrKeyComp(105) then
    Result := stkHtmlTagKey
  else
    Result := stkHtmlTagKeyUndef;
end;

function TSynWebEngine.Html_AttrFunc60: TSynWebTokenKind;
begin
  if  Html_AttrKeyComp(49) then
    Result := stkHtmlTagKey
  else
    Result := stkHtmlTagKeyUndef;
end;

function TSynWebEngine.Html_AttrFunc61: TSynWebTokenKind;
begin
  if  Html_AttrKeyComp(82) or
      Html_AttrKeyComp(119) then
    Result := stkHtmlTagKey
  else
    Result := stkHtmlTagKeyUndef;
end;

function TSynWebEngine.Html_AttrFunc62: TSynWebTokenKind;
begin
  if  Html_AttrKeyComp(4) or
      Html_AttrKeyComp(12) then
    Result := stkHtmlTagKey
  else
    Result := stkHtmlTagKeyUndef;
end;

function TSynWebEngine.Html_AttrFunc63: TSynWebTokenKind;
begin
  if  Html_AttrKeyComp(26) then
    Result := stkHtmlTagKey
  else
    Result := stkHtmlTagKeyUndef;
end;

function TSynWebEngine.Html_AttrFunc64: TSynWebTokenKind;
begin
  if  Html_AttrKeyComp(124) then
    Result := stkHtmlTagKey
  else
    Result := stkHtmlTagKeyUndef;
end;

function TSynWebEngine.Html_AttrFunc65: TSynWebTokenKind;
begin
  if  Html_AttrKeyComp(66) or
      Html_AttrKeyComp(118) then
    Result := stkHtmlTagKey
  else
    Result := stkHtmlTagKeyUndef;
end;

function TSynWebEngine.Html_AttrFunc66: TSynWebTokenKind;
begin
  if  Html_AttrKeyComp(8) or
      Html_AttrKeyComp(36) or
      Html_AttrKeyComp(44) or
      Html_AttrKeyComp(69) or
      Html_AttrKeyComp(71) or
      Html_AttrKeyComp(115) or
      Html_AttrKeyComp(116) or
      Html_AttrKeyComp(123) then
    Result := stkHtmlTagKey
  else
    Result := stkHtmlTagKeyUndef;
end;

function TSynWebEngine.Html_AttrFunc67: TSynWebTokenKind;
begin
  if  Html_AttrKeyComp(21) or
      Html_AttrKeyComp(75) or
      Html_AttrKeyComp(76) then
    Result := stkHtmlTagKey
  else
    Result := stkHtmlTagKeyUndef;
end;

function TSynWebEngine.Html_AttrFunc68: TSynWebTokenKind;
begin
  if  Html_AttrKeyComp(59) or
      Html_AttrKeyComp(122) then
    Result := stkHtmlTagKey
  else
    Result := stkHtmlTagKeyUndef;
end;

function TSynWebEngine.Html_AttrFunc69: TSynWebTokenKind;
begin
  if  Html_AttrKeyComp(114) then
    Result := stkHtmlTagKey
  else
    Result := stkHtmlTagKeyUndef;
end;

function TSynWebEngine.Html_AttrFunc71: TSynWebTokenKind;
begin
  if  Html_AttrKeyComp(29) or
      Html_AttrKeyComp(42) or
      Html_AttrKeyComp(52) or
      Html_AttrKeyComp(113) then
    Result := stkHtmlTagKey
  else
    Result := stkHtmlTagKeyUndef;
end;

function TSynWebEngine.Html_AttrFunc72: TSynWebTokenKind;
begin
  if  Html_AttrKeyComp(11) then
    Result := stkHtmlTagKey
  else
    Result := stkHtmlTagKeyUndef;
end;

function TSynWebEngine.Html_AttrFunc73: TSynWebTokenKind;
begin
  if  Html_AttrKeyComp(103) then
    Result := stkHtmlTagKey
  else
    Result := stkHtmlTagKeyUndef;
end;

function TSynWebEngine.Html_AttrFunc74: TSynWebTokenKind;
begin
  if  Html_AttrKeyComp(17) or
      Html_AttrKeyComp(31) then
    Result := stkHtmlTagKey
  else
    Result := stkHtmlTagKeyUndef;
end;

function TSynWebEngine.Html_AttrFunc75: TSynWebTokenKind;
begin
  if  Html_AttrKeyComp(97) or
      Html_AttrKeyComp(99) or
      Html_AttrKeyComp(117) then
    Result := stkHtmlTagKey
  else
    Result := stkHtmlTagKeyUndef;
end;

function TSynWebEngine.Html_AttrFunc77: TSynWebTokenKind;
begin
  if  Html_AttrKeyComp(37) or
      Html_AttrKeyComp(125) then
    Result := stkHtmlTagKey
  else
    Result := stkHtmlTagKeyUndef;
end;

function TSynWebEngine.Html_AttrFunc78: TSynWebTokenKind;
begin
  if  Html_AttrKeyComp(109) then
    Result := stkHtmlTagKey
  else
    Result := stkHtmlTagKeyUndef;
end;

function TSynWebEngine.Html_AttrFunc79: TSynWebTokenKind;
begin
  if  Html_AttrKeyComp(61) or
      Html_AttrKeyComp(112) then
    Result := stkHtmlTagKey
  else
    Result := stkHtmlTagKeyUndef;
end;

function TSynWebEngine.Html_AttrFunc80: TSynWebTokenKind;
begin
  if  Html_AttrKeyComp(28) then
    Result := stkHtmlTagKey
  else
    Result := stkHtmlTagKeyUndef;
end;

function TSynWebEngine.Html_AttrFunc81: TSynWebTokenKind;
begin
  if  Html_AttrKeyComp(92) or
      Html_AttrKeyComp(110) then
    Result := stkHtmlTagKey
  else
    Result := stkHtmlTagKeyUndef;
end;

function TSynWebEngine.Html_AttrFunc82: TSynWebTokenKind;
begin
  if  Html_AttrKeyComp(74) or
      Html_AttrKeyComp(127) then
    Result := stkHtmlTagKey
  else
    Result := stkHtmlTagKeyUndef;
end;

function TSynWebEngine.Html_AttrFunc85: TSynWebTokenKind;
begin
  if  Html_AttrKeyComp(77) or
      Html_AttrKeyComp(108) then
    Result := stkHtmlTagKey
  else
    Result := stkHtmlTagKeyUndef;
end;

function TSynWebEngine.Html_AttrFunc87: TSynWebTokenKind;
begin
  if  Html_AttrKeyComp(13) or
      Html_AttrKeyComp(72) or
      Html_AttrKeyComp(126) then
    Result := stkHtmlTagKey
  else
    Result := stkHtmlTagKeyUndef;
end;

function TSynWebEngine.Html_AttrFunc88: TSynWebTokenKind;
begin
  if  Html_AttrKeyComp(43) then
    Result := stkHtmlTagKey
  else
    Result := stkHtmlTagKeyUndef;
end;

function TSynWebEngine.Html_AttrFunc91: TSynWebTokenKind;
begin
  if  Html_AttrKeyComp(3) or
      Html_AttrKeyComp(30) then
    Result := stkHtmlTagKey
  else
    Result := stkHtmlTagKeyUndef;
end;

function TSynWebEngine.Html_AttrFunc93: TSynWebTokenKind;
begin
  if  Html_AttrKeyComp(25) or
      Html_AttrKeyComp(78) or
      Html_AttrKeyComp(89) then
    Result := stkHtmlTagKey
  else
    Result := stkHtmlTagKeyUndef;
end;

function TSynWebEngine.Html_AttrFunc94: TSynWebTokenKind;
begin
  if  Html_AttrKeyComp(94) then
    Result := stkHtmlTagKey
  else
    Result := stkHtmlTagKeyUndef;
end;

function TSynWebEngine.Html_AttrFunc96: TSynWebTokenKind;
begin
  if  Html_AttrKeyComp(10) or
      Html_AttrKeyComp(88) or
      Html_AttrKeyComp(91) then
    Result := stkHtmlTagKey
  else
    Result := stkHtmlTagKeyUndef;
end;

function TSynWebEngine.Html_AttrFunc98: TSynWebTokenKind;
begin
  if  Html_AttrKeyComp(93) then
    Result := stkHtmlTagKey
  else
    Result := stkHtmlTagKeyUndef;
end;

function TSynWebEngine.Html_AttrFunc101: TSynWebTokenKind;
begin
  if  Html_AttrKeyComp(14) then
    Result := stkHtmlTagKey
  else
    Result := stkHtmlTagKeyUndef;
end;

function TSynWebEngine.Html_AttrFunc102: TSynWebTokenKind;
begin
  if  Html_AttrKeyComp(121) then
    Result := stkHtmlTagKey
  else
    Result := stkHtmlTagKeyUndef;
end;

function TSynWebEngine.Html_AttrFunc103: TSynWebTokenKind;
begin
  if  Html_AttrKeyComp(2) then
    Result := stkHtmlTagKey
  else
    Result := stkHtmlTagKeyUndef;
end;

function TSynWebEngine.Html_AttrFunc104: TSynWebTokenKind;
begin
  if  Html_AttrKeyComp(64) then
    Result := stkHtmlTagKey
  else
    Result := stkHtmlTagKeyUndef;
end;

function TSynWebEngine.Html_AttrFunc105: TSynWebTokenKind;
begin
  if  Html_AttrKeyComp(48) then
    Result := stkHtmlTagKey
  else
    Result := stkHtmlTagKeyUndef;
end;

function TSynWebEngine.Html_AttrFunc106: TSynWebTokenKind;
begin
  if  Html_AttrKeyComp(98) then
    Result := stkHtmlTagKey
  else
    Result := stkHtmlTagKeyUndef;
end;

function TSynWebEngine.Html_AttrFunc107: TSynWebTokenKind;
begin
  if  Html_AttrKeyComp(81) then
    Result := stkHtmlTagKey
  else
    Result := stkHtmlTagKeyUndef;
end;

function TSynWebEngine.Html_AttrFunc108: TSynWebTokenKind;
begin
  if  Html_AttrKeyComp(67) then
    Result := stkHtmlTagKey
  else
    Result := stkHtmlTagKeyUndef;
end;

function TSynWebEngine.Html_AttrFunc109: TSynWebTokenKind;
begin
  if  Html_AttrKeyComp(102) then
    Result := stkHtmlTagKey
  else
    Result := stkHtmlTagKeyUndef;
end;

function TSynWebEngine.Html_AttrFunc110: TSynWebTokenKind;
begin
  if  Html_AttrKeyComp(111) then
    Result := stkHtmlTagKey
  else
    Result := stkHtmlTagKeyUndef;
end;

function TSynWebEngine.Html_AttrFunc111: TSynWebTokenKind;
begin
  if  Html_AttrKeyComp(70) then
    Result := stkHtmlTagKey
  else
    Result := stkHtmlTagKeyUndef;
end;

function TSynWebEngine.Html_AttrFunc113: TSynWebTokenKind;
begin
  if  Html_AttrKeyComp(90) then
    Result := stkHtmlTagKey
  else
    Result := stkHtmlTagKeyUndef;
end;

function TSynWebEngine.Html_AttrFunc114: TSynWebTokenKind;
begin
  if  Html_AttrKeyComp(35) then
    Result := stkHtmlTagKey
  else
    Result := stkHtmlTagKeyUndef;
end;

function TSynWebEngine.Html_AttrFunc119: TSynWebTokenKind;
begin
  if  Html_AttrKeyComp(34) or
      Html_AttrKeyComp(54) or
      Html_AttrKeyComp(62) then
    Result := stkHtmlTagKey
  else
    Result := stkHtmlTagKeyUndef;
end;

function TSynWebEngine.Html_AttrFunc126: TSynWebTokenKind;
begin
  if  Html_AttrKeyComp(63) or
      Html_AttrKeyComp(79) then
    Result := stkHtmlTagKey
  else
    Result := stkHtmlTagKeyUndef;
end;

function TSynWebEngine.Html_AttrFunc127: TSynWebTokenKind;
begin
  if  Html_AttrKeyComp(120) then
    Result := stkHtmlTagKey
  else
    Result := stkHtmlTagKeyUndef;
end;

function TSynWebEngine.Html_AttrFunc139: TSynWebTokenKind;
begin
  if  Html_AttrKeyComp(87) then
    Result := stkHtmlTagKey
  else
    Result := stkHtmlTagKeyUndef;
end;

function TSynWebEngine.Html_AttrFunc147: TSynWebTokenKind;
begin
  if  Html_AttrKeyComp(80) then
    Result := stkHtmlTagKey
  else
    Result := stkHtmlTagKeyUndef;
end;

function TSynWebEngine.Html_AttrFunc157: TSynWebTokenKind;
begin
  if  Html_AttrKeyComp(84) then
    Result := stkHtmlTagKey
  else
    Result := stkHtmlTagKeyUndef;
end;

function TSynWebEngine.Html_AttrFunc158: TSynWebTokenKind;
begin
  if  Html_AttrKeyComp(83) or
      Html_AttrKeyComp(85) then
    Result := stkHtmlTagKey
  else
    Result := stkHtmlTagKeyUndef;
end;

function TSynWebEngine.Html_AttrFunc162: TSynWebTokenKind;
begin
  if  Html_AttrKeyComp(86) then
    Result := stkHtmlTagKey
  else
    Result := stkHtmlTagKeyUndef;
end;
