function TSynWebEngine.Css_ValUndef: TSynWebTokenKind;
begin
  Result:=stkCssValUndef;
end;

function TSynWebEngine.Css_ValFunc26: TSynWebTokenKind;
begin
  if  Css_ValKeyComp(59) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.Css_ValFunc27: TSynWebTokenKind;
begin
  if  Css_ValKeyComp(28) or
      Css_ValKeyComp(125) or
      Css_ValKeyComp(130) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.Css_ValFunc29: TSynWebTokenKind;
begin
  if  Css_ValKeyComp(12) or
      Css_ValKeyComp(43) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.Css_ValFunc31: TSynWebTokenKind;
begin
  if  Css_ValKeyComp(91) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.Css_ValFunc32: TSynWebTokenKind;
begin
  if  Css_ValKeyComp(60) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.Css_ValFunc33: TSynWebTokenKind;
begin
  if  Css_ValKeyComp(16) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.Css_ValFunc35: TSynWebTokenKind;
begin
  if  Css_ValKeyComp(40) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.Css_ValFunc36: TSynWebTokenKind;
begin
  if  Css_ValKeyComp(25) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.Css_ValFunc37: TSynWebTokenKind;
begin
  if  Css_ValKeyComp(112) or
      Css_ValKeyComp(189) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.Css_ValFunc38: TSynWebTokenKind;
begin
  if  Css_ValKeyComp(170) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.Css_ValFunc39: TSynWebTokenKind;
begin
  if  Css_ValKeyComp(79) or
      Css_ValKeyComp(119) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.Css_ValFunc40: TSynWebTokenKind;
begin
  if  Css_ValKeyComp(3) or
      Css_ValKeyComp(15) or
      Css_ValKeyComp(161) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.Css_ValFunc41: TSynWebTokenKind;
begin
  if  Css_ValKeyComp(35) or
      Css_ValKeyComp(57) or
      Css_ValKeyComp(62) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.Css_ValFunc42: TSynWebTokenKind;
begin
  if  Css_ValKeyComp(9) or
      Css_ValKeyComp(50) or
      Css_ValKeyComp(158) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.Css_ValFunc43: TSynWebTokenKind;
begin
  if  Css_ValKeyComp(14) or
      Css_ValKeyComp(72) or
      Css_ValKeyComp(74) or
      Css_ValKeyComp(131) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.Css_ValFunc44: TSynWebTokenKind;
begin
  if  Css_ValKeyComp(58) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.Css_ValFunc45: TSynWebTokenKind;
begin
  if  Css_ValKeyComp(0) or
      Css_ValKeyComp(18) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.Css_ValFunc46: TSynWebTokenKind;
begin
  if  Css_ValKeyComp(48) or
      Css_ValKeyComp(97) or
      Css_ValKeyComp(124) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.Css_ValFunc47: TSynWebTokenKind;
begin
  if  Css_ValKeyComp(36) or
      Css_ValKeyComp(96) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.Css_ValFunc48: TSynWebTokenKind;
begin
  if  Css_ValKeyComp(13) or
      Css_ValKeyComp(51) or
      Css_ValKeyComp(103) or
      Css_ValKeyComp(190) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.Css_ValFunc49: TSynWebTokenKind;
begin
  if  Css_ValKeyComp(46) or
      Css_ValKeyComp(55) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.Css_ValFunc50: TSynWebTokenKind;
begin
  if  Css_ValKeyComp(26) or
      Css_ValKeyComp(83) or
      Css_ValKeyComp(90) or
      Css_ValKeyComp(135) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.Css_ValFunc51: TSynWebTokenKind;
begin
  if  Css_ValKeyComp(7) or
      Css_ValKeyComp(54) or
      Css_ValKeyComp(174) or
      Css_ValKeyComp(175) or
      Css_ValKeyComp(176) or
      Css_ValKeyComp(183) or
      Css_ValKeyComp(188) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.Css_ValFunc52: TSynWebTokenKind;
begin
  if  Css_ValKeyComp(82) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.Css_ValFunc53: TSynWebTokenKind;
begin
  if  Css_ValKeyComp(94) or
      Css_ValKeyComp(163) or
      Css_ValKeyComp(185) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.Css_ValFunc54: TSynWebTokenKind;
begin
  if  Css_ValKeyComp(70) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.Css_ValFunc55: TSynWebTokenKind;
begin
  if  Css_ValKeyComp(61) or
      Css_ValKeyComp(99) or
      Css_ValKeyComp(192) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.Css_ValFunc56: TSynWebTokenKind;
begin
  if  Css_ValKeyComp(17) or
      Css_ValKeyComp(77) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.Css_ValFunc57: TSynWebTokenKind;
begin
  if  Css_ValKeyComp(6) or
      Css_ValKeyComp(10) or
      Css_ValKeyComp(136) or
      Css_ValKeyComp(141) or
      Css_ValKeyComp(147) or
      Css_ValKeyComp(191) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.Css_ValFunc59: TSynWebTokenKind;
begin
  if  Css_ValKeyComp(5) or
      Css_ValKeyComp(42) or
      Css_ValKeyComp(152) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.Css_ValFunc60: TSynWebTokenKind;
begin
  if  Css_ValKeyComp(68) or
      Css_ValKeyComp(114) or
      Css_ValKeyComp(120) or
      Css_ValKeyComp(151) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.Css_ValFunc61: TSynWebTokenKind;
begin
  if  Css_ValKeyComp(73) or
      Css_ValKeyComp(75) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.Css_ValFunc62: TSynWebTokenKind;
begin
  if  Css_ValKeyComp(100) or
      Css_ValKeyComp(132) or
      Css_ValKeyComp(194) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.Css_ValFunc63: TSynWebTokenKind;
begin
  if  Css_ValKeyComp(64) or
      Css_ValKeyComp(111) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.Css_ValFunc65: TSynWebTokenKind;
begin
  if  Css_ValKeyComp(22) or
      Css_ValKeyComp(93) or
      Css_ValKeyComp(127) or
      Css_ValKeyComp(142) or
      Css_ValKeyComp(186) or
      Css_ValKeyComp(195) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.Css_ValFunc67: TSynWebTokenKind;
begin
  if  Css_ValKeyComp(8) or
      Css_ValKeyComp(52) or
      Css_ValKeyComp(67) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.Css_ValFunc68: TSynWebTokenKind;
begin
  if  Css_ValKeyComp(39) or
      Css_ValKeyComp(41) or
      Css_ValKeyComp(44) or
      Css_ValKeyComp(47) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.Css_ValFunc69: TSynWebTokenKind;
begin
  if  Css_ValKeyComp(38) or
      Css_ValKeyComp(49) or
      Css_ValKeyComp(145) or
      Css_ValKeyComp(171) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.Css_ValFunc70: TSynWebTokenKind;
begin
  if  Css_ValKeyComp(128) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.Css_ValFunc71: TSynWebTokenKind;
begin
  if  Css_ValKeyComp(129) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.Css_ValFunc72: TSynWebTokenKind;
begin
  if  Css_ValKeyComp(156) or
      Css_ValKeyComp(196) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.Css_ValFunc73: TSynWebTokenKind;
begin
  if  Css_ValKeyComp(84) or
      Css_ValKeyComp(106) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.Css_ValFunc74: TSynWebTokenKind;
begin
  if  Css_ValKeyComp(193) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.Css_ValFunc75: TSynWebTokenKind;
begin
  if  Css_ValKeyComp(4) or
      Css_ValKeyComp(105) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.Css_ValFunc76: TSynWebTokenKind;
begin
  if  Css_ValKeyComp(53) or
      Css_ValKeyComp(92) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.Css_ValFunc77: TSynWebTokenKind;
begin
  if  Css_ValKeyComp(108) or
      Css_ValKeyComp(148) or
      Css_ValKeyComp(168) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.Css_ValFunc78: TSynWebTokenKind;
begin
  if  Css_ValKeyComp(21) or
      Css_ValKeyComp(121) or
      Css_ValKeyComp(184) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.Css_ValFunc79: TSynWebTokenKind;
begin
  if  Css_ValKeyComp(78) or
      Css_ValKeyComp(138) or
      Css_ValKeyComp(143) or
      Css_ValKeyComp(159) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.Css_ValFunc80: TSynWebTokenKind;
begin
  if  Css_ValKeyComp(133) or
      Css_ValKeyComp(150) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.Css_ValFunc81: TSynWebTokenKind;
begin
  if  Css_ValKeyComp(2) or
      Css_ValKeyComp(110) or
      Css_ValKeyComp(154) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.Css_ValFunc82: TSynWebTokenKind;
begin
  if  Css_ValKeyComp(56) or
      Css_ValKeyComp(101) or
      Css_ValKeyComp(155) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.Css_ValFunc83: TSynWebTokenKind;
begin
  if  Css_ValKeyComp(29) or
      Css_ValKeyComp(63) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.Css_ValFunc84: TSynWebTokenKind;
begin
  if  Css_ValKeyComp(66) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.Css_ValFunc85: TSynWebTokenKind;
begin
  if  Css_ValKeyComp(19) or
      Css_ValKeyComp(139) or
      Css_ValKeyComp(144) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.Css_ValFunc86: TSynWebTokenKind;
begin
  if  Css_ValKeyComp(45) or
      Css_ValKeyComp(187) or
      Css_ValKeyComp(197) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.Css_ValFunc87: TSynWebTokenKind;
begin
  if  Css_ValKeyComp(65) or
      Css_ValKeyComp(107) or
      Css_ValKeyComp(140) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.Css_ValFunc88: TSynWebTokenKind;
begin
  if  Css_ValKeyComp(69) or
      Css_ValKeyComp(81) or
      Css_ValKeyComp(123) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.Css_ValFunc89: TSynWebTokenKind;
begin
  if  Css_ValKeyComp(23) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.Css_ValFunc91: TSynWebTokenKind;
begin
  if  Css_ValKeyComp(95) or
      Css_ValKeyComp(137) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.Css_ValFunc92: TSynWebTokenKind;
begin
  if  Css_ValKeyComp(85) or
      Css_ValKeyComp(126) or
      Css_ValKeyComp(146) or
      Css_ValKeyComp(198) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.Css_ValFunc93: TSynWebTokenKind;
begin
  if  Css_ValKeyComp(116) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.Css_ValFunc95: TSynWebTokenKind;
begin
  if  Css_ValKeyComp(1) or
      Css_ValKeyComp(179) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.Css_ValFunc96: TSynWebTokenKind;
begin
  if  Css_ValKeyComp(31) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.Css_ValFunc97: TSynWebTokenKind;
begin
  if  Css_ValKeyComp(34) or
      Css_ValKeyComp(118) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.Css_ValFunc99: TSynWebTokenKind;
begin
  if  Css_ValKeyComp(162) or
      Css_ValKeyComp(164) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.Css_ValFunc100: TSynWebTokenKind;
begin
  if  Css_ValKeyComp(87) or
      Css_ValKeyComp(109) or
      Css_ValKeyComp(115) or
      Css_ValKeyComp(117) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.Css_ValFunc101: TSynWebTokenKind;
begin
  if  Css_ValKeyComp(11) or
      Css_ValKeyComp(86) or
      Css_ValKeyComp(98) or
      Css_ValKeyComp(153) or
      Css_ValKeyComp(173) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.Css_ValFunc102: TSynWebTokenKind;
begin
  if  Css_ValKeyComp(20) or
      Css_ValKeyComp(157) or
      Css_ValKeyComp(178) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.Css_ValFunc104: TSynWebTokenKind;
begin
  if  Css_ValKeyComp(180) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.Css_ValFunc105: TSynWebTokenKind;
begin
  if  Css_ValKeyComp(160) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.Css_ValFunc108: TSynWebTokenKind;
begin
  if  Css_ValKeyComp(24) or
      Css_ValKeyComp(76) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.Css_ValFunc109: TSynWebTokenKind;
begin
  if  Css_ValKeyComp(113) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.Css_ValFunc110: TSynWebTokenKind;
begin
  if  Css_ValKeyComp(33) or
      Css_ValKeyComp(71) or
      Css_ValKeyComp(88) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.Css_ValFunc113: TSynWebTokenKind;
begin
  if  Css_ValKeyComp(27) or
      Css_ValKeyComp(181) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.Css_ValFunc115: TSynWebTokenKind;
begin
  if  Css_ValKeyComp(32) or
      Css_ValKeyComp(89) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.Css_ValFunc116: TSynWebTokenKind;
begin
  if  Css_ValKeyComp(149) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.Css_ValFunc117: TSynWebTokenKind;
begin
  if  Css_ValKeyComp(122) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.Css_ValFunc118: TSynWebTokenKind;
begin
  if  Css_ValKeyComp(80) or
      Css_ValKeyComp(182) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.Css_ValFunc119: TSynWebTokenKind;
begin
  if  Css_ValKeyComp(104) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.Css_ValFunc120: TSynWebTokenKind;
begin
  if  Css_ValKeyComp(167) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.Css_ValFunc123: TSynWebTokenKind;
begin
  if  Css_ValKeyComp(102) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.Css_ValFunc125: TSynWebTokenKind;
begin
  if  Css_ValKeyComp(37) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.Css_ValFunc127: TSynWebTokenKind;
begin
  if  Css_ValKeyComp(134) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.Css_ValFunc135: TSynWebTokenKind;
begin
  if  Css_ValKeyComp(169) or
      Css_ValKeyComp(172) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.Css_ValFunc146: TSynWebTokenKind;
begin
  if  Css_ValKeyComp(177) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.Css_ValFunc151: TSynWebTokenKind;
begin
  if  Css_ValKeyComp(30) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.Css_ValFunc157: TSynWebTokenKind;
begin
  if  Css_ValKeyComp(165) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;

function TSynWebEngine.Css_ValFunc158: TSynWebTokenKind;
begin
  if  Css_ValKeyComp(166) then
    Result := stkCssVal
  else
    Result := stkCssValUndef;
end;
