function TSynWebEngine.Css_SpecialUndef: Boolean;
begin
  Result:=False;
end;

function TSynWebEngine.Css_SpecialFunc16: Boolean;
begin
  if  Css_SpecialKeyComp(7) or
      Css_SpecialKeyComp(8) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.Css_SpecialFunc18: Boolean;
begin
  if  Css_SpecialKeyComp(9) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.Css_SpecialFunc19: Boolean;
begin
  if  Css_SpecialKeyComp(33) or
      Css_SpecialKeyComp(40) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.Css_SpecialFunc23: Boolean;
begin
  if  Css_SpecialKeyComp(24) or
      Css_SpecialKeyComp(38) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.Css_SpecialFunc25: Boolean;
begin
  if  Css_SpecialKeyComp(2) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.Css_SpecialFunc26: Boolean;
begin
  if  Css_SpecialKeyComp(30) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.Css_SpecialFunc29: Boolean;
begin
  if  Css_SpecialKeyComp(11) or
      Css_SpecialKeyComp(32) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.Css_SpecialFunc30: Boolean;
begin
  if  Css_SpecialKeyComp(18) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.Css_SpecialFunc32: Boolean;
begin
  if  Css_SpecialKeyComp(29) or
      Css_SpecialKeyComp(31) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.Css_SpecialFunc34: Boolean;
begin
  if  Css_SpecialKeyComp(21) or
      Css_SpecialKeyComp(26) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.Css_SpecialFunc36: Boolean;
begin
  if  Css_SpecialKeyComp(36) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.Css_SpecialFunc40: Boolean;
begin
  if  Css_SpecialKeyComp(37) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.Css_SpecialFunc42: Boolean;
begin
  if  Css_SpecialKeyComp(44) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.Css_SpecialFunc43: Boolean;
begin
  if  Css_SpecialKeyComp(27) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.Css_SpecialFunc45: Boolean;
begin
  if  Css_SpecialKeyComp(25) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.Css_SpecialFunc46: Boolean;
begin
  if  Css_SpecialKeyComp(28) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.Css_SpecialFunc50: Boolean;
begin
  if  Css_SpecialKeyComp(1) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.Css_SpecialFunc51: Boolean;
begin
  if  Css_SpecialKeyComp(4) or
      Css_SpecialKeyComp(17) or
      Css_SpecialKeyComp(45) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.Css_SpecialFunc56: Boolean;
begin
  if  Css_SpecialKeyComp(19) or
      Css_SpecialKeyComp(42) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.Css_SpecialFunc57: Boolean;
begin
  if  Css_SpecialKeyComp(3) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.Css_SpecialFunc59: Boolean;
begin
  if  Css_SpecialKeyComp(5) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.Css_SpecialFunc60: Boolean;
begin
  if  Css_SpecialKeyComp(0) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.Css_SpecialFunc62: Boolean;
begin
  if  Css_SpecialKeyComp(39) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.Css_SpecialFunc64: Boolean;
begin
  if  Css_SpecialKeyComp(16) or
      Css_SpecialKeyComp(41) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.Css_SpecialFunc65: Boolean;
begin
  if  Css_SpecialKeyComp(43) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.Css_SpecialFunc68: Boolean;
begin
  if  Css_SpecialKeyComp(20) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.Css_SpecialFunc72: Boolean;
begin
  if  Css_SpecialKeyComp(12) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.Css_SpecialFunc74: Boolean;
begin
  if  Css_SpecialKeyComp(6) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.Css_SpecialFunc77: Boolean;
begin
  if  Css_SpecialKeyComp(34) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.Css_SpecialFunc82: Boolean;
begin
  if  Css_SpecialKeyComp(10) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.Css_SpecialFunc88: Boolean;
begin
  if  Css_SpecialKeyComp(46) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.Css_SpecialFunc89: Boolean;
begin
  if  Css_SpecialKeyComp(13) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.Css_SpecialFunc91: Boolean;
begin
  if  Css_SpecialKeyComp(22) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.Css_SpecialFunc93: Boolean;
begin
  if  Css_SpecialKeyComp(15) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.Css_SpecialFunc125: Boolean;
begin
  if  Css_SpecialKeyComp(35) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.Css_SpecialFunc126: Boolean;
begin
  if  Css_SpecialKeyComp(23) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.Css_SpecialFunc133: Boolean;
begin
  if  Css_SpecialKeyComp(14) then
    Result := True
  else
    Result := False;
end;
