function TSynWebEngine.CSS_SpecialUndef: Boolean;
begin
  Result:=False;
end;

function TSynWebEngine.CSS_SpecialFunc16: Boolean;
begin
  if  CSS_SpecialKeyComp(7) or
      CSS_SpecialKeyComp(8) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.CSS_SpecialFunc18: Boolean;
begin
  if  CSS_SpecialKeyComp(9) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.CSS_SpecialFunc19: Boolean;
begin
  if  CSS_SpecialKeyComp(33) or
      CSS_SpecialKeyComp(40) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.CSS_SpecialFunc23: Boolean;
begin
  if  CSS_SpecialKeyComp(24) or
      CSS_SpecialKeyComp(38) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.CSS_SpecialFunc25: Boolean;
begin
  if  CSS_SpecialKeyComp(2) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.CSS_SpecialFunc26: Boolean;
begin
  if  CSS_SpecialKeyComp(30) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.CSS_SpecialFunc29: Boolean;
begin
  if  CSS_SpecialKeyComp(11) or
      CSS_SpecialKeyComp(32) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.CSS_SpecialFunc30: Boolean;
begin
  if  CSS_SpecialKeyComp(18) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.CSS_SpecialFunc32: Boolean;
begin
  if  CSS_SpecialKeyComp(29) or
      CSS_SpecialKeyComp(31) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.CSS_SpecialFunc34: Boolean;
begin
  if  CSS_SpecialKeyComp(21) or
      CSS_SpecialKeyComp(26) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.CSS_SpecialFunc36: Boolean;
begin
  if  CSS_SpecialKeyComp(36) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.CSS_SpecialFunc40: Boolean;
begin
  if  CSS_SpecialKeyComp(37) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.CSS_SpecialFunc42: Boolean;
begin
  if  CSS_SpecialKeyComp(44) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.CSS_SpecialFunc43: Boolean;
begin
  if  CSS_SpecialKeyComp(27) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.CSS_SpecialFunc45: Boolean;
begin
  if  CSS_SpecialKeyComp(25) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.CSS_SpecialFunc46: Boolean;
begin
  if  CSS_SpecialKeyComp(28) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.CSS_SpecialFunc50: Boolean;
begin
  if  CSS_SpecialKeyComp(1) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.CSS_SpecialFunc51: Boolean;
begin
  if  CSS_SpecialKeyComp(4) or
      CSS_SpecialKeyComp(17) or
      CSS_SpecialKeyComp(45) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.CSS_SpecialFunc56: Boolean;
begin
  if  CSS_SpecialKeyComp(19) or
      CSS_SpecialKeyComp(42) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.CSS_SpecialFunc57: Boolean;
begin
  if  CSS_SpecialKeyComp(3) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.CSS_SpecialFunc59: Boolean;
begin
  if  CSS_SpecialKeyComp(5) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.CSS_SpecialFunc60: Boolean;
begin
  if  CSS_SpecialKeyComp(0) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.CSS_SpecialFunc62: Boolean;
begin
  if  CSS_SpecialKeyComp(39) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.CSS_SpecialFunc64: Boolean;
begin
  if  CSS_SpecialKeyComp(16) or
      CSS_SpecialKeyComp(41) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.CSS_SpecialFunc65: Boolean;
begin
  if  CSS_SpecialKeyComp(43) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.CSS_SpecialFunc68: Boolean;
begin
  if  CSS_SpecialKeyComp(20) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.CSS_SpecialFunc72: Boolean;
begin
  if  CSS_SpecialKeyComp(12) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.CSS_SpecialFunc74: Boolean;
begin
  if  CSS_SpecialKeyComp(6) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.CSS_SpecialFunc77: Boolean;
begin
  if  CSS_SpecialKeyComp(34) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.CSS_SpecialFunc82: Boolean;
begin
  if  CSS_SpecialKeyComp(10) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.CSS_SpecialFunc88: Boolean;
begin
  if  CSS_SpecialKeyComp(46) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.CSS_SpecialFunc89: Boolean;
begin
  if  CSS_SpecialKeyComp(13) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.CSS_SpecialFunc91: Boolean;
begin
  if  CSS_SpecialKeyComp(22) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.CSS_SpecialFunc93: Boolean;
begin
  if  CSS_SpecialKeyComp(15) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.CSS_SpecialFunc125: Boolean;
begin
  if  CSS_SpecialKeyComp(35) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.CSS_SpecialFunc126: Boolean;
begin
  if  CSS_SpecialKeyComp(23) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.CSS_SpecialFunc133: Boolean;
begin
  if  CSS_SpecialKeyComp(14) then
    Result := True
  else
    Result := False;
end;
