function TSynWebEngine.Html_SpecialUndef: Boolean;
begin
  Result:=False;
end;

function TSynWebEngine.Html_SpecialFunc12: Boolean;
begin
  if  Html_SpecialKeyComp(79) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.Html_SpecialFunc16: Boolean;
begin
  if  Html_SpecialKeyComp(46) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.Html_SpecialFunc17: Boolean;
begin
  if  Html_SpecialKeyComp(111) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.Html_SpecialFunc19: Boolean;
begin
  if  Html_SpecialKeyComp(13) or
      Html_SpecialKeyComp(129) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.Html_SpecialFunc20: Boolean;
begin
  if  Html_SpecialKeyComp(28) or
      Html_SpecialKeyComp(33) or
      Html_SpecialKeyComp(34) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.Html_SpecialFunc22: Boolean;
begin
  if  Html_SpecialKeyComp(14) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.Html_SpecialFunc23: Boolean;
begin
  if  Html_SpecialKeyComp(130) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.Html_SpecialFunc25: Boolean;
begin
  if  Html_SpecialKeyComp(168) or
      Html_SpecialKeyComp(169) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.Html_SpecialFunc26: Boolean;
begin
  if  Html_SpecialKeyComp(63) or
      Html_SpecialKeyComp(64) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.Html_SpecialFunc27: Boolean;
begin
  if  Html_SpecialKeyComp(80) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.Html_SpecialFunc28: Boolean;
begin
  if  Html_SpecialKeyComp(24) or
      Html_SpecialKeyComp(25) or
      Html_SpecialKeyComp(73) or
      Html_SpecialKeyComp(74) or
      Html_SpecialKeyComp(75) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.Html_SpecialFunc30: Boolean;
begin
  if  Html_SpecialKeyComp(12) or
      Html_SpecialKeyComp(126) or
      Html_SpecialKeyComp(188) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.Html_SpecialFunc32: Boolean;
begin
  if  Html_SpecialKeyComp(118) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.Html_SpecialFunc33: Boolean;
begin
  if  Html_SpecialKeyComp(31) or
      Html_SpecialKeyComp(35) or
      Html_SpecialKeyComp(65) or
      Html_SpecialKeyComp(66) or
      Html_SpecialKeyComp(103) or
      Html_SpecialKeyComp(104) or
      Html_SpecialKeyComp(152) or
      Html_SpecialKeyComp(166) or
      Html_SpecialKeyComp(167) or
      Html_SpecialKeyComp(242) or
      Html_SpecialKeyComp(243) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.Html_SpecialFunc34: Boolean;
begin
  if  Html_SpecialKeyComp(2) or
      Html_SpecialKeyComp(3) or
      Html_SpecialKeyComp(5) or
      Html_SpecialKeyComp(6) or
      Html_SpecialKeyComp(105) or
      Html_SpecialKeyComp(124) or
      Html_SpecialKeyComp(125) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.Html_SpecialFunc35: Boolean;
begin
  if  Html_SpecialKeyComp(77) or
      Html_SpecialKeyComp(78) or
      Html_SpecialKeyComp(92) or
      Html_SpecialKeyComp(119) or
      Html_SpecialKeyComp(136) or
      Html_SpecialKeyComp(137) or
      Html_SpecialKeyComp(180) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.Html_SpecialFunc36: Boolean;
begin
  if  Html_SpecialKeyComp(29) or
      Html_SpecialKeyComp(30) or
      Html_SpecialKeyComp(162) or
      Html_SpecialKeyComp(187) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.Html_SpecialFunc38: Boolean;
begin
  if  Html_SpecialKeyComp(10) or
      Html_SpecialKeyComp(11) or
      Html_SpecialKeyComp(53) or
      Html_SpecialKeyComp(54) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.Html_SpecialFunc39: Boolean;
begin
  if  Html_SpecialKeyComp(37) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.Html_SpecialFunc40: Boolean;
begin
  if  Html_SpecialKeyComp(40) or
      Html_SpecialKeyComp(181) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.Html_SpecialFunc41: Boolean;
begin
  if  Html_SpecialKeyComp(44) or
      Html_SpecialKeyComp(45) or
      Html_SpecialKeyComp(71) or
      Html_SpecialKeyComp(109) or
      Html_SpecialKeyComp(147) or
      Html_SpecialKeyComp(148) or
      Html_SpecialKeyComp(190) or
      Html_SpecialKeyComp(191) or
      Html_SpecialKeyComp(204) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.Html_SpecialFunc42: Boolean;
begin
  if  Html_SpecialKeyComp(32) or
      Html_SpecialKeyComp(42) or
      Html_SpecialKeyComp(43) or
      Html_SpecialKeyComp(47) or
      Html_SpecialKeyComp(48) or
      Html_SpecialKeyComp(87) or
      Html_SpecialKeyComp(88) or
      Html_SpecialKeyComp(206) or
      Html_SpecialKeyComp(215) or
      Html_SpecialKeyComp(216) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.Html_SpecialFunc43: Boolean;
begin
  if  Html_SpecialKeyComp(94) or
      Html_SpecialKeyComp(115) or
      Html_SpecialKeyComp(153) or
      Html_SpecialKeyComp(192) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.Html_SpecialFunc44: Boolean;
begin
  if  Html_SpecialKeyComp(177) or
      Html_SpecialKeyComp(178) or
      Html_SpecialKeyComp(246) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.Html_SpecialFunc45: Boolean;
begin
  if  Html_SpecialKeyComp(81) or
      Html_SpecialKeyComp(82) or
      Html_SpecialKeyComp(95) or
      Html_SpecialKeyComp(96) or
      Html_SpecialKeyComp(101) or
      Html_SpecialKeyComp(102) or
      Html_SpecialKeyComp(120) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.Html_SpecialFunc46: Boolean;
begin
  if  Html_SpecialKeyComp(49) or
      Html_SpecialKeyComp(128) or
      Html_SpecialKeyComp(235) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.Html_SpecialFunc47: Boolean;
begin
  if  Html_SpecialKeyComp(21) or
      Html_SpecialKeyComp(22) or
      Html_SpecialKeyComp(27) or
      Html_SpecialKeyComp(170) or
      Html_SpecialKeyComp(185) or
      Html_SpecialKeyComp(199) or
      Html_SpecialKeyComp(207) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.Html_SpecialFunc48: Boolean;
begin
  if  Html_SpecialKeyComp(140) or
      Html_SpecialKeyComp(141) or
      Html_SpecialKeyComp(142) or
      Html_SpecialKeyComp(143) or
      Html_SpecialKeyComp(226) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.Html_SpecialFunc49: Boolean;
begin
  if  Html_SpecialKeyComp(16) or
      Html_SpecialKeyComp(17) or
      Html_SpecialKeyComp(107) or
      Html_SpecialKeyComp(108) or
      Html_SpecialKeyComp(131) or
      Html_SpecialKeyComp(201) or
      Html_SpecialKeyComp(202) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.Html_SpecialFunc50: Boolean;
begin
  if  Html_SpecialKeyComp(4) or
      Html_SpecialKeyComp(154) or
      Html_SpecialKeyComp(224) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.Html_SpecialFunc51: Boolean;
begin
  if  Html_SpecialKeyComp(0) or
      Html_SpecialKeyComp(1) or
      Html_SpecialKeyComp(15) or
      Html_SpecialKeyComp(19) or
      Html_SpecialKeyComp(20) or
      Html_SpecialKeyComp(67) or
      Html_SpecialKeyComp(68) or
      Html_SpecialKeyComp(98) or
      Html_SpecialKeyComp(127) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.Html_SpecialFunc52: Boolean;
begin
  if  Html_SpecialKeyComp(93) or
      Html_SpecialKeyComp(200) or
      Html_SpecialKeyComp(249) or
      Html_SpecialKeyComp(250) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.Html_SpecialFunc53: Boolean;
begin
  if  Html_SpecialKeyComp(50) or
      Html_SpecialKeyComp(58) or
      Html_SpecialKeyComp(89) or
      Html_SpecialKeyComp(114) or
      Html_SpecialKeyComp(175) or
      Html_SpecialKeyComp(208) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.Html_SpecialFunc54: Boolean;
begin
  if  Html_SpecialKeyComp(7) or
      Html_SpecialKeyComp(8) or
      Html_SpecialKeyComp(59) or
      Html_SpecialKeyComp(218) or
      Html_SpecialKeyComp(219) or
      Html_SpecialKeyComp(231) or
      Html_SpecialKeyComp(232) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.Html_SpecialFunc55: Boolean;
begin
  if  Html_SpecialKeyComp(51) or
      Html_SpecialKeyComp(52) or
      Html_SpecialKeyComp(99) or
      Html_SpecialKeyComp(100) or
      Html_SpecialKeyComp(146) or
      Html_SpecialKeyComp(163) or
      Html_SpecialKeyComp(165) or
      Html_SpecialKeyComp(183) or
      Html_SpecialKeyComp(184) or
      Html_SpecialKeyComp(203) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.Html_SpecialFunc56: Boolean;
begin
  if  Html_SpecialKeyComp(76) or
      Html_SpecialKeyComp(133) or
      Html_SpecialKeyComp(209) or
      Html_SpecialKeyComp(210) or
      Html_SpecialKeyComp(211) or
      Html_SpecialKeyComp(212) or
      Html_SpecialKeyComp(217) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.Html_SpecialFunc57: Boolean;
begin
  if  Html_SpecialKeyComp(36) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.Html_SpecialFunc58: Boolean;
begin
  if  Html_SpecialKeyComp(39) or
      Html_SpecialKeyComp(55) or
      Html_SpecialKeyComp(56) or
      Html_SpecialKeyComp(121) or
      Html_SpecialKeyComp(198) or
      Html_SpecialKeyComp(229) or
      Html_SpecialKeyComp(230) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.Html_SpecialFunc59: Boolean;
begin
  if  Html_SpecialKeyComp(23) or
      Html_SpecialKeyComp(38) or
      Html_SpecialKeyComp(69) or
      Html_SpecialKeyComp(85) or
      Html_SpecialKeyComp(86) or
      Html_SpecialKeyComp(251) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.Html_SpecialFunc61: Boolean;
begin
  if  Html_SpecialKeyComp(160) or
      Html_SpecialKeyComp(161) or
      Html_SpecialKeyComp(173) or
      Html_SpecialKeyComp(174) or
      Html_SpecialKeyComp(213) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.Html_SpecialFunc62: Boolean;
begin
  if  Html_SpecialKeyComp(84) or
      Html_SpecialKeyComp(90) or
      Html_SpecialKeyComp(91) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.Html_SpecialFunc63: Boolean;
begin
  if  Html_SpecialKeyComp(26) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.Html_SpecialFunc64: Boolean;
begin
  if  Html_SpecialKeyComp(72) or
      Html_SpecialKeyComp(134) or
      Html_SpecialKeyComp(135) or
      Html_SpecialKeyComp(205) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.Html_SpecialFunc65: Boolean;
begin
  if  Html_SpecialKeyComp(122) or
      Html_SpecialKeyComp(138) or
      Html_SpecialKeyComp(139) or
      Html_SpecialKeyComp(157) or
      Html_SpecialKeyComp(158) or
      Html_SpecialKeyComp(176) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.Html_SpecialFunc66: Boolean;
begin
  if  Html_SpecialKeyComp(106) or
      Html_SpecialKeyComp(225) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.Html_SpecialFunc67: Boolean;
begin
  if  Html_SpecialKeyComp(239) or
      Html_SpecialKeyComp(240) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.Html_SpecialFunc68: Boolean;
begin
  if  Html_SpecialKeyComp(144) or
      Html_SpecialKeyComp(145) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.Html_SpecialFunc69: Boolean;
begin
  if  Html_SpecialKeyComp(110) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.Html_SpecialFunc70: Boolean;
begin
  if  Html_SpecialKeyComp(172) or
      Html_SpecialKeyComp(196) or
      Html_SpecialKeyComp(197) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.Html_SpecialFunc71: Boolean;
begin
  if  Html_SpecialKeyComp(83) or
      Html_SpecialKeyComp(227) or
      Html_SpecialKeyComp(228) or
      Html_SpecialKeyComp(247) or
      Html_SpecialKeyComp(248) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.Html_SpecialFunc72: Boolean;
begin
  if  Html_SpecialKeyComp(132) or
      Html_SpecialKeyComp(182) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.Html_SpecialFunc73: Boolean;
begin
  if  Html_SpecialKeyComp(164) or
      Html_SpecialKeyComp(179) or
      Html_SpecialKeyComp(214) or
      Html_SpecialKeyComp(236) or
      Html_SpecialKeyComp(252) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.Html_SpecialFunc74: Boolean;
begin
  if  Html_SpecialKeyComp(18) or
      Html_SpecialKeyComp(62) or
      Html_SpecialKeyComp(155) or
      Html_SpecialKeyComp(156) or
      Html_SpecialKeyComp(195) or
      Html_SpecialKeyComp(233) or
      Html_SpecialKeyComp(234) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.Html_SpecialFunc75: Boolean;
begin
  if  Html_SpecialKeyComp(186) or
      Html_SpecialKeyComp(222) or
      Html_SpecialKeyComp(223) or
      Html_SpecialKeyComp(244) or
      Html_SpecialKeyComp(245) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.Html_SpecialFunc76: Boolean;
begin
  if  Html_SpecialKeyComp(123) or
      Html_SpecialKeyComp(241) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.Html_SpecialFunc77: Boolean;
begin
  if  Html_SpecialKeyComp(70) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.Html_SpecialFunc78: Boolean;
begin
  if  Html_SpecialKeyComp(112) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.Html_SpecialFunc79: Boolean;
begin
  if  Html_SpecialKeyComp(41) or
      Html_SpecialKeyComp(57) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.Html_SpecialFunc81: Boolean;
begin
  if  Html_SpecialKeyComp(9) or
      Html_SpecialKeyComp(159) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.Html_SpecialFunc83: Boolean;
begin
  if  Html_SpecialKeyComp(151) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.Html_SpecialFunc84: Boolean;
begin
  if  Html_SpecialKeyComp(117) or
      Html_SpecialKeyComp(189) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.Html_SpecialFunc85: Boolean;
begin
  if  Html_SpecialKeyComp(116) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.Html_SpecialFunc86: Boolean;
begin
  if  Html_SpecialKeyComp(221) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.Html_SpecialFunc87: Boolean;
begin
  if  Html_SpecialKeyComp(149) or
      Html_SpecialKeyComp(150) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.Html_SpecialFunc90: Boolean;
begin
  if  Html_SpecialKeyComp(60) or
      Html_SpecialKeyComp(61) or
      Html_SpecialKeyComp(113) or
      Html_SpecialKeyComp(194) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.Html_SpecialFunc91: Boolean;
begin
  if  Html_SpecialKeyComp(97) or
      Html_SpecialKeyComp(193) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.Html_SpecialFunc95: Boolean;
begin
  if  Html_SpecialKeyComp(171) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.Html_SpecialFunc106: Boolean;
begin
  if  Html_SpecialKeyComp(237) or
      Html_SpecialKeyComp(238) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.Html_SpecialFunc111: Boolean;
begin
  if  Html_SpecialKeyComp(220) then
    Result := True
  else
    Result := False;
end;
