function TSynWebEngine.CssPropUndef: TSynWebTokenKind;
begin
  Result:=stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc28: TSynWebTokenKind;
begin
  if  CssPropKeyComp(23) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc29: TSynWebTokenKind;
begin
  if  CssPropKeyComp(86) or
      CssPropKeyComp(212) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc35: TSynWebTokenKind;
begin
  if  CssPropKeyComp(101) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc39: TSynWebTokenKind;
begin
  if  CssPropKeyComp(69) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc40: TSynWebTokenKind;
begin
  if  CssPropKeyComp(70) or
      CssPropKeyComp(247) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc41: TSynWebTokenKind;
begin
  if  CssPropKeyComp(153) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc43: TSynWebTokenKind;
begin
  if  CssPropKeyComp(158) or
      CssPropKeyComp(175) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc51: TSynWebTokenKind;
begin
  if  CssPropKeyComp(279) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc52: TSynWebTokenKind;
begin
  if  CssPropKeyComp(85) or
      CssPropKeyComp(242) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc54: TSynWebTokenKind;
begin
  if  CssPropKeyComp(107) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc55: TSynWebTokenKind;
begin
  if  CssPropKeyComp(109) or
      CssPropKeyComp(207) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc56: TSynWebTokenKind;
begin
  if  CssPropKeyComp(223) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc57: TSynWebTokenKind;
begin
  if  CssPropKeyComp(142) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc59: TSynWebTokenKind;
begin
  if  CssPropKeyComp(241) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc62: TSynWebTokenKind;
begin
  if  CssPropKeyComp(28) or
      CssPropKeyComp(170) or
      CssPropKeyComp(178) or
      CssPropKeyComp(217) or
      CssPropKeyComp(230) or
      CssPropKeyComp(234) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc63: TSynWebTokenKind;
begin
  if  CssPropKeyComp(71) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc64: TSynWebTokenKind;
begin
  if  CssPropKeyComp(305) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc71: TSynWebTokenKind;
begin
  if  CssPropKeyComp(251) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc80: TSynWebTokenKind;
begin
  if  CssPropKeyComp(10) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc82: TSynWebTokenKind;
begin
  if  CssPropKeyComp(229) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc85: TSynWebTokenKind;
begin
  if  CssPropKeyComp(61) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc86: TSynWebTokenKind;
begin
  if  CssPropKeyComp(91) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc88: TSynWebTokenKind;
begin
  if  CssPropKeyComp(301) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc89: TSynWebTokenKind;
begin
  if  CssPropKeyComp(196) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc91: TSynWebTokenKind;
begin
  if  CssPropKeyComp(82) or
      CssPropKeyComp(197) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc93: TSynWebTokenKind;
begin
  if  CssPropKeyComp(304) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc94: TSynWebTokenKind;
begin
  if  CssPropKeyComp(89) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc95: TSynWebTokenKind;
begin
  if  CssPropKeyComp(152) or
      CssPropKeyComp(222) or
      CssPropKeyComp(233) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc96: TSynWebTokenKind;
begin
  if  CssPropKeyComp(2) or
      CssPropKeyComp(13) or
      CssPropKeyComp(198) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc97: TSynWebTokenKind;
begin
  if  CssPropKeyComp(79) or
      CssPropKeyComp(90) or
      CssPropKeyComp(228) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc98: TSynWebTokenKind;
begin
  if  CssPropKeyComp(11) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc100: TSynWebTokenKind;
begin
  if  CssPropKeyComp(248) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc103: TSynWebTokenKind;
begin
  if  CssPropKeyComp(99) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc108: TSynWebTokenKind;
begin
  if  CssPropKeyComp(126) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc112: TSynWebTokenKind;
begin
  if  CssPropKeyComp(193) or
      CssPropKeyComp(235) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc115: TSynWebTokenKind;
begin
  if  CssPropKeyComp(160) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc116: TSynWebTokenKind;
begin
  if  CssPropKeyComp(106) or
      CssPropKeyComp(203) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc117: TSynWebTokenKind;
begin
  if  CssPropKeyComp(87) or
      CssPropKeyComp(226) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc118: TSynWebTokenKind;
begin
  if  CssPropKeyComp(88) or
      CssPropKeyComp(191) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc120: TSynWebTokenKind;
begin
  if  CssPropKeyComp(310) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc124: TSynWebTokenKind;
begin
  if  CssPropKeyComp(280) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc125: TSynWebTokenKind;
begin
  if  CssPropKeyComp(65) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc126: TSynWebTokenKind;
begin
  if  CssPropKeyComp(66) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc128: TSynWebTokenKind;
begin
  if  CssPropKeyComp(103) or
      CssPropKeyComp(188) or
      CssPropKeyComp(194) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc130: TSynWebTokenKind;
begin
  if  CssPropKeyComp(293) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc131: TSynWebTokenKind;
begin
  if  CssPropKeyComp(176) or
      CssPropKeyComp(186) or
      CssPropKeyComp(189) or
      CssPropKeyComp(190) or
      CssPropKeyComp(243) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc132: TSynWebTokenKind;
begin
  if  CssPropKeyComp(133) or
      CssPropKeyComp(135) or
      CssPropKeyComp(177) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc133: TSynWebTokenKind;
begin
  if  CssPropKeyComp(184) or
      CssPropKeyComp(288) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc135: TSynWebTokenKind;
begin
  if  CssPropKeyComp(37) or
      CssPropKeyComp(67) or
      CssPropKeyComp(161) or
      CssPropKeyComp(306) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc136: TSynWebTokenKind;
begin
  if  CssPropKeyComp(209) or
      CssPropKeyComp(292) or
      CssPropKeyComp(298) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc137: TSynWebTokenKind;
begin
  if  CssPropKeyComp(134) or
      CssPropKeyComp(192) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc138: TSynWebTokenKind;
begin
  if  CssPropKeyComp(187) or
      CssPropKeyComp(220) or
      CssPropKeyComp(246) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc139: TSynWebTokenKind;
begin
  if  CssPropKeyComp(224) or
      CssPropKeyComp(283) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc140: TSynWebTokenKind;
begin
  if  CssPropKeyComp(74) or
      CssPropKeyComp(185) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc142: TSynWebTokenKind;
begin
  if  CssPropKeyComp(252) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc143: TSynWebTokenKind;
begin
  if  CssPropKeyComp(43) or
      CssPropKeyComp(172) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc144: TSynWebTokenKind;
begin
  if  CssPropKeyComp(211) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc145: TSynWebTokenKind;
begin
  if  CssPropKeyComp(105) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc147: TSynWebTokenKind;
begin
  if  CssPropKeyComp(216) or
      CssPropKeyComp(237) or
      CssPropKeyComp(302) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc148: TSynWebTokenKind;
begin
  if  CssPropKeyComp(296) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc149: TSynWebTokenKind;
begin
  if  CssPropKeyComp(63) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc150: TSynWebTokenKind;
begin
  if  CssPropKeyComp(218) or
      CssPropKeyComp(231) or
      CssPropKeyComp(255) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc151: TSynWebTokenKind;
begin
  if  CssPropKeyComp(54) or
      CssPropKeyComp(137) or
      CssPropKeyComp(174) or
      CssPropKeyComp(219) or
      CssPropKeyComp(232) or
      CssPropKeyComp(253) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc152: TSynWebTokenKind;
begin
  if  CssPropKeyComp(114) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc153: TSynWebTokenKind;
begin
  if  CssPropKeyComp(68) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc154: TSynWebTokenKind;
begin
  if  CssPropKeyComp(128) or
      CssPropKeyComp(240) or
      CssPropKeyComp(289) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc155: TSynWebTokenKind;
begin
  if  CssPropKeyComp(73) or
      CssPropKeyComp(210) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc156: TSynWebTokenKind;
begin
  if  CssPropKeyComp(24) or
      CssPropKeyComp(308) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc158: TSynWebTokenKind;
begin
  if  CssPropKeyComp(295) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc159: TSynWebTokenKind;
begin
  if  CssPropKeyComp(110) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc162: TSynWebTokenKind;
begin
  if  CssPropKeyComp(48) or
      CssPropKeyComp(162) or
      CssPropKeyComp(173) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc163: TSynWebTokenKind;
begin
  if  CssPropKeyComp(36) or
      CssPropKeyComp(64) or
      CssPropKeyComp(108) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc164: TSynWebTokenKind;
begin
  if  CssPropKeyComp(60) or
      CssPropKeyComp(269) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc165: TSynWebTokenKind;
begin
  if  CssPropKeyComp(125) or
      CssPropKeyComp(225) or
      CssPropKeyComp(278) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc166: TSynWebTokenKind;
begin
  if  CssPropKeyComp(80) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc167: TSynWebTokenKind;
begin
  if  CssPropKeyComp(7) or
      CssPropKeyComp(22) or
      CssPropKeyComp(155) or
      CssPropKeyComp(182) or
      CssPropKeyComp(276) or
      CssPropKeyComp(307) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc168: TSynWebTokenKind;
begin
  if  CssPropKeyComp(100) or
      CssPropKeyComp(140) or
      CssPropKeyComp(259) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc169: TSynWebTokenKind;
begin
  if  CssPropKeyComp(17) or
      CssPropKeyComp(52) or
      CssPropKeyComp(249) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc171: TSynWebTokenKind;
begin
  if  CssPropKeyComp(112) or
      CssPropKeyComp(290) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc172: TSynWebTokenKind;
begin
  if  CssPropKeyComp(47) or
      CssPropKeyComp(75) or
      CssPropKeyComp(250) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc173: TSynWebTokenKind;
begin
  if  CssPropKeyComp(130) or
      CssPropKeyComp(270) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc174: TSynWebTokenKind;
begin
  if  CssPropKeyComp(15) or
      CssPropKeyComp(117) or
      CssPropKeyComp(244) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc175: TSynWebTokenKind;
begin
  if  CssPropKeyComp(309) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc176: TSynWebTokenKind;
begin
  if  CssPropKeyComp(180) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc177: TSynWebTokenKind;
begin
  if  CssPropKeyComp(274) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc178: TSynWebTokenKind;
begin
  if  CssPropKeyComp(119) or
      CssPropKeyComp(205) or
      CssPropKeyComp(208) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc179: TSynWebTokenKind;
begin
  if  CssPropKeyComp(166) or
      CssPropKeyComp(206) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc180: TSynWebTokenKind;
begin
  if  CssPropKeyComp(25) or
      CssPropKeyComp(81) or
      CssPropKeyComp(300) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc181: TSynWebTokenKind;
begin
  if  CssPropKeyComp(3) or
      CssPropKeyComp(53) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc182: TSynWebTokenKind;
begin
  if  CssPropKeyComp(104) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc183: TSynWebTokenKind;
begin
  if  CssPropKeyComp(35) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc185: TSynWebTokenKind;
begin
  if  CssPropKeyComp(29) or
      CssPropKeyComp(171) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc186: TSynWebTokenKind;
begin
  if  CssPropKeyComp(116) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc187: TSynWebTokenKind;
begin
  if  CssPropKeyComp(159) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc189: TSynWebTokenKind;
begin
  if  CssPropKeyComp(26) or
      CssPropKeyComp(72) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc190: TSynWebTokenKind;
begin
  if  CssPropKeyComp(102) or
      CssPropKeyComp(143) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc191: TSynWebTokenKind;
begin
  if  CssPropKeyComp(144) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc192: TSynWebTokenKind;
begin
  if  CssPropKeyComp(213) or
      CssPropKeyComp(299) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc193: TSynWebTokenKind;
begin
  if  CssPropKeyComp(21) or
      CssPropKeyComp(214) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc194: TSynWebTokenKind;
begin
  if  CssPropKeyComp(238) or
      CssPropKeyComp(294) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc195: TSynWebTokenKind;
begin
  if  CssPropKeyComp(27) or
      CssPropKeyComp(92) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc197: TSynWebTokenKind;
begin
  if  CssPropKeyComp(16) or
      CssPropKeyComp(199) or
      CssPropKeyComp(265) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc198: TSynWebTokenKind;
begin
  if  CssPropKeyComp(202) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc199: TSynWebTokenKind;
begin
  if  CssPropKeyComp(20) or
      CssPropKeyComp(150) or
      CssPropKeyComp(183) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc200: TSynWebTokenKind;
begin
  if  CssPropKeyComp(1) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc201: TSynWebTokenKind;
begin
  if  CssPropKeyComp(84) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc202: TSynWebTokenKind;
begin
  if  CssPropKeyComp(215) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc203: TSynWebTokenKind;
begin
  if  CssPropKeyComp(273) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc205: TSynWebTokenKind;
begin
  if  CssPropKeyComp(200) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc206: TSynWebTokenKind;
begin
  if  CssPropKeyComp(12) or
      CssPropKeyComp(18) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc208: TSynWebTokenKind;
begin
  if  CssPropKeyComp(0) or
      CssPropKeyComp(258) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc210: TSynWebTokenKind;
begin
  if  CssPropKeyComp(195) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc211: TSynWebTokenKind;
begin
  if  CssPropKeyComp(260) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc213: TSynWebTokenKind;
begin
  if  CssPropKeyComp(136) or
      CssPropKeyComp(154) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc215: TSynWebTokenKind;
begin
  if  CssPropKeyComp(179) or
      CssPropKeyComp(201) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc217: TSynWebTokenKind;
begin
  if  CssPropKeyComp(145) or
      CssPropKeyComp(271) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc220: TSynWebTokenKind;
begin
  if  CssPropKeyComp(139) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc221: TSynWebTokenKind;
begin
  if  CssPropKeyComp(40) or
      CssPropKeyComp(156) or
      CssPropKeyComp(239) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc223: TSynWebTokenKind;
begin
  if  CssPropKeyComp(157) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc224: TSynWebTokenKind;
begin
  if  CssPropKeyComp(236) or
      CssPropKeyComp(284) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc226: TSynWebTokenKind;
begin
  if  CssPropKeyComp(254) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc230: TSynWebTokenKind;
begin
  if  CssPropKeyComp(127) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc231: TSynWebTokenKind;
begin
  if  CssPropKeyComp(4) or
      CssPropKeyComp(118) or
      CssPropKeyComp(275) or
      CssPropKeyComp(297) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc234: TSynWebTokenKind;
begin
  if  CssPropKeyComp(281) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc235: TSynWebTokenKind;
begin
  if  CssPropKeyComp(83) or
      CssPropKeyComp(129) or
      CssPropKeyComp(204) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc236: TSynWebTokenKind;
begin
  if  CssPropKeyComp(5) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc237: TSynWebTokenKind;
begin
  if  CssPropKeyComp(42) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc238: TSynWebTokenKind;
begin
  if  CssPropKeyComp(39) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc239: TSynWebTokenKind;
begin
  if  CssPropKeyComp(14) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc240: TSynWebTokenKind;
begin
  if  CssPropKeyComp(257) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc242: TSynWebTokenKind;
begin
  if  CssPropKeyComp(132) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc243: TSynWebTokenKind;
begin
  if  CssPropKeyComp(282) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc244: TSynWebTokenKind;
begin
  if  CssPropKeyComp(44) or
      CssPropKeyComp(151) or
      CssPropKeyComp(245) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc245: TSynWebTokenKind;
begin
  if  CssPropKeyComp(46) or
      CssPropKeyComp(291) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc247: TSynWebTokenKind;
begin
  if  CssPropKeyComp(272) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc248: TSynWebTokenKind;
begin
  if  CssPropKeyComp(221) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc250: TSynWebTokenKind;
begin
  if  CssPropKeyComp(227) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc251: TSynWebTokenKind;
begin
  if  CssPropKeyComp(19) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc252: TSynWebTokenKind;
begin
  if  CssPropKeyComp(55) or
      CssPropKeyComp(141) or
      CssPropKeyComp(167) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc253: TSynWebTokenKind;
begin
  if  CssPropKeyComp(59) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc254: TSynWebTokenKind;
begin
  if  CssPropKeyComp(41) or
      CssPropKeyComp(138) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc255: TSynWebTokenKind;
begin
  if  CssPropKeyComp(121) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc258: TSynWebTokenKind;
begin
  if  CssPropKeyComp(62) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc260: TSynWebTokenKind;
begin
  if  CssPropKeyComp(256) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc262: TSynWebTokenKind;
begin
  if  CssPropKeyComp(45) or
      CssPropKeyComp(97) or
      CssPropKeyComp(164) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc263: TSynWebTokenKind;
begin
  if  CssPropKeyComp(49) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc264: TSynWebTokenKind;
begin
  if  CssPropKeyComp(51) or
      CssPropKeyComp(98) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc265: TSynWebTokenKind;
begin
  if  CssPropKeyComp(115) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc266: TSynWebTokenKind;
begin
  if  CssPropKeyComp(163) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc270: TSynWebTokenKind;
begin
  if  CssPropKeyComp(58) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc273: TSynWebTokenKind;
begin
  if  CssPropKeyComp(38) or
      CssPropKeyComp(76) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc274: TSynWebTokenKind;
begin
  if  CssPropKeyComp(78) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc276: TSynWebTokenKind;
begin
  if  CssPropKeyComp(131) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc279: TSynWebTokenKind;
begin
  if  CssPropKeyComp(285) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc281: TSynWebTokenKind;
begin
  if  CssPropKeyComp(50) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc283: TSynWebTokenKind;
begin
  if  CssPropKeyComp(169) or
      CssPropKeyComp(181) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc286: TSynWebTokenKind;
begin
  if  CssPropKeyComp(30) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc287: TSynWebTokenKind;
begin
  if  CssPropKeyComp(34) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc289: TSynWebTokenKind;
begin
  if  CssPropKeyComp(262) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc291: TSynWebTokenKind;
begin
  if  CssPropKeyComp(8) or
      CssPropKeyComp(77) or
      CssPropKeyComp(146) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc292: TSynWebTokenKind;
begin
  if  CssPropKeyComp(147) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc293: TSynWebTokenKind;
begin
  if  CssPropKeyComp(148) or
      CssPropKeyComp(303) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc295: TSynWebTokenKind;
begin
  if  CssPropKeyComp(113) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc298: TSynWebTokenKind;
begin
  if  CssPropKeyComp(266) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc299: TSynWebTokenKind;
begin
  if  CssPropKeyComp(124) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc300: TSynWebTokenKind;
begin
  if  CssPropKeyComp(149) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc304: TSynWebTokenKind;
begin
  if  CssPropKeyComp(33) or
      CssPropKeyComp(263) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc310: TSynWebTokenKind;
begin
  if  CssPropKeyComp(286) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc312: TSynWebTokenKind;
begin
  if  CssPropKeyComp(261) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc315: TSynWebTokenKind;
begin
  if  CssPropKeyComp(165) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc316: TSynWebTokenKind;
begin
  if  CssPropKeyComp(268) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc320: TSynWebTokenKind;
begin
  if  CssPropKeyComp(111) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc328: TSynWebTokenKind;
begin
  if  CssPropKeyComp(123) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc330: TSynWebTokenKind;
begin
  if  CssPropKeyComp(264) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc331: TSynWebTokenKind;
begin
  if  CssPropKeyComp(120) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc334: TSynWebTokenKind;
begin
  if  CssPropKeyComp(94) or
      CssPropKeyComp(168) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc335: TSynWebTokenKind;
begin
  if  CssPropKeyComp(96) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc342: TSynWebTokenKind;
begin
  if  CssPropKeyComp(56) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc343: TSynWebTokenKind;
begin
  if  CssPropKeyComp(122) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc346: TSynWebTokenKind;
begin
  if  CssPropKeyComp(9) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc352: TSynWebTokenKind;
begin
  if  CssPropKeyComp(267) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc356: TSynWebTokenKind;
begin
  if  CssPropKeyComp(6) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc361: TSynWebTokenKind;
begin
  if  CssPropKeyComp(57) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc364: TSynWebTokenKind;
begin
  if  CssPropKeyComp(277) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc366: TSynWebTokenKind;
begin
  if  CssPropKeyComp(93) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc367: TSynWebTokenKind;
begin
  if  CssPropKeyComp(95) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc376: TSynWebTokenKind;
begin
  if  CssPropKeyComp(31) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc389: TSynWebTokenKind;
begin
  if  CssPropKeyComp(287) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;

function TSynWebEngine.CssPropFunc395: TSynWebTokenKind;
begin
  if  CssPropKeyComp(32) then
    Result := stkCssProp
  else
    Result := stkCssPropUndef;
end;
