function TSynWebEngine.CssSpecialUndef: Boolean;
begin
  Result:=False;
end;

function TSynWebEngine.CssSpecialFunc16: Boolean;
begin
  if  CssSpecialKeyComp(8) or
      CssSpecialKeyComp(9) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.CssSpecialFunc18: Boolean;
begin
  if  CssSpecialKeyComp(11) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.CssSpecialFunc19: Boolean;
begin
  if  CssSpecialKeyComp(47) or
      CssSpecialKeyComp(55) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.CssSpecialFunc23: Boolean;
begin
  if  CssSpecialKeyComp(29) or
      CssSpecialKeyComp(52) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.CssSpecialFunc25: Boolean;
begin
  if  CssSpecialKeyComp(2) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.CssSpecialFunc26: Boolean;
begin
  if  CssSpecialKeyComp(37) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.CssSpecialFunc29: Boolean;
begin
  if  CssSpecialKeyComp(15) or
      CssSpecialKeyComp(46) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.CssSpecialFunc30: Boolean;
begin
  if  CssSpecialKeyComp(23) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.CssSpecialFunc32: Boolean;
begin
  if  CssSpecialKeyComp(36) or
      CssSpecialKeyComp(38) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.CssSpecialFunc34: Boolean;
begin
  if  CssSpecialKeyComp(26) or
      CssSpecialKeyComp(31) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.CssSpecialFunc36: Boolean;
begin
  if  CssSpecialKeyComp(50) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.CssSpecialFunc39: Boolean;
begin
  if  CssSpecialKeyComp(7) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.CssSpecialFunc40: Boolean;
begin
  if  CssSpecialKeyComp(51) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.CssSpecialFunc42: Boolean;
begin
  if  CssSpecialKeyComp(60) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.CssSpecialFunc43: Boolean;
begin
  if  CssSpecialKeyComp(14) or
      CssSpecialKeyComp(34) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.CssSpecialFunc45: Boolean;
begin
  if  CssSpecialKeyComp(30) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.CssSpecialFunc46: Boolean;
begin
  if  CssSpecialKeyComp(35) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.CssSpecialFunc49: Boolean;
begin
  if  CssSpecialKeyComp(39) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.CssSpecialFunc50: Boolean;
begin
  if  CssSpecialKeyComp(1) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.CssSpecialFunc51: Boolean;
begin
  if  CssSpecialKeyComp(4) or
      CssSpecialKeyComp(61) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.CssSpecialFunc56: Boolean;
begin
  if  CssSpecialKeyComp(10) or
      CssSpecialKeyComp(24) or
      CssSpecialKeyComp(57) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.CssSpecialFunc57: Boolean;
begin
  if  CssSpecialKeyComp(3) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.CssSpecialFunc59: Boolean;
begin
  if  CssSpecialKeyComp(5) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.CssSpecialFunc60: Boolean;
begin
  if  CssSpecialKeyComp(0) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.CssSpecialFunc62: Boolean;
begin
  if  CssSpecialKeyComp(53) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.CssSpecialFunc64: Boolean;
begin
  if  CssSpecialKeyComp(21) or
      CssSpecialKeyComp(56) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.CssSpecialFunc65: Boolean;
begin
  if  CssSpecialKeyComp(59) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.CssSpecialFunc68: Boolean;
begin
  if  CssSpecialKeyComp(25) or
      CssSpecialKeyComp(54) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.CssSpecialFunc71: Boolean;
begin
  if  CssSpecialKeyComp(58) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.CssSpecialFunc72: Boolean;
begin
  if  CssSpecialKeyComp(16) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.CssSpecialFunc74: Boolean;
begin
  if  CssSpecialKeyComp(6) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.CssSpecialFunc77: Boolean;
begin
  if  CssSpecialKeyComp(48) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.CssSpecialFunc79: Boolean;
begin
  if  CssSpecialKeyComp(13) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.CssSpecialFunc82: Boolean;
begin
  if  CssSpecialKeyComp(12) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.CssSpecialFunc86: Boolean;
begin
  if  CssSpecialKeyComp(63) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.CssSpecialFunc88: Boolean;
begin
  if  CssSpecialKeyComp(62) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.CssSpecialFunc91: Boolean;
begin
  if  CssSpecialKeyComp(27) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.CssSpecialFunc108: Boolean;
begin
  if  CssSpecialKeyComp(22) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.CssSpecialFunc116: Boolean;
begin
  if  CssSpecialKeyComp(40) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.CssSpecialFunc125: Boolean;
begin
  if  CssSpecialKeyComp(49) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.CssSpecialFunc126: Boolean;
begin
  if  CssSpecialKeyComp(28) or
      CssSpecialKeyComp(32) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.CssSpecialFunc140: Boolean;
begin
  if  CssSpecialKeyComp(44) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.CssSpecialFunc146: Boolean;
begin
  if  CssSpecialKeyComp(17) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.CssSpecialFunc150: Boolean;
begin
  if  CssSpecialKeyComp(19) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.CssSpecialFunc190: Boolean;
begin
  if  CssSpecialKeyComp(18) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.CssSpecialFunc205: Boolean;
begin
  if  CssSpecialKeyComp(43) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.CssSpecialFunc206: Boolean;
begin
  if  CssSpecialKeyComp(41) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.CssSpecialFunc215: Boolean;
begin
  if  CssSpecialKeyComp(33) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.CssSpecialFunc229: Boolean;
begin
  if  CssSpecialKeyComp(45) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.CssSpecialFunc235: Boolean;
begin
  if  CssSpecialKeyComp(20) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.CssSpecialFunc295: Boolean;
begin
  if  CssSpecialKeyComp(42) then
    Result := True
  else
    Result := False;
end;
