function TSynWebSyn.HTML_SpecialUndef: Boolean;
begin
  Result:=False;
end;

function TSynWebSyn.HTML_SpecialFunc12: Boolean;
begin
  if  HTML_SpecialKeyComp(79) then
    Result := True
  else
    Result := False;
end;

function TSynWebSyn.HTML_SpecialFunc16: Boolean;
begin
  if  HTML_SpecialKeyComp(46) then
    Result := True
  else
    Result := False;
end;

function TSynWebSyn.HTML_SpecialFunc17: Boolean;
begin
  if  HTML_SpecialKeyComp(111) then
    Result := True
  else
    Result := False;
end;

function TSynWebSyn.HTML_SpecialFunc19: Boolean;
begin
  if  HTML_SpecialKeyComp(13) or
      HTML_SpecialKeyComp(129) then
    Result := True
  else
    Result := False;
end;

function TSynWebSyn.HTML_SpecialFunc20: Boolean;
begin
  if  HTML_SpecialKeyComp(28) or
      HTML_SpecialKeyComp(33) or
      HTML_SpecialKeyComp(34) then
    Result := True
  else
    Result := False;
end;

function TSynWebSyn.HTML_SpecialFunc22: Boolean;
begin
  if  HTML_SpecialKeyComp(14) then
    Result := True
  else
    Result := False;
end;

function TSynWebSyn.HTML_SpecialFunc23: Boolean;
begin
  if  HTML_SpecialKeyComp(130) then
    Result := True
  else
    Result := False;
end;

function TSynWebSyn.HTML_SpecialFunc25: Boolean;
begin
  if  HTML_SpecialKeyComp(168) or
      HTML_SpecialKeyComp(169) then
    Result := True
  else
    Result := False;
end;

function TSynWebSyn.HTML_SpecialFunc26: Boolean;
begin
  if  HTML_SpecialKeyComp(63) or
      HTML_SpecialKeyComp(64) then
    Result := True
  else
    Result := False;
end;

function TSynWebSyn.HTML_SpecialFunc27: Boolean;
begin
  if  HTML_SpecialKeyComp(80) then
    Result := True
  else
    Result := False;
end;

function TSynWebSyn.HTML_SpecialFunc28: Boolean;
begin
  if  HTML_SpecialKeyComp(24) or
      HTML_SpecialKeyComp(25) or
      HTML_SpecialKeyComp(73) or
      HTML_SpecialKeyComp(74) or
      HTML_SpecialKeyComp(75) then
    Result := True
  else
    Result := False;
end;

function TSynWebSyn.HTML_SpecialFunc30: Boolean;
begin
  if  HTML_SpecialKeyComp(12) or
      HTML_SpecialKeyComp(126) or
      HTML_SpecialKeyComp(188) then
    Result := True
  else
    Result := False;
end;

function TSynWebSyn.HTML_SpecialFunc32: Boolean;
begin
  if  HTML_SpecialKeyComp(118) then
    Result := True
  else
    Result := False;
end;

function TSynWebSyn.HTML_SpecialFunc33: Boolean;
begin
  if  HTML_SpecialKeyComp(31) or
      HTML_SpecialKeyComp(35) or
      HTML_SpecialKeyComp(65) or
      HTML_SpecialKeyComp(66) or
      HTML_SpecialKeyComp(103) or
      HTML_SpecialKeyComp(104) or
      HTML_SpecialKeyComp(152) or
      HTML_SpecialKeyComp(166) or
      HTML_SpecialKeyComp(167) or
      HTML_SpecialKeyComp(242) or
      HTML_SpecialKeyComp(243) then
    Result := True
  else
    Result := False;
end;

function TSynWebSyn.HTML_SpecialFunc34: Boolean;
begin
  if  HTML_SpecialKeyComp(2) or
      HTML_SpecialKeyComp(3) or
      HTML_SpecialKeyComp(5) or
      HTML_SpecialKeyComp(6) or
      HTML_SpecialKeyComp(105) or
      HTML_SpecialKeyComp(124) or
      HTML_SpecialKeyComp(125) then
    Result := True
  else
    Result := False;
end;

function TSynWebSyn.HTML_SpecialFunc35: Boolean;
begin
  if  HTML_SpecialKeyComp(77) or
      HTML_SpecialKeyComp(78) or
      HTML_SpecialKeyComp(92) or
      HTML_SpecialKeyComp(119) or
      HTML_SpecialKeyComp(136) or
      HTML_SpecialKeyComp(137) or
      HTML_SpecialKeyComp(180) then
    Result := True
  else
    Result := False;
end;

function TSynWebSyn.HTML_SpecialFunc36: Boolean;
begin
  if  HTML_SpecialKeyComp(29) or
      HTML_SpecialKeyComp(30) or
      HTML_SpecialKeyComp(162) or
      HTML_SpecialKeyComp(187) then
    Result := True
  else
    Result := False;
end;

function TSynWebSyn.HTML_SpecialFunc38: Boolean;
begin
  if  HTML_SpecialKeyComp(10) or
      HTML_SpecialKeyComp(11) or
      HTML_SpecialKeyComp(53) or
      HTML_SpecialKeyComp(54) then
    Result := True
  else
    Result := False;
end;

function TSynWebSyn.HTML_SpecialFunc39: Boolean;
begin
  if  HTML_SpecialKeyComp(37) then
    Result := True
  else
    Result := False;
end;

function TSynWebSyn.HTML_SpecialFunc40: Boolean;
begin
  if  HTML_SpecialKeyComp(40) or
      HTML_SpecialKeyComp(181) then
    Result := True
  else
    Result := False;
end;

function TSynWebSyn.HTML_SpecialFunc41: Boolean;
begin
  if  HTML_SpecialKeyComp(44) or
      HTML_SpecialKeyComp(45) or
      HTML_SpecialKeyComp(71) or
      HTML_SpecialKeyComp(109) or
      HTML_SpecialKeyComp(147) or
      HTML_SpecialKeyComp(148) or
      HTML_SpecialKeyComp(190) or
      HTML_SpecialKeyComp(191) or
      HTML_SpecialKeyComp(204) then
    Result := True
  else
    Result := False;
end;

function TSynWebSyn.HTML_SpecialFunc42: Boolean;
begin
  if  HTML_SpecialKeyComp(32) or
      HTML_SpecialKeyComp(42) or
      HTML_SpecialKeyComp(43) or
      HTML_SpecialKeyComp(47) or
      HTML_SpecialKeyComp(48) or
      HTML_SpecialKeyComp(87) or
      HTML_SpecialKeyComp(88) or
      HTML_SpecialKeyComp(206) or
      HTML_SpecialKeyComp(215) or
      HTML_SpecialKeyComp(216) then
    Result := True
  else
    Result := False;
end;

function TSynWebSyn.HTML_SpecialFunc43: Boolean;
begin
  if  HTML_SpecialKeyComp(94) or
      HTML_SpecialKeyComp(115) or
      HTML_SpecialKeyComp(153) or
      HTML_SpecialKeyComp(192) then
    Result := True
  else
    Result := False;
end;

function TSynWebSyn.HTML_SpecialFunc44: Boolean;
begin
  if  HTML_SpecialKeyComp(177) or
      HTML_SpecialKeyComp(178) or
      HTML_SpecialKeyComp(246) then
    Result := True
  else
    Result := False;
end;

function TSynWebSyn.HTML_SpecialFunc45: Boolean;
begin
  if  HTML_SpecialKeyComp(81) or
      HTML_SpecialKeyComp(82) or
      HTML_SpecialKeyComp(95) or
      HTML_SpecialKeyComp(96) or
      HTML_SpecialKeyComp(101) or
      HTML_SpecialKeyComp(102) or
      HTML_SpecialKeyComp(120) then
    Result := True
  else
    Result := False;
end;

function TSynWebSyn.HTML_SpecialFunc46: Boolean;
begin
  if  HTML_SpecialKeyComp(49) or
      HTML_SpecialKeyComp(128) or
      HTML_SpecialKeyComp(235) then
    Result := True
  else
    Result := False;
end;

function TSynWebSyn.HTML_SpecialFunc47: Boolean;
begin
  if  HTML_SpecialKeyComp(21) or
      HTML_SpecialKeyComp(22) or
      HTML_SpecialKeyComp(27) or
      HTML_SpecialKeyComp(170) or
      HTML_SpecialKeyComp(185) or
      HTML_SpecialKeyComp(199) or
      HTML_SpecialKeyComp(207) then
    Result := True
  else
    Result := False;
end;

function TSynWebSyn.HTML_SpecialFunc48: Boolean;
begin
  if  HTML_SpecialKeyComp(140) or
      HTML_SpecialKeyComp(141) or
      HTML_SpecialKeyComp(142) or
      HTML_SpecialKeyComp(143) or
      HTML_SpecialKeyComp(226) then
    Result := True
  else
    Result := False;
end;

function TSynWebSyn.HTML_SpecialFunc49: Boolean;
begin
  if  HTML_SpecialKeyComp(16) or
      HTML_SpecialKeyComp(17) or
      HTML_SpecialKeyComp(107) or
      HTML_SpecialKeyComp(108) or
      HTML_SpecialKeyComp(131) or
      HTML_SpecialKeyComp(201) or
      HTML_SpecialKeyComp(202) then
    Result := True
  else
    Result := False;
end;

function TSynWebSyn.HTML_SpecialFunc50: Boolean;
begin
  if  HTML_SpecialKeyComp(4) or
      HTML_SpecialKeyComp(154) or
      HTML_SpecialKeyComp(224) then
    Result := True
  else
    Result := False;
end;

function TSynWebSyn.HTML_SpecialFunc51: Boolean;
begin
  if  HTML_SpecialKeyComp(0) or
      HTML_SpecialKeyComp(1) or
      HTML_SpecialKeyComp(15) or
      HTML_SpecialKeyComp(19) or
      HTML_SpecialKeyComp(20) or
      HTML_SpecialKeyComp(67) or
      HTML_SpecialKeyComp(68) or
      HTML_SpecialKeyComp(98) or
      HTML_SpecialKeyComp(127) then
    Result := True
  else
    Result := False;
end;

function TSynWebSyn.HTML_SpecialFunc52: Boolean;
begin
  if  HTML_SpecialKeyComp(93) or
      HTML_SpecialKeyComp(200) or
      HTML_SpecialKeyComp(249) or
      HTML_SpecialKeyComp(250) then
    Result := True
  else
    Result := False;
end;

function TSynWebSyn.HTML_SpecialFunc53: Boolean;
begin
  if  HTML_SpecialKeyComp(50) or
      HTML_SpecialKeyComp(58) or
      HTML_SpecialKeyComp(89) or
      HTML_SpecialKeyComp(114) or
      HTML_SpecialKeyComp(175) or
      HTML_SpecialKeyComp(208) then
    Result := True
  else
    Result := False;
end;

function TSynWebSyn.HTML_SpecialFunc54: Boolean;
begin
  if  HTML_SpecialKeyComp(7) or
      HTML_SpecialKeyComp(8) or
      HTML_SpecialKeyComp(59) or
      HTML_SpecialKeyComp(218) or
      HTML_SpecialKeyComp(219) or
      HTML_SpecialKeyComp(231) or
      HTML_SpecialKeyComp(232) then
    Result := True
  else
    Result := False;
end;

function TSynWebSyn.HTML_SpecialFunc55: Boolean;
begin
  if  HTML_SpecialKeyComp(51) or
      HTML_SpecialKeyComp(52) or
      HTML_SpecialKeyComp(99) or
      HTML_SpecialKeyComp(100) or
      HTML_SpecialKeyComp(146) or
      HTML_SpecialKeyComp(163) or
      HTML_SpecialKeyComp(165) or
      HTML_SpecialKeyComp(183) or
      HTML_SpecialKeyComp(184) or
      HTML_SpecialKeyComp(203) then
    Result := True
  else
    Result := False;
end;

function TSynWebSyn.HTML_SpecialFunc56: Boolean;
begin
  if  HTML_SpecialKeyComp(76) or
      HTML_SpecialKeyComp(133) or
      HTML_SpecialKeyComp(209) or
      HTML_SpecialKeyComp(210) or
      HTML_SpecialKeyComp(211) or
      HTML_SpecialKeyComp(212) or
      HTML_SpecialKeyComp(217) then
    Result := True
  else
    Result := False;
end;

function TSynWebSyn.HTML_SpecialFunc57: Boolean;
begin
  if  HTML_SpecialKeyComp(36) then
    Result := True
  else
    Result := False;
end;

function TSynWebSyn.HTML_SpecialFunc58: Boolean;
begin
  if  HTML_SpecialKeyComp(39) or
      HTML_SpecialKeyComp(55) or
      HTML_SpecialKeyComp(56) or
      HTML_SpecialKeyComp(121) or
      HTML_SpecialKeyComp(198) or
      HTML_SpecialKeyComp(229) or
      HTML_SpecialKeyComp(230) then
    Result := True
  else
    Result := False;
end;

function TSynWebSyn.HTML_SpecialFunc59: Boolean;
begin
  if  HTML_SpecialKeyComp(23) or
      HTML_SpecialKeyComp(38) or
      HTML_SpecialKeyComp(69) or
      HTML_SpecialKeyComp(85) or
      HTML_SpecialKeyComp(86) or
      HTML_SpecialKeyComp(251) then
    Result := True
  else
    Result := False;
end;

function TSynWebSyn.HTML_SpecialFunc61: Boolean;
begin
  if  HTML_SpecialKeyComp(160) or
      HTML_SpecialKeyComp(161) or
      HTML_SpecialKeyComp(173) or
      HTML_SpecialKeyComp(174) or
      HTML_SpecialKeyComp(213) then
    Result := True
  else
    Result := False;
end;

function TSynWebSyn.HTML_SpecialFunc62: Boolean;
begin
  if  HTML_SpecialKeyComp(84) or
      HTML_SpecialKeyComp(90) or
      HTML_SpecialKeyComp(91) then
    Result := True
  else
    Result := False;
end;

function TSynWebSyn.HTML_SpecialFunc63: Boolean;
begin
  if  HTML_SpecialKeyComp(26) then
    Result := True
  else
    Result := False;
end;

function TSynWebSyn.HTML_SpecialFunc64: Boolean;
begin
  if  HTML_SpecialKeyComp(72) or
      HTML_SpecialKeyComp(134) or
      HTML_SpecialKeyComp(135) or
      HTML_SpecialKeyComp(205) then
    Result := True
  else
    Result := False;
end;

function TSynWebSyn.HTML_SpecialFunc65: Boolean;
begin
  if  HTML_SpecialKeyComp(122) or
      HTML_SpecialKeyComp(138) or
      HTML_SpecialKeyComp(139) or
      HTML_SpecialKeyComp(157) or
      HTML_SpecialKeyComp(158) or
      HTML_SpecialKeyComp(176) then
    Result := True
  else
    Result := False;
end;

function TSynWebSyn.HTML_SpecialFunc66: Boolean;
begin
  if  HTML_SpecialKeyComp(106) or
      HTML_SpecialKeyComp(225) then
    Result := True
  else
    Result := False;
end;

function TSynWebSyn.HTML_SpecialFunc67: Boolean;
begin
  if  HTML_SpecialKeyComp(239) or
      HTML_SpecialKeyComp(240) then
    Result := True
  else
    Result := False;
end;

function TSynWebSyn.HTML_SpecialFunc68: Boolean;
begin
  if  HTML_SpecialKeyComp(144) or
      HTML_SpecialKeyComp(145) then
    Result := True
  else
    Result := False;
end;

function TSynWebSyn.HTML_SpecialFunc69: Boolean;
begin
  if  HTML_SpecialKeyComp(110) then
    Result := True
  else
    Result := False;
end;

function TSynWebSyn.HTML_SpecialFunc70: Boolean;
begin
  if  HTML_SpecialKeyComp(172) or
      HTML_SpecialKeyComp(196) or
      HTML_SpecialKeyComp(197) then
    Result := True
  else
    Result := False;
end;

function TSynWebSyn.HTML_SpecialFunc71: Boolean;
begin
  if  HTML_SpecialKeyComp(83) or
      HTML_SpecialKeyComp(227) or
      HTML_SpecialKeyComp(228) or
      HTML_SpecialKeyComp(247) or
      HTML_SpecialKeyComp(248) then
    Result := True
  else
    Result := False;
end;

function TSynWebSyn.HTML_SpecialFunc72: Boolean;
begin
  if  HTML_SpecialKeyComp(132) or
      HTML_SpecialKeyComp(182) then
    Result := True
  else
    Result := False;
end;

function TSynWebSyn.HTML_SpecialFunc73: Boolean;
begin
  if  HTML_SpecialKeyComp(164) or
      HTML_SpecialKeyComp(179) or
      HTML_SpecialKeyComp(214) or
      HTML_SpecialKeyComp(236) or
      HTML_SpecialKeyComp(252) then
    Result := True
  else
    Result := False;
end;

function TSynWebSyn.HTML_SpecialFunc74: Boolean;
begin
  if  HTML_SpecialKeyComp(18) or
      HTML_SpecialKeyComp(62) or
      HTML_SpecialKeyComp(155) or
      HTML_SpecialKeyComp(156) or
      HTML_SpecialKeyComp(195) or
      HTML_SpecialKeyComp(233) or
      HTML_SpecialKeyComp(234) then
    Result := True
  else
    Result := False;
end;

function TSynWebSyn.HTML_SpecialFunc75: Boolean;
begin
  if  HTML_SpecialKeyComp(186) or
      HTML_SpecialKeyComp(222) or
      HTML_SpecialKeyComp(223) or
      HTML_SpecialKeyComp(244) or
      HTML_SpecialKeyComp(245) then
    Result := True
  else
    Result := False;
end;

function TSynWebSyn.HTML_SpecialFunc76: Boolean;
begin
  if  HTML_SpecialKeyComp(123) or
      HTML_SpecialKeyComp(241) then
    Result := True
  else
    Result := False;
end;

function TSynWebSyn.HTML_SpecialFunc77: Boolean;
begin
  if  HTML_SpecialKeyComp(70) then
    Result := True
  else
    Result := False;
end;

function TSynWebSyn.HTML_SpecialFunc78: Boolean;
begin
  if  HTML_SpecialKeyComp(112) then
    Result := True
  else
    Result := False;
end;

function TSynWebSyn.HTML_SpecialFunc79: Boolean;
begin
  if  HTML_SpecialKeyComp(41) or
      HTML_SpecialKeyComp(57) then
    Result := True
  else
    Result := False;
end;

function TSynWebSyn.HTML_SpecialFunc81: Boolean;
begin
  if  HTML_SpecialKeyComp(9) or
      HTML_SpecialKeyComp(159) then
    Result := True
  else
    Result := False;
end;

function TSynWebSyn.HTML_SpecialFunc83: Boolean;
begin
  if  HTML_SpecialKeyComp(151) then
    Result := True
  else
    Result := False;
end;

function TSynWebSyn.HTML_SpecialFunc84: Boolean;
begin
  if  HTML_SpecialKeyComp(117) or
      HTML_SpecialKeyComp(189) then
    Result := True
  else
    Result := False;
end;

function TSynWebSyn.HTML_SpecialFunc85: Boolean;
begin
  if  HTML_SpecialKeyComp(116) then
    Result := True
  else
    Result := False;
end;

function TSynWebSyn.HTML_SpecialFunc86: Boolean;
begin
  if  HTML_SpecialKeyComp(221) then
    Result := True
  else
    Result := False;
end;

function TSynWebSyn.HTML_SpecialFunc87: Boolean;
begin
  if  HTML_SpecialKeyComp(149) or
      HTML_SpecialKeyComp(150) then
    Result := True
  else
    Result := False;
end;

function TSynWebSyn.HTML_SpecialFunc90: Boolean;
begin
  if  HTML_SpecialKeyComp(60) or
      HTML_SpecialKeyComp(61) or
      HTML_SpecialKeyComp(113) or
      HTML_SpecialKeyComp(194) then
    Result := True
  else
    Result := False;
end;

function TSynWebSyn.HTML_SpecialFunc91: Boolean;
begin
  if  HTML_SpecialKeyComp(97) or
      HTML_SpecialKeyComp(193) then
    Result := True
  else
    Result := False;
end;

function TSynWebSyn.HTML_SpecialFunc95: Boolean;
begin
  if  HTML_SpecialKeyComp(171) then
    Result := True
  else
    Result := False;
end;

function TSynWebSyn.HTML_SpecialFunc106: Boolean;
begin
  if  HTML_SpecialKeyComp(237) or
      HTML_SpecialKeyComp(238) then
    Result := True
  else
    Result := False;
end;

function TSynWebSyn.HTML_SpecialFunc111: Boolean;
begin
  if  HTML_SpecialKeyComp(220) then
    Result := True
  else
    Result := False;
end;
