function TSynWebEngine.MLAttrUndef: TSynWebTokenKind;
begin
  Result:=stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc13: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(55) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc15: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(45) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc23: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(0) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc26: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(32) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc27: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(23) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc30: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(15) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc31: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(40) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc32: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(57) or
      MLAttrKeyComp(65) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc33: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(7) or
      MLAttrKeyComp(68) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc34: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(58) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc35: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(95) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc37: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(19) or
      MLAttrKeyComp(51) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc38: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(39) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc39: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(18) or
      MLAttrKeyComp(22) or
      MLAttrKeyComp(46) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc40: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(107) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc43: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(5) or
      MLAttrKeyComp(47) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc45: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(96) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc46: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(60) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc47: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(6) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc48: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(1) or
      MLAttrKeyComp(33) or
      MLAttrKeyComp(38) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc49: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(27) or
      MLAttrKeyComp(104) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc50: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(106) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc52: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(53) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc53: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(9) or
      MLAttrKeyComp(100) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc54: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(20) or
      MLAttrKeyComp(24) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc55: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(73) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc56: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(41) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc57: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(16) or
      MLAttrKeyComp(50) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc58: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(56) or
      MLAttrKeyComp(101) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc59: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(105) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc60: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(49) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc61: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(82) or
      MLAttrKeyComp(119) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc62: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(4) or
      MLAttrKeyComp(12) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc63: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(26) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc64: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(124) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc65: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(66) or
      MLAttrKeyComp(118) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc66: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(8) or
      MLAttrKeyComp(36) or
      MLAttrKeyComp(44) or
      MLAttrKeyComp(69) or
      MLAttrKeyComp(71) or
      MLAttrKeyComp(115) or
      MLAttrKeyComp(116) or
      MLAttrKeyComp(123) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc67: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(21) or
      MLAttrKeyComp(75) or
      MLAttrKeyComp(76) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc68: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(59) or
      MLAttrKeyComp(122) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc69: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(114) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc71: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(29) or
      MLAttrKeyComp(42) or
      MLAttrKeyComp(52) or
      MLAttrKeyComp(113) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc72: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(11) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc73: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(103) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc74: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(17) or
      MLAttrKeyComp(31) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc75: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(97) or
      MLAttrKeyComp(99) or
      MLAttrKeyComp(117) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc77: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(37) or
      MLAttrKeyComp(125) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc78: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(109) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc79: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(61) or
      MLAttrKeyComp(112) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc80: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(28) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc81: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(92) or
      MLAttrKeyComp(110) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc82: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(74) or
      MLAttrKeyComp(127) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc85: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(77) or
      MLAttrKeyComp(108) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc87: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(13) or
      MLAttrKeyComp(72) or
      MLAttrKeyComp(126) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc88: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(43) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc91: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(3) or
      MLAttrKeyComp(30) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc93: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(25) or
      MLAttrKeyComp(78) or
      MLAttrKeyComp(89) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc94: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(94) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc96: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(10) or
      MLAttrKeyComp(88) or
      MLAttrKeyComp(91) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc98: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(93) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc101: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(14) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc102: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(121) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc103: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(2) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc104: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(64) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc105: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(48) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc106: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(98) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc107: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(81) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc108: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(67) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc109: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(102) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc110: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(111) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc111: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(70) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc113: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(90) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc114: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(35) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc119: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(34) or
      MLAttrKeyComp(54) or
      MLAttrKeyComp(62) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc126: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(63) or
      MLAttrKeyComp(79) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc127: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(120) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc139: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(87) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc147: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(80) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc157: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(84) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc158: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(83) or
      MLAttrKeyComp(85) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc162: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(86) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;
