function TSynWebEngine.MLAttrUndef: TSynWebTokenKind;
begin
  Result:=stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc13: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(61) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc15: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(49) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc23: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(0) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc26: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(34) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc27: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(24) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc30: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(16) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc31: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(42) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc32: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(65) or
      MLAttrKeyComp(74) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc33: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(7) or
      MLAttrKeyComp(78) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc34: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(66) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc35: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(113) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc37: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(20) or
      MLAttrKeyComp(57) or
      MLAttrKeyComp(76) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc38: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(41) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc39: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(19) or
      MLAttrKeyComp(23) or
      MLAttrKeyComp(50) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc40: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(126) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc42: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(62) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc43: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(5) or
      MLAttrKeyComp(53) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc45: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(109) or
      MLAttrKeyComp(114) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc46: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(68) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc47: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(6) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc48: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(1) or
      MLAttrKeyComp(35) or
      MLAttrKeyComp(40) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc49: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(28) or
      MLAttrKeyComp(123) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc50: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(125) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc52: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(59) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc53: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(9) or
      MLAttrKeyComp(118) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc54: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(21) or
      MLAttrKeyComp(25) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc55: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(84) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc56: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(43) or
      MLAttrKeyComp(44) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc57: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(17) or
      MLAttrKeyComp(56) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc58: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(63) or
      MLAttrKeyComp(119) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc59: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(124) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc60: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(55) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc61: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(52) or
      MLAttrKeyComp(95) or
      MLAttrKeyComp(138) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc62: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(4) or
      MLAttrKeyComp(12) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc63: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(27) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc64: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(143) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc65: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(75) or
      MLAttrKeyComp(137) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc66: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(8) or
      MLAttrKeyComp(38) or
      MLAttrKeyComp(48) or
      MLAttrKeyComp(80) or
      MLAttrKeyComp(82) or
      MLAttrKeyComp(134) or
      MLAttrKeyComp(135) or
      MLAttrKeyComp(142) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc67: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(22) or
      MLAttrKeyComp(86) or
      MLAttrKeyComp(87) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc68: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(67) or
      MLAttrKeyComp(101) or
      MLAttrKeyComp(141) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc69: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(108) or
      MLAttrKeyComp(133) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc70: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(64) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc71: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(31) or
      MLAttrKeyComp(46) or
      MLAttrKeyComp(58) or
      MLAttrKeyComp(132) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc72: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(11) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc73: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(51) or
      MLAttrKeyComp(121) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc74: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(18) or
      MLAttrKeyComp(33) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc75: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(115) or
      MLAttrKeyComp(117) or
      MLAttrKeyComp(136) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc77: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(39) or
      MLAttrKeyComp(144) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc78: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(128) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc79: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(70) or
      MLAttrKeyComp(131) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc80: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(29) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc81: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(110) or
      MLAttrKeyComp(129) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc82: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(85) or
      MLAttrKeyComp(146) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc83: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(69) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc85: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(88) or
      MLAttrKeyComp(127) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc87: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(14) or
      MLAttrKeyComp(83) or
      MLAttrKeyComp(145) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc88: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(47) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc91: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(3) or
      MLAttrKeyComp(32) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc93: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(26) or
      MLAttrKeyComp(91) or
      MLAttrKeyComp(103) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc94: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(105) or
      MLAttrKeyComp(112) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc96: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(10) or
      MLAttrKeyComp(102) or
      MLAttrKeyComp(106) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc97: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(30) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc98: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(13) or
      MLAttrKeyComp(111) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc101: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(15) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc102: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(107) or
      MLAttrKeyComp(140) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc103: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(2) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc104: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(73) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc105: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(45) or
      MLAttrKeyComp(54) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc106: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(116) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc107: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(94) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc108: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(77) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc109: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(120) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc110: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(130) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc111: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(81) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc113: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(104) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc114: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(37) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc117: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(122) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc119: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(36) or
      MLAttrKeyComp(60) or
      MLAttrKeyComp(71) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc126: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(72) or
      MLAttrKeyComp(92) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc127: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(139) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc139: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(100) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc143: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(79) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc147: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(93) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc154: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(89) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc157: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(97) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc158: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(96) or
      MLAttrKeyComp(98) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc162: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(99) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;

function TSynWebEngine.MLAttrFunc176: TSynWebTokenKind;
begin
  if  MLAttrKeyComp(90) then
    Result := stkMLTagKey
  else
    Result := stkMLTagKeyUndef;
end;
