function TSynWebEngine.MLSpecialUndef: Boolean;
begin
  Result:=False;
end;

function TSynWebEngine.MLSpecialFunc12: Boolean;
begin
  if  MLSpecialKeyComp(79) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc16: Boolean;
begin
  if  MLSpecialKeyComp(46) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc17: Boolean;
begin
  if  MLSpecialKeyComp(111) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc19: Boolean;
begin
  if  MLSpecialKeyComp(13) or
      MLSpecialKeyComp(129) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc20: Boolean;
begin
  if  MLSpecialKeyComp(28) or
      MLSpecialKeyComp(33) or
      MLSpecialKeyComp(34) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc22: Boolean;
begin
  if  MLSpecialKeyComp(14) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc23: Boolean;
begin
  if  MLSpecialKeyComp(130) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc25: Boolean;
begin
  if  MLSpecialKeyComp(168) or
      MLSpecialKeyComp(169) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc26: Boolean;
begin
  if  MLSpecialKeyComp(63) or
      MLSpecialKeyComp(64) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc27: Boolean;
begin
  if  MLSpecialKeyComp(80) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc28: Boolean;
begin
  if  MLSpecialKeyComp(24) or
      MLSpecialKeyComp(25) or
      MLSpecialKeyComp(73) or
      MLSpecialKeyComp(74) or
      MLSpecialKeyComp(75) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc30: Boolean;
begin
  if  MLSpecialKeyComp(12) or
      MLSpecialKeyComp(126) or
      MLSpecialKeyComp(188) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc32: Boolean;
begin
  if  MLSpecialKeyComp(118) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc33: Boolean;
begin
  if  MLSpecialKeyComp(31) or
      MLSpecialKeyComp(35) or
      MLSpecialKeyComp(65) or
      MLSpecialKeyComp(66) or
      MLSpecialKeyComp(103) or
      MLSpecialKeyComp(104) or
      MLSpecialKeyComp(152) or
      MLSpecialKeyComp(166) or
      MLSpecialKeyComp(167) or
      MLSpecialKeyComp(242) or
      MLSpecialKeyComp(243) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc34: Boolean;
begin
  if  MLSpecialKeyComp(2) or
      MLSpecialKeyComp(3) or
      MLSpecialKeyComp(5) or
      MLSpecialKeyComp(6) or
      MLSpecialKeyComp(105) or
      MLSpecialKeyComp(124) or
      MLSpecialKeyComp(125) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc35: Boolean;
begin
  if  MLSpecialKeyComp(77) or
      MLSpecialKeyComp(78) or
      MLSpecialKeyComp(92) or
      MLSpecialKeyComp(119) or
      MLSpecialKeyComp(136) or
      MLSpecialKeyComp(137) or
      MLSpecialKeyComp(180) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc36: Boolean;
begin
  if  MLSpecialKeyComp(29) or
      MLSpecialKeyComp(30) or
      MLSpecialKeyComp(162) or
      MLSpecialKeyComp(187) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc38: Boolean;
begin
  if  MLSpecialKeyComp(10) or
      MLSpecialKeyComp(11) or
      MLSpecialKeyComp(53) or
      MLSpecialKeyComp(54) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc39: Boolean;
begin
  if  MLSpecialKeyComp(37) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc40: Boolean;
begin
  if  MLSpecialKeyComp(40) or
      MLSpecialKeyComp(181) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc41: Boolean;
begin
  if  MLSpecialKeyComp(44) or
      MLSpecialKeyComp(45) or
      MLSpecialKeyComp(71) or
      MLSpecialKeyComp(109) or
      MLSpecialKeyComp(147) or
      MLSpecialKeyComp(148) or
      MLSpecialKeyComp(190) or
      MLSpecialKeyComp(191) or
      MLSpecialKeyComp(204) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc42: Boolean;
begin
  if  MLSpecialKeyComp(32) or
      MLSpecialKeyComp(42) or
      MLSpecialKeyComp(43) or
      MLSpecialKeyComp(47) or
      MLSpecialKeyComp(48) or
      MLSpecialKeyComp(87) or
      MLSpecialKeyComp(88) or
      MLSpecialKeyComp(206) or
      MLSpecialKeyComp(215) or
      MLSpecialKeyComp(216) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc43: Boolean;
begin
  if  MLSpecialKeyComp(94) or
      MLSpecialKeyComp(115) or
      MLSpecialKeyComp(153) or
      MLSpecialKeyComp(192) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc44: Boolean;
begin
  if  MLSpecialKeyComp(177) or
      MLSpecialKeyComp(178) or
      MLSpecialKeyComp(246) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc45: Boolean;
begin
  if  MLSpecialKeyComp(81) or
      MLSpecialKeyComp(82) or
      MLSpecialKeyComp(95) or
      MLSpecialKeyComp(96) or
      MLSpecialKeyComp(101) or
      MLSpecialKeyComp(102) or
      MLSpecialKeyComp(120) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc46: Boolean;
begin
  if  MLSpecialKeyComp(49) or
      MLSpecialKeyComp(128) or
      MLSpecialKeyComp(235) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc47: Boolean;
begin
  if  MLSpecialKeyComp(21) or
      MLSpecialKeyComp(22) or
      MLSpecialKeyComp(27) or
      MLSpecialKeyComp(170) or
      MLSpecialKeyComp(185) or
      MLSpecialKeyComp(199) or
      MLSpecialKeyComp(207) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc48: Boolean;
begin
  if  MLSpecialKeyComp(140) or
      MLSpecialKeyComp(141) or
      MLSpecialKeyComp(142) or
      MLSpecialKeyComp(143) or
      MLSpecialKeyComp(226) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc49: Boolean;
begin
  if  MLSpecialKeyComp(16) or
      MLSpecialKeyComp(17) or
      MLSpecialKeyComp(107) or
      MLSpecialKeyComp(108) or
      MLSpecialKeyComp(131) or
      MLSpecialKeyComp(201) or
      MLSpecialKeyComp(202) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc50: Boolean;
begin
  if  MLSpecialKeyComp(4) or
      MLSpecialKeyComp(154) or
      MLSpecialKeyComp(224) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc51: Boolean;
begin
  if  MLSpecialKeyComp(0) or
      MLSpecialKeyComp(1) or
      MLSpecialKeyComp(15) or
      MLSpecialKeyComp(19) or
      MLSpecialKeyComp(20) or
      MLSpecialKeyComp(67) or
      MLSpecialKeyComp(68) or
      MLSpecialKeyComp(98) or
      MLSpecialKeyComp(127) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc52: Boolean;
begin
  if  MLSpecialKeyComp(93) or
      MLSpecialKeyComp(200) or
      MLSpecialKeyComp(249) or
      MLSpecialKeyComp(250) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc53: Boolean;
begin
  if  MLSpecialKeyComp(50) or
      MLSpecialKeyComp(58) or
      MLSpecialKeyComp(89) or
      MLSpecialKeyComp(114) or
      MLSpecialKeyComp(175) or
      MLSpecialKeyComp(208) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc54: Boolean;
begin
  if  MLSpecialKeyComp(7) or
      MLSpecialKeyComp(8) or
      MLSpecialKeyComp(59) or
      MLSpecialKeyComp(218) or
      MLSpecialKeyComp(219) or
      MLSpecialKeyComp(231) or
      MLSpecialKeyComp(232) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc55: Boolean;
begin
  if  MLSpecialKeyComp(51) or
      MLSpecialKeyComp(52) or
      MLSpecialKeyComp(99) or
      MLSpecialKeyComp(100) or
      MLSpecialKeyComp(146) or
      MLSpecialKeyComp(163) or
      MLSpecialKeyComp(165) or
      MLSpecialKeyComp(183) or
      MLSpecialKeyComp(184) or
      MLSpecialKeyComp(203) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc56: Boolean;
begin
  if  MLSpecialKeyComp(76) or
      MLSpecialKeyComp(133) or
      MLSpecialKeyComp(209) or
      MLSpecialKeyComp(210) or
      MLSpecialKeyComp(211) or
      MLSpecialKeyComp(212) or
      MLSpecialKeyComp(217) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc57: Boolean;
begin
  if  MLSpecialKeyComp(36) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc58: Boolean;
begin
  if  MLSpecialKeyComp(39) or
      MLSpecialKeyComp(55) or
      MLSpecialKeyComp(56) or
      MLSpecialKeyComp(121) or
      MLSpecialKeyComp(198) or
      MLSpecialKeyComp(229) or
      MLSpecialKeyComp(230) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc59: Boolean;
begin
  if  MLSpecialKeyComp(23) or
      MLSpecialKeyComp(38) or
      MLSpecialKeyComp(69) or
      MLSpecialKeyComp(85) or
      MLSpecialKeyComp(86) or
      MLSpecialKeyComp(251) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc61: Boolean;
begin
  if  MLSpecialKeyComp(160) or
      MLSpecialKeyComp(161) or
      MLSpecialKeyComp(173) or
      MLSpecialKeyComp(174) or
      MLSpecialKeyComp(213) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc62: Boolean;
begin
  if  MLSpecialKeyComp(84) or
      MLSpecialKeyComp(90) or
      MLSpecialKeyComp(91) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc63: Boolean;
begin
  if  MLSpecialKeyComp(26) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc64: Boolean;
begin
  if  MLSpecialKeyComp(72) or
      MLSpecialKeyComp(134) or
      MLSpecialKeyComp(135) or
      MLSpecialKeyComp(205) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc65: Boolean;
begin
  if  MLSpecialKeyComp(122) or
      MLSpecialKeyComp(138) or
      MLSpecialKeyComp(139) or
      MLSpecialKeyComp(157) or
      MLSpecialKeyComp(158) or
      MLSpecialKeyComp(176) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc66: Boolean;
begin
  if  MLSpecialKeyComp(106) or
      MLSpecialKeyComp(225) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc67: Boolean;
begin
  if  MLSpecialKeyComp(239) or
      MLSpecialKeyComp(240) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc68: Boolean;
begin
  if  MLSpecialKeyComp(144) or
      MLSpecialKeyComp(145) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc69: Boolean;
begin
  if  MLSpecialKeyComp(110) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc70: Boolean;
begin
  if  MLSpecialKeyComp(172) or
      MLSpecialKeyComp(196) or
      MLSpecialKeyComp(197) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc71: Boolean;
begin
  if  MLSpecialKeyComp(83) or
      MLSpecialKeyComp(227) or
      MLSpecialKeyComp(228) or
      MLSpecialKeyComp(247) or
      MLSpecialKeyComp(248) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc72: Boolean;
begin
  if  MLSpecialKeyComp(132) or
      MLSpecialKeyComp(182) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc73: Boolean;
begin
  if  MLSpecialKeyComp(164) or
      MLSpecialKeyComp(179) or
      MLSpecialKeyComp(214) or
      MLSpecialKeyComp(236) or
      MLSpecialKeyComp(252) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc74: Boolean;
begin
  if  MLSpecialKeyComp(18) or
      MLSpecialKeyComp(62) or
      MLSpecialKeyComp(155) or
      MLSpecialKeyComp(156) or
      MLSpecialKeyComp(195) or
      MLSpecialKeyComp(233) or
      MLSpecialKeyComp(234) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc75: Boolean;
begin
  if  MLSpecialKeyComp(186) or
      MLSpecialKeyComp(222) or
      MLSpecialKeyComp(223) or
      MLSpecialKeyComp(244) or
      MLSpecialKeyComp(245) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc76: Boolean;
begin
  if  MLSpecialKeyComp(123) or
      MLSpecialKeyComp(241) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc77: Boolean;
begin
  if  MLSpecialKeyComp(70) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc78: Boolean;
begin
  if  MLSpecialKeyComp(112) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc79: Boolean;
begin
  if  MLSpecialKeyComp(41) or
      MLSpecialKeyComp(57) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc81: Boolean;
begin
  if  MLSpecialKeyComp(9) or
      MLSpecialKeyComp(159) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc83: Boolean;
begin
  if  MLSpecialKeyComp(151) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc84: Boolean;
begin
  if  MLSpecialKeyComp(117) or
      MLSpecialKeyComp(189) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc85: Boolean;
begin
  if  MLSpecialKeyComp(116) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc86: Boolean;
begin
  if  MLSpecialKeyComp(221) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc87: Boolean;
begin
  if  MLSpecialKeyComp(149) or
      MLSpecialKeyComp(150) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc90: Boolean;
begin
  if  MLSpecialKeyComp(60) or
      MLSpecialKeyComp(61) or
      MLSpecialKeyComp(113) or
      MLSpecialKeyComp(194) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc91: Boolean;
begin
  if  MLSpecialKeyComp(97) or
      MLSpecialKeyComp(193) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc95: Boolean;
begin
  if  MLSpecialKeyComp(171) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc106: Boolean;
begin
  if  MLSpecialKeyComp(237) or
      MLSpecialKeyComp(238) then
    Result := True
  else
    Result := False;
end;

function TSynWebEngine.MLSpecialFunc111: Boolean;
begin
  if  MLSpecialKeyComp(220) then
    Result := True
  else
    Result := False;
end;
