function TSynWebSyn.Css_PropUndef: TtkTokenKind;
begin
  Result:=tkCssPropUndef;
end;

function TSynWebSyn.CSS_PropFunc29: TtkTokenKind;
begin
  if  CSS_PropKeyComp(37) then
    Result := tkCssProp
  else
    Result := tkCssPropUndef;
end;

function TSynWebSyn.CSS_PropFunc39: TtkTokenKind;
begin
  if  CSS_PropKeyComp(31) then
    Result := tkCssProp
  else
    Result := tkCssPropUndef;
end;

function TSynWebSyn.CSS_PropFunc40: TtkTokenKind;
begin
  if  CSS_PropKeyComp(32) then
    Result := tkCssProp
  else
    Result := tkCssPropUndef;
end;

function TSynWebSyn.CSS_PropFunc43: TtkTokenKind;
begin
  if  CSS_PropKeyComp(53) then
    Result := tkCssProp
  else
    Result := tkCssPropUndef;
end;

function TSynWebSyn.CSS_PropFunc51: TtkTokenKind;
begin
  if  CSS_PropKeyComp(104) then
    Result := tkCssProp
  else
    Result := tkCssPropUndef;
end;

function TSynWebSyn.CSS_PropFunc52: TtkTokenKind;
begin
  if  CSS_PropKeyComp(93) then
    Result := tkCssProp
  else
    Result := tkCssPropUndef;
end;

function TSynWebSyn.CSS_PropFunc54: TtkTokenKind;
begin
  if  CSS_PropKeyComp(45) then
    Result := tkCssProp
  else
    Result := tkCssPropUndef;
end;

function TSynWebSyn.CSS_PropFunc55: TtkTokenKind;
begin
  if  CSS_PropKeyComp(46) or
      CSS_PropKeyComp(75) then
    Result := tkCssProp
  else
    Result := tkCssPropUndef;
end;

function TSynWebSyn.CSS_PropFunc56: TtkTokenKind;
begin
  if  CSS_PropKeyComp(86) then
    Result := tkCssProp
  else
    Result := tkCssPropUndef;
end;

function TSynWebSyn.CSS_PropFunc57: TtkTokenKind;
begin
  if  CSS_PropKeyComp(52) then
    Result := tkCssProp
  else
    Result := tkCssPropUndef;
end;

function TSynWebSyn.CSS_PropFunc60: TtkTokenKind;
begin
  if  CSS_PropKeyComp(38) then
    Result := tkCssProp
  else
    Result := tkCssPropUndef;
end;

function TSynWebSyn.CSS_PropFunc61: TtkTokenKind;
begin
  if  CSS_PropKeyComp(39) then
    Result := tkCssProp
  else
    Result := tkCssPropUndef;
end;

function TSynWebSyn.CSS_PropFunc62: TtkTokenKind;
begin
  if  CSS_PropKeyComp(7) or
      CSS_PropKeyComp(60) or
      CSS_PropKeyComp(83) or
      CSS_PropKeyComp(92) then
    Result := tkCssProp
  else
    Result := tkCssPropUndef;
end;

function TSynWebSyn.CSS_PropFunc63: TtkTokenKind;
begin
  if  CSS_PropKeyComp(33) or
      CSS_PropKeyComp(114) then
    Result := tkCssProp
  else
    Result := tkCssPropUndef;
end;

function TSynWebSyn.CSS_PropFunc64: TtkTokenKind;
begin
  if  CSS_PropKeyComp(112) then
    Result := tkCssProp
  else
    Result := tkCssPropUndef;
end;

function TSynWebSyn.CSS_PropFunc74: TtkTokenKind;
begin
  if  CSS_PropKeyComp(67) or
      CSS_PropKeyComp(94) then
    Result := tkCssProp
  else
    Result := tkCssPropUndef;
end;

function TSynWebSyn.CSS_PropFunc76: TtkTokenKind;
begin
  if  CSS_PropKeyComp(65) or
      CSS_PropKeyComp(105) then
    Result := tkCssProp
  else
    Result := tkCssPropUndef;
end;

function TSynWebSyn.CSS_PropFunc78: TtkTokenKind;
begin
  if  CSS_PropKeyComp(55) or
      CSS_PropKeyComp(80) then
    Result := tkCssProp
  else
    Result := tkCssPropUndef;
end;

function TSynWebSyn.CSS_PropFunc79: TtkTokenKind;
begin
  if  CSS_PropKeyComp(77) or
      CSS_PropKeyComp(81) then
    Result := tkCssProp
  else
    Result := tkCssPropUndef;
end;

function TSynWebSyn.CSS_PropFunc81: TtkTokenKind;
begin
  if  CSS_PropKeyComp(68) or
      CSS_PropKeyComp(97) then
    Result := tkCssProp
  else
    Result := tkCssPropUndef;
end;

function TSynWebSyn.CSS_PropFunc82: TtkTokenKind;
begin
  if  CSS_PropKeyComp(87) then
    Result := tkCssProp
  else
    Result := tkCssPropUndef;
end;

function TSynWebSyn.CSS_PropFunc83: TtkTokenKind;
begin
  if  CSS_PropKeyComp(66) then
    Result := tkCssProp
  else
    Result := tkCssPropUndef;
end;

function TSynWebSyn.CSS_PropFunc85: TtkTokenKind;
begin
  if  CSS_PropKeyComp(29) then
    Result := tkCssProp
  else
    Result := tkCssPropUndef;
end;

function TSynWebSyn.CSS_PropFunc86: TtkTokenKind;
begin
  if  CSS_PropKeyComp(14) or
      CSS_PropKeyComp(42) or
      CSS_PropKeyComp(62) then
    Result := tkCssProp
  else
    Result := tkCssPropUndef;
end;

function TSynWebSyn.CSS_PropFunc87: TtkTokenKind;
begin
  if  CSS_PropKeyComp(79) then
    Result := tkCssProp
  else
    Result := tkCssPropUndef;
end;

function TSynWebSyn.CSS_PropFunc88: TtkTokenKind;
begin
  if  CSS_PropKeyComp(82) or
      CSS_PropKeyComp(109) then
    Result := tkCssProp
  else
    Result := tkCssPropUndef;
end;

function TSynWebSyn.CSS_PropFunc90: TtkTokenKind;
begin
  if  CSS_PropKeyComp(110) then
    Result := tkCssProp
  else
    Result := tkCssPropUndef;
end;

function TSynWebSyn.CSS_PropFunc91: TtkTokenKind;
begin
  if  CSS_PropKeyComp(34) or
      CSS_PropKeyComp(69) then
    Result := tkCssProp
  else
    Result := tkCssPropUndef;
end;

function TSynWebSyn.CSS_PropFunc93: TtkTokenKind;
begin
  if  CSS_PropKeyComp(84) or
      CSS_PropKeyComp(100) or
      CSS_PropKeyComp(111) then
    Result := tkCssProp
  else
    Result := tkCssPropUndef;
end;

function TSynWebSyn.CSS_PropFunc94: TtkTokenKind;
begin
  if  CSS_PropKeyComp(24) or
      CSS_PropKeyComp(40) or
      CSS_PropKeyComp(64) or
      CSS_PropKeyComp(85) then
    Result := tkCssProp
  else
    Result := tkCssPropUndef;
end;

function TSynWebSyn.CSS_PropFunc95: TtkTokenKind;
begin
  if  CSS_PropKeyComp(48) or
      CSS_PropKeyComp(91) then
    Result := tkCssProp
  else
    Result := tkCssPropUndef;
end;

function TSynWebSyn.CSS_PropFunc96: TtkTokenKind;
begin
  if  CSS_PropKeyComp(1) or
      CSS_PropKeyComp(30) or
      CSS_PropKeyComp(70) then
    Result := tkCssProp
  else
    Result := tkCssPropUndef;
end;

function TSynWebSyn.CSS_PropFunc97: TtkTokenKind;
begin
  if  CSS_PropKeyComp(41) or
      CSS_PropKeyComp(90) then
    Result := tkCssProp
  else
    Result := tkCssPropUndef;
end;

function TSynWebSyn.CSS_PropFunc98: TtkTokenKind;
begin
  if  CSS_PropKeyComp(0) or
      CSS_PropKeyComp(78) then
    Result := tkCssProp
  else
    Result := tkCssPropUndef;
end;

function TSynWebSyn.CSS_PropFunc100: TtkTokenKind;
begin
  if  CSS_PropKeyComp(98) then
    Result := tkCssProp
  else
    Result := tkCssPropUndef;
end;

function TSynWebSyn.CSS_PropFunc101: TtkTokenKind;
begin
  if  CSS_PropKeyComp(108) then
    Result := tkCssProp
  else
    Result := tkCssPropUndef;
end;

function TSynWebSyn.CSS_PropFunc102: TtkTokenKind;
begin
  if  CSS_PropKeyComp(47) then
    Result := tkCssProp
  else
    Result := tkCssPropUndef;
end;

function TSynWebSyn.CSS_PropFunc103: TtkTokenKind;
begin
  if  CSS_PropKeyComp(43) then
    Result := tkCssProp
  else
    Result := tkCssPropUndef;
end;

function TSynWebSyn.CSS_PropFunc105: TtkTokenKind;
begin
  if  CSS_PropKeyComp(18) or
      CSS_PropKeyComp(63) then
    Result := tkCssProp
  else
    Result := tkCssPropUndef;
end;

function TSynWebSyn.CSS_PropFunc106: TtkTokenKind;
begin
  if  CSS_PropKeyComp(13) then
    Result := tkCssProp
  else
    Result := tkCssPropUndef;
end;

function TSynWebSyn.CSS_PropFunc107: TtkTokenKind;
begin
  if  CSS_PropKeyComp(28) then
    Result := tkCssProp
  else
    Result := tkCssPropUndef;
end;

function TSynWebSyn.CSS_PropFunc108: TtkTokenKind;
begin
  if  CSS_PropKeyComp(51) or
      CSS_PropKeyComp(88) then
    Result := tkCssProp
  else
    Result := tkCssPropUndef;
end;

function TSynWebSyn.CSS_PropFunc110: TtkTokenKind;
begin
  if  CSS_PropKeyComp(113) then
    Result := tkCssProp
  else
    Result := tkCssPropUndef;
end;

function TSynWebSyn.CSS_PropFunc111: TtkTokenKind;
begin
  if  CSS_PropKeyComp(44) then
    Result := tkCssProp
  else
    Result := tkCssPropUndef;
end;

function TSynWebSyn.CSS_PropFunc112: TtkTokenKind;
begin
  if  CSS_PropKeyComp(4) or
      CSS_PropKeyComp(22) then
    Result := tkCssProp
  else
    Result := tkCssPropUndef;
end;

function TSynWebSyn.CSS_PropFunc114: TtkTokenKind;
begin
  if  CSS_PropKeyComp(106) then
    Result := tkCssProp
  else
    Result := tkCssPropUndef;
end;

function TSynWebSyn.CSS_PropFunc115: TtkTokenKind;
begin
  if  CSS_PropKeyComp(99) then
    Result := tkCssProp
  else
    Result := tkCssPropUndef;
end;

function TSynWebSyn.CSS_PropFunc116: TtkTokenKind;
begin
  if  CSS_PropKeyComp(74) or
      CSS_PropKeyComp(102) then
    Result := tkCssProp
  else
    Result := tkCssPropUndef;
end;

function TSynWebSyn.CSS_PropFunc117: TtkTokenKind;
begin
  if  CSS_PropKeyComp(49) or
      CSS_PropKeyComp(89) or
      CSS_PropKeyComp(95) then
    Result := tkCssProp
  else
    Result := tkCssPropUndef;
end;

function TSynWebSyn.CSS_PropFunc121: TtkTokenKind;
begin
  if  CSS_PropKeyComp(50) or
      CSS_PropKeyComp(76) then
    Result := tkCssProp
  else
    Result := tkCssPropUndef;
end;

function TSynWebSyn.CSS_PropFunc122: TtkTokenKind;
begin
  if  CSS_PropKeyComp(56) then
    Result := tkCssProp
  else
    Result := tkCssPropUndef;
end;

function TSynWebSyn.CSS_PropFunc124: TtkTokenKind;
begin
  if  CSS_PropKeyComp(23) then
    Result := tkCssProp
  else
    Result := tkCssPropUndef;
end;

function TSynWebSyn.CSS_PropFunc126: TtkTokenKind;
begin
  if  CSS_PropKeyComp(12) then
    Result := tkCssProp
  else
    Result := tkCssPropUndef;
end;

function TSynWebSyn.CSS_PropFunc128: TtkTokenKind;
begin
  if  CSS_PropKeyComp(8) or
      CSS_PropKeyComp(61) then
    Result := tkCssProp
  else
    Result := tkCssPropUndef;
end;

function TSynWebSyn.CSS_PropFunc130: TtkTokenKind;
begin
  if  CSS_PropKeyComp(15) or
      CSS_PropKeyComp(54) then
    Result := tkCssProp
  else
    Result := tkCssPropUndef;
end;

function TSynWebSyn.CSS_PropFunc131: TtkTokenKind;
begin
  if  CSS_PropKeyComp(17) then
    Result := tkCssProp
  else
    Result := tkCssPropUndef;
end;

function TSynWebSyn.CSS_PropFunc136: TtkTokenKind;
begin
  if  CSS_PropKeyComp(107) then
    Result := tkCssProp
  else
    Result := tkCssPropUndef;
end;

function TSynWebSyn.CSS_PropFunc138: TtkTokenKind;
begin
  if  CSS_PropKeyComp(25) or
      CSS_PropKeyComp(57) then
    Result := tkCssProp
  else
    Result := tkCssPropUndef;
end;

function TSynWebSyn.CSS_PropFunc139: TtkTokenKind;
begin
  if  CSS_PropKeyComp(27) then
    Result := tkCssProp
  else
    Result := tkCssPropUndef;
end;

function TSynWebSyn.CSS_PropFunc140: TtkTokenKind;
begin
  if  CSS_PropKeyComp(3) or
      CSS_PropKeyComp(71) then
    Result := tkCssProp
  else
    Result := tkCssPropUndef;
end;

function TSynWebSyn.CSS_PropFunc141: TtkTokenKind;
begin
  if  CSS_PropKeyComp(73) then
    Result := tkCssProp
  else
    Result := tkCssPropUndef;
end;

function TSynWebSyn.CSS_PropFunc142: TtkTokenKind;
begin
  if  CSS_PropKeyComp(6) then
    Result := tkCssProp
  else
    Result := tkCssPropUndef;
end;

function TSynWebSyn.CSS_PropFunc144: TtkTokenKind;
begin
  if  CSS_PropKeyComp(36) then
    Result := tkCssProp
  else
    Result := tkCssPropUndef;
end;

function TSynWebSyn.CSS_PropFunc148: TtkTokenKind;
begin
  if  CSS_PropKeyComp(16) then
    Result := tkCssProp
  else
    Result := tkCssPropUndef;
end;

function TSynWebSyn.CSS_PropFunc149: TtkTokenKind;
begin
  if  CSS_PropKeyComp(19) then
    Result := tkCssProp
  else
    Result := tkCssPropUndef;
end;

function TSynWebSyn.CSS_PropFunc150: TtkTokenKind;
begin
  if  CSS_PropKeyComp(21) then
    Result := tkCssProp
  else
    Result := tkCssPropUndef;
end;

function TSynWebSyn.CSS_PropFunc154: TtkTokenKind;
begin
  if  CSS_PropKeyComp(101) then
    Result := tkCssProp
  else
    Result := tkCssPropUndef;
end;

function TSynWebSyn.CSS_PropFunc156: TtkTokenKind;
begin
  if  CSS_PropKeyComp(26) then
    Result := tkCssProp
  else
    Result := tkCssPropUndef;
end;

function TSynWebSyn.CSS_PropFunc158: TtkTokenKind;
begin
  if  CSS_PropKeyComp(72) then
    Result := tkCssProp
  else
    Result := tkCssPropUndef;
end;

function TSynWebSyn.CSS_PropFunc167: TtkTokenKind;
begin
  if  CSS_PropKeyComp(20) then
    Result := tkCssProp
  else
    Result := tkCssPropUndef;
end;

function TSynWebSyn.CSS_PropFunc169: TtkTokenKind;
begin
  if  CSS_PropKeyComp(59) then
    Result := tkCssProp
  else
    Result := tkCssPropUndef;
end;

function TSynWebSyn.CSS_PropFunc172: TtkTokenKind;
begin
  if  CSS_PropKeyComp(9) then
    Result := tkCssProp
  else
    Result := tkCssPropUndef;
end;

function TSynWebSyn.CSS_PropFunc173: TtkTokenKind;
begin
  if  CSS_PropKeyComp(11) then
    Result := tkCssProp
  else
    Result := tkCssPropUndef;
end;

function TSynWebSyn.CSS_PropFunc174: TtkTokenKind;
begin
  if  CSS_PropKeyComp(103) then
    Result := tkCssProp
  else
    Result := tkCssPropUndef;
end;

function TSynWebSyn.CSS_PropFunc178: TtkTokenKind;
begin
  if  CSS_PropKeyComp(35) then
    Result := tkCssProp
  else
    Result := tkCssPropUndef;
end;

function TSynWebSyn.CSS_PropFunc182: TtkTokenKind;
begin
  if  CSS_PropKeyComp(2) then
    Result := tkCssProp
  else
    Result := tkCssPropUndef;
end;

function TSynWebSyn.CSS_PropFunc187: TtkTokenKind;
begin
  if  CSS_PropKeyComp(96) then
    Result := tkCssProp
  else
    Result := tkCssPropUndef;
end;

function TSynWebSyn.CSS_PropFunc190: TtkTokenKind;
begin
  if  CSS_PropKeyComp(10) then
    Result := tkCssProp
  else
    Result := tkCssPropUndef;
end;

function TSynWebSyn.CSS_PropFunc194: TtkTokenKind;
begin
  if  CSS_PropKeyComp(5) then
    Result := tkCssProp
  else
    Result := tkCssPropUndef;
end;

function TSynWebSyn.CSS_PropFunc220: TtkTokenKind;
begin
  if  CSS_PropKeyComp(58) then
    Result := tkCssProp
  else
    Result := tkCssPropUndef;
end;
